/**
 * lib/reports/screening/_web/primitives/AttestationCard.tsx — §5.2 document trail
 *
 * Notes:  Web parity for _pdf/primitives/AttestationCard.tsx.
 *         Version metadata, inputs hash, help URL, POPIA contact.
 */
import type { JSX } from "react"
import { fmtDate } from "@/lib/reports/screening/_primitives/theme"
import type { FitScoreReportData } from "@/lib/reports/screening/_primitives/theme"
import { BlockHeader } from "./BlockHeader"

function MetaRow({ label, value }: Readonly<{ label: string; value: string }>): JSX.Element {
  return (
    <div className="flex gap-4 mb-1 last:mb-0">
      <span className="font-mono text-[9px] text-muted-foreground w-24 shrink-0">{label}</span>
      <span className="font-mono text-[9px] text-foreground">{value}</span>
    </div>
  )
}

interface AttestationCardProps {
  data: FitScoreReportData
}

export function AttestationCard({ data }: Readonly<AttestationCardProps>): JSX.Element {
  const appUrl      = process.env.NEXT_PUBLIC_APP_URL ?? "https://app.pleks.co.za"
  const displayHost = appUrl.replace(/^https?:\/\//, "")
  const helpUrl     = `${displayHost}/help/fitscore-report/${data.interpretationVersion}`

  return (
    <div className="border border-border bg-card mb-5">
      <BlockHeader label="5.2" title="Document trail" rightTag={data.applicationRef} />
      <div className="px-4 py-4">
        <div className="pb-4 mb-4 border-b border-border">
          <MetaRow label="Engine"        value={data.engineVersion} />
          <MetaRow label="Narrative"     value={data.narrativeVersion} />
          <MetaRow label="Interpretation" value={data.interpretationVersion} />
          <MetaRow label="Synthesis"     value={data.synthesisVersion} />
          <MetaRow label="Inputs hash"   value={`sha256:${data.inputsHash}`} />
        </div>

        <p className="font-mono text-[10px] text-muted-foreground leading-relaxed mb-4">
          {`This report was generated by Pleks at ${fmtDate(data.generatedAt)} for application ${data.applicationRef}.`}
        </p>

        <div className="mb-3">
          <p className="font-mono text-[8px] uppercase tracking-widest text-muted-foreground mb-1">How to read this report</p>
          <p className="font-mono text-[9px] text-foreground">{helpUrl}</p>
        </div>

        <div>
          <p className="font-mono text-[8px] uppercase tracking-widest text-muted-foreground mb-1">POPIA access requests</p>
          <p className="font-mono text-[9px] text-foreground">privacy@pleks.co.za</p>
        </div>
      </div>
    </div>
  )
}
