import { formatZAR } from "@/lib/constants"

export interface TrustLedgerEntry {
  id: string
  date: string
  reference: string | null
  transaction_type: string
  description: string
  direction: "credit" | "debit"
  amount_cents: number
  property_name: string | null
}

const TYPE_LABELS: Record<string, string> = {
  rent_received:    "Rent received",
  deposit_received: "Deposit received",
  deposit_interest: "Deposit interest",
  expense_paid:     "Expense paid",
  management_fee:   "Management fee",
  owner_payment:    "Owner payout",
  deposit_returned: "Deposit returned",
  deposit_deduction:"Deposit deduction",
  adjustment:       "Adjustment",
}

export function formatTrustType(type: string): string {
  return TYPE_LABELS[type] ?? type.replaceAll("_", " ")
}

export function buildTrustLedgerCSV(entries: TrustLedgerEntry[]): string {
  const rows = [
    ["Date", "Reference", "Type", "Description", "Property", "In (ZAR)", "Out (ZAR)", "Balance"].join(","),
  ]
  let balance = 0
  for (const e of entries) {
    if (e.direction === "credit") { balance += e.amount_cents }
    else { balance -= e.amount_cents }
    const inAmt = e.direction === "credit" ? (e.amount_cents / 100).toFixed(2) : ""
    const outAmt = e.direction === "debit" ? (e.amount_cents / 100).toFixed(2) : ""
    rows.push([
      e.date,
      e.reference ?? "",
      formatTrustType(e.transaction_type),
      `"${(e.description ?? "").replaceAll('"', '""')}"`,
      e.property_name ?? "",
      inAmt,
      outAmt,
      (balance / 100).toFixed(2),
    ].join(","))
  }
  return rows.join("\n")
}

export function buildTrustLedgerHTML(
  entries: TrustLedgerEntry[],
  org: { name: string; logo_url?: string | null },
  filters: { from?: string; to?: string },
): string {
  const CSS = `
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, 'Segoe UI', sans-serif; font-size: 11px; color: #1a1a1a; padding: 20mm 15mm; }
    header { display: flex; align-items: center; gap: 16px; margin-bottom: 12px; }
    header img { height: 40px; }
    header .org-info h2 { font-size: 16px; margin-bottom: 2px; }
    header .org-info p { font-size: 10px; color: #666; }
    hr { border: none; border-top: 2px solid #0f172a; margin: 8px 0 16px; }
    h1 { font-size: 14px; margin-bottom: 4px; }
    .period { font-size: 10px; color: #666; margin-bottom: 16px; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
    th { text-align: left; font-size: 9px; text-transform: uppercase; color: #64748b; border-bottom: 1px solid #e2e8f0; padding: 6px 8px; }
    td { padding: 5px 8px; border-bottom: 1px solid #f1f5f9; font-size: 10px; }
    .text-right { text-align: right; }
    .text-green { color: #16a34a; }
    .text-red { color: #dc2626; }
    .balance { font-weight: 600; }
    .footer { margin-top: 24px; font-size: 9px; color: #94a3b8; text-align: center; }
  `

  let periodLabel = "All transactions"
  if (filters.from && filters.to) { periodLabel = `${filters.from} — ${filters.to}` }
  else if (filters.from) { periodLabel = `From ${filters.from}` }

  let runningBalance = 0
  const rows = entries.map((e) => {
    if (e.direction === "credit") { runningBalance += e.amount_cents }
    else { runningBalance -= e.amount_cents }
    const isNeg = runningBalance < 0
    return `
      <tr>
        <td>${e.date}</td>
        <td>${e.reference ?? "—"}</td>
        <td>${formatTrustType(e.transaction_type)}</td>
        <td>${e.description ?? ""}</td>
        <td>${e.property_name ?? "—"}</td>
        <td class="text-right text-green">${e.direction === "credit" ? formatZAR(e.amount_cents) : ""}</td>
        <td class="text-right text-red">${e.direction === "debit" ? formatZAR(e.amount_cents) : ""}</td>
        <td class="text-right balance ${isNeg ? "text-red" : ""}">${formatZAR(Math.abs(runningBalance))}</td>
      </tr>`
  }).join("")

  return `<!DOCTYPE html><html><head><meta charset="utf-8"><style>${CSS}</style></head><body>
    <header>
      ${org.logo_url ? `<img src="${org.logo_url}" alt="${org.name}">` : ""}
      <div class="org-info"><h2>${org.name}</h2></div>
    </header>
    <hr>
    <h1>Trust Account Ledger</h1>
    <div class="period">${periodLabel}</div>
    <table>
      <thead><tr>
        <th>Date</th><th>Reference</th><th>Type</th><th>Description</th><th>Property</th>
        <th class="text-right">In</th><th class="text-right">Out</th><th class="text-right">Balance</th>
      </tr></thead>
      <tbody>${rows}</tbody>
    </table>
    <div class="footer">Generated by Pleks — ${new Date().toLocaleDateString("en-ZA")}</div>
  </body></html>`
}
