import { formatZAR } from "@/lib/constants"
import { formatDateShort, formatPeriodLabel } from "./periods"
import type {
  PortfolioSummaryData,
  IncomeCollectionData,
  ArrearsAgingData,
  RentRollData,
} from "./types"

interface OrgInfo {
  name: string
  logo_url?: string | null
  address?: string | null
  phone?: string | null
  email?: string | null
}

const REPORT_CSS = `
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; font-size: 11px; color: #1a1a1a; padding: 20mm 15mm; }
  header { display: flex; align-items: center; gap: 16px; margin-bottom: 12px; }
  header img { height: 40px; }
  header .org-info h2 { font-size: 16px; margin-bottom: 2px; }
  header .org-info p { font-size: 10px; color: #666; }
  hr { border: none; border-top: 2px solid #0f172a; margin: 8px 0 16px; }
  h1 { font-size: 14px; margin-bottom: 12px; }
  h2 { font-size: 12px; margin: 16px 0 8px; color: #334155; }
  .period { font-size: 10px; color: #666; margin-bottom: 16px; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
  th { text-align: left; font-size: 9px; text-transform: uppercase; color: #64748b; border-bottom: 1px solid #e2e8f0; padding: 6px 8px; }
  td { padding: 6px 8px; border-bottom: 1px solid #f1f5f9; font-size: 10px; }
  tr:last-child td { border-bottom: 2px solid #e2e8f0; font-weight: 600; }
  .metric-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin-bottom: 16px; }
  .metric { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 6px; padding: 10px; }
  .metric .label { font-size: 9px; color: #64748b; text-transform: uppercase; }
  .metric .value { font-size: 16px; font-weight: 700; margin-top: 2px; }
  .metric .sub { font-size: 9px; color: #94a3b8; }
  .text-right { text-align: right; }
  .text-danger { color: #dc2626; }
  .text-success { color: #16a34a; }
  .text-warning { color: #d97706; }
  .footer { margin-top: 24px; font-size: 9px; color: #94a3b8; text-align: center; }
`

function letterhead(org: OrgInfo): string {
  return `
    <header>
      ${org.logo_url ? `<img src="${org.logo_url}" alt="${org.name}">` : ""}
      <div class="org-info">
        <h2>${org.name}</h2>
        <p>${[org.address, org.phone, org.email].filter(Boolean).join(" | ")}</p>
      </div>
    </header>
    <hr>
  `
}

function footer(): string {
  return `<div class="footer">Generated by Pleks — ${formatDateShort(new Date())}</div>`
}

function wrapHTML(title: string, org: OrgInfo, body: string): string {
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><style>${REPORT_CSS}</style></head><body>${letterhead(org)}<h1>${title}</h1>${body}${footer()}</body></html>`
}

export function buildPortfolioSummaryHTML(data: PortfolioSummaryData, org: OrgInfo): string {
  const period = formatPeriodLabel(data.period.from, data.period.to)
  const body = `
    <div class="period">${period}</div>
    <div class="metric-grid">
      <div class="metric"><div class="label">Total Units</div><div class="value">${data.total_units}</div></div>
      <div class="metric"><div class="label">Occupied</div><div class="value">${data.occupied_units} <span class="sub">(${data.occupancy_rate}%)</span></div></div>
      <div class="metric"><div class="label">Vacant</div><div class="value">${data.vacant_units}</div></div>
      <div class="metric"><div class="label">Notice</div><div class="value">${data.notice_units}</div></div>
    </div>
    <div class="metric-grid">
      <div class="metric"><div class="label">Expected Income</div><div class="value">${formatZAR(data.expected_income_cents)}</div></div>
      <div class="metric"><div class="label">Collected</div><div class="value">${formatZAR(data.collected_income_cents)} <span class="sub">(${data.collection_rate}%)</span></div></div>
      <div class="metric"><div class="label">Outstanding</div><div class="value class="text-danger"">${formatZAR(data.outstanding_cents)}</div></div>
      <div class="metric"><div class="label">Total Arrears</div><div class="value class="text-danger"">${formatZAR(data.total_arrears_cents)}</div></div>
    </div>
    <h2>Per Property</h2>
    <table>
      <tr><th>Property</th><th>Units</th><th>Occupied</th><th class="text-right">Collection</th><th class="text-right">Maintenance</th></tr>
      ${data.properties.map((p) => `<tr>
        <td>${p.property_name}</td><td>${p.total_units}</td><td>${p.occupied_units} (${p.occupancy_rate}%)</td>
        <td class="text-right">${p.collection_rate}%</td><td class="text-right">${formatZAR(p.maintenance_spend_cents)}</td>
      </tr>`).join("")}
    </table>
  `
  return wrapHTML("Portfolio Performance", org, body)
}

export function buildRentRollHTML(data: RentRollData, org: OrgInfo): string {
  const body = `
    <div class="period">As at ${formatDateShort(data.as_at)}</div>
    <div class="metric-grid">
      <div class="metric"><div class="label">Total Units</div><div class="value">${data.total_units}</div></div>
      <div class="metric"><div class="label">Occupied</div><div class="value">${data.occupied_units} (${data.occupancy_rate}%)</div></div>
      <div class="metric"><div class="label">Monthly Rent</div><div class="value">${formatZAR(data.total_monthly_rent_cents)}</div></div>
      <div class="metric"><div class="label">Arrears</div><div class="value${data.total_arrears_cents > 0 ? " text-danger" : ""}">${formatZAR(data.total_arrears_cents)}</div></div>
    </div>
    <table>
      <tr><th>Property</th><th>Unit</th><th>Tenant</th><th class="text-right">Rent/mo</th><th>Dates</th><th>Method</th><th>Status</th><th class="text-right">Arrears</th></tr>
      ${data.rows.map((r) => {
        let leaseDateSuffix: string
        if (r.lease_end) { leaseDateSuffix = ` – ${formatDateShort(r.lease_end)}` }
        else if (r.lease_start) { leaseDateSuffix = " (M2M)" }
        else { leaseDateSuffix = "" }
        const leaseDates = r.lease_start ? `${formatDateShort(r.lease_start)}${leaseDateSuffix}` : "—"
        return `<tr>
        <td>${r.property_name}</td><td>${r.unit_number}</td><td>${r.tenant_name ?? "VACANT"}</td>
        <td class="text-right">${r.monthly_rent_cents ? formatZAR(r.monthly_rent_cents) : "—"}</td>
        <td>${leaseDates}</td>
        <td>${r.payment_method || "—"}</td><td>${r.status}</td>
        <td class="text-right${r.arrears_cents > 0 ? " text-danger" : ""}">${r.arrears_cents ? formatZAR(r.arrears_cents) : "—"}</td>
      </tr>`
      }).join("")}
    </table>
  `
  return wrapHTML("Rent Roll", org, body)
}

export function buildArrearsAgingHTML(data: ArrearsAgingData, org: OrgInfo): string {
  const body = `
    <div class="period">As at ${formatDateShort(data.as_at)}</div>
    <div class="metric-grid">
      <div class="metric"><div class="label">Tenants in Arrears</div><div class="value">${data.tenants_in_arrears}</div></div>
      <div class="metric"><div class="label">0-30 days</div><div class="value text-warning">${formatZAR(data.total_30d_cents)}</div></div>
      <div class="metric"><div class="label">31-60 days</div><div class="value text-warning">${formatZAR(data.total_60d_cents)}</div></div>
      <div class="metric"><div class="label">90+ days</div><div class="value text-danger">${formatZAR(data.total_90plus_cents)}</div></div>
    </div>
    <table>
      <tr><th>Tenant</th><th>Unit</th><th>Property</th><th class="text-right">0-30d</th><th class="text-right">31-60d</th><th class="text-right">61-90d</th><th class="text-right">90d+</th><th class="text-right">Total</th><th>Step</th></tr>
      ${data.cases.map((c) => `<tr>
        <td>${c.tenant_name}</td><td>${c.unit_number}</td><td>${c.property_name}</td>
        <td class="text-right">${c.arrears_30d_cents ? formatZAR(c.arrears_30d_cents) : "—"}</td>
        <td class="text-right">${c.arrears_60d_cents ? formatZAR(c.arrears_60d_cents) : "—"}</td>
        <td class="text-right">${c.arrears_90d_cents ? formatZAR(c.arrears_90d_cents) : "—"}</td>
        <td class="text-right">${c.arrears_90plus_cents ? formatZAR(c.arrears_90plus_cents) : "—"}</td>
        <td class="text-right">${formatZAR(c.total_cents)}</td>
        <td>Step ${c.current_step}</td>
      </tr>`).join("")}
    </table>
  `
  return wrapHTML("Arrears Aging Report", org, body)
}

export function buildIncomeCollectionHTML(data: IncomeCollectionData, org: OrgInfo): string {
  const period = formatPeriodLabel(data.period.from, data.period.to)
  const body = `
    <div class="period">${period}</div>
    <div class="metric-grid">
      <div class="metric"><div class="label">Expected</div><div class="value">${formatZAR(data.expected_income_cents)}</div></div>
      <div class="metric"><div class="label">Collected</div><div class="value">${formatZAR(data.collected_income_cents)} (${data.collection_rate}%)</div></div>
      <div class="metric"><div class="label">Outstanding</div><div class="value text-danger">${formatZAR(data.outstanding_cents)}</div></div>
      <div class="metric"><div class="label">DebiCheck</div><div class="value">${formatZAR(data.debicheck_collected_cents)} (${data.debicheck_count})</div></div>
    </div>
    <table>
      <tr><th>Unit</th><th>Tenant</th><th>Invoice</th><th class="text-right">Expected</th><th class="text-right">Received</th><th>Status</th></tr>
      ${data.invoices.map((inv) => `<tr>
        <td>${inv.unit_number}, ${inv.property_name}</td><td>${inv.tenant_name ?? "—"}</td><td>${inv.invoice_number}</td>
        <td class="text-right">${formatZAR(inv.total_amount_cents)}</td>
        <td class="text-right">${formatZAR(inv.amount_paid_cents)}</td>
        <td>${inv.status}</td>
      </tr>`).join("")}
    </table>
  `
  return wrapHTML("Income Collection Report", org, body)
}

export { wrapHTML, REPORT_CSS, letterhead }
