/**
 * Token hydration page — validates a ?token= link and sets the tenant
 * session cookie, then redirects to /portal.
 *
 * URL: /portal/access?token=<uuid>
 * Generated by: generateTenantPortalLink() and shared by agent via WhatsApp
 */

import { redirect } from "next/navigation"
import { cookies } from "next/headers"
import { createServiceClient } from "@/lib/supabase/server"

const COOKIE_NAME = "pleks_tenant_token"
const COOKIE_MAX_AGE = 90 * 24 * 60 * 60 // 90 days in seconds

export default async function PortalAccessPage({
  searchParams,
}: {
  searchParams: Promise<{ token?: string }>
}) {
  const { token } = await searchParams

  if (!token) {
    return (
      <div className="flex min-h-screen items-center justify-center px-4">
        <div className="text-center max-w-sm">
          <p className="text-lg font-semibold mb-2">Invalid portal link</p>
          <p className="text-sm text-muted-foreground">
            This link is missing a valid access token. Please use the link sent by your agent.
          </p>
        </div>
      </div>
    )
  }

  const service = await createServiceClient()

  const { data: tokenRecord, error } = await service
    .from("tenant_portal_tokens")
    .select("id, token, expires_at")
    .eq("token", token)
    .eq("revoked", false)
    .gt("expires_at", new Date().toISOString())
    .single()

  if (error || !tokenRecord) {
    return (
      <div className="flex min-h-screen items-center justify-center px-4">
        <div className="text-center max-w-sm">
          <p className="text-lg font-semibold mb-2">Link expired or invalid</p>
          <p className="text-sm text-muted-foreground">
            This portal link has expired or been revoked. Please ask your agent to send a new link.
          </p>
        </div>
      </div>
    )
  }

  // Set the token cookie and redirect to portal
  const cookieStore = await cookies()
  cookieStore.set(COOKIE_NAME, token, {
    httpOnly: true,
    secure: process.env.NODE_ENV === "production",
    sameSite: "lax",
    path: "/portal",
    maxAge: COOKIE_MAX_AGE,
  })

  redirect("/portal")
}
