/**
 * app/(tenant)/tenant/access/page.tsx — token-based portal login gate
 *
 * Route:  /tenant/access?token=<uuid>
 * Auth:   none (public page — token is the credential)
 * Data:   tenant_portal_tokens (validate), audit_log (write on success — BUILD_63)
 * Notes:  Token links are generated by generateTenantPortalLink() and sent via WhatsApp.
 *         Magic-link (Supabase email) path audit is deferred to a later phase.
 */

import { redirect } from "next/navigation"
import { cookies, headers } from "next/headers"
import { createServiceClient } from "@/lib/supabase/server"

const COOKIE_NAME = "pleks_tenant_token"
const COOKIE_MAX_AGE = 90 * 24 * 60 * 60 // 90 days

export default async function PortalAccessPage({
  searchParams,
}: {
  searchParams: Promise<{ token?: string }>
}) {
  const { token } = await searchParams

  if (!token) {
    return (
      <div className="flex min-h-screen items-center justify-center px-4">
        <div className="text-center max-w-sm">
          <p className="text-lg font-semibold mb-2">Invalid portal link</p>
          <p className="text-sm text-muted-foreground">
            This link is missing a valid access token. Please use the link sent by your agent.
          </p>
        </div>
      </div>
    )
  }

  const service = await createServiceClient()

  const { data: tokenRecord, error } = await service
    .from("tenant_portal_tokens")
    .select("id, token, expires_at, tenant_id, org_id")
    .eq("token", token)
    .eq("revoked", false)
    .gt("expires_at", new Date().toISOString())
    .single()

  if (error || !tokenRecord) {
    return (
      <div className="flex min-h-screen items-center justify-center px-4">
        <div className="text-center max-w-sm">
          <p className="text-lg font-semibold mb-2">Link expired or invalid</p>
          <p className="text-sm text-muted-foreground">
            This portal link has expired or been revoked. Please ask your agent to send a new link.
          </p>
        </div>
      </div>
    )
  }

  // Set the session cookie
  const cookieStore = await cookies()
  cookieStore.set(COOKIE_NAME, token, {
    httpOnly: true,
    secure: process.env.NODE_ENV === "production",
    sameSite: "lax",
    path: "/tenant",
    maxAge: COOKIE_MAX_AGE,
  })

  // Audit the token login moment (BUILD_63 §9.2 — Tribunal evidence trail)
  const headerStore = await headers()
  const ip = headerStore.get("x-forwarded-for")?.split(",")[0]?.trim() ?? null
  void service.from("audit_log").insert({
    org_id:      tokenRecord.org_id,
    table_name:  "tenant_portal_tokens",
    record_id:   tokenRecord.tenant_id,
    action:      "UPDATE",
    changed_by:  null,
    new_values:  {
      event:        "tenant_portal_login",
      auth_method:  "token_link",
      tenant_id:    tokenRecord.tenant_id,
      token_id:     tokenRecord.id,
      ip_address:   ip,
      logged_in_at: new Date().toISOString(),
    },
  })

  redirect("/tenant")
}
