/**
 * scripts/gen-template-seed.mts — generate the comms-template review doc + seed SQL (ADDENDUM_70E E3)
 *
 * The ONLY path from the typed SYSTEM_TEMPLATE_SEEDS source to:
 *   1. the human-readable REVIEW DOC (for CD) — bodies as they'll send, tokens preserved
 *   2. the SEED SQL (for document_templates) — idempotent INSERTs, NOT run here
 * Drift-proof by construction: review doc and seed come from one source. Run: tsx scripts/gen-template-seed.mts
 */

import { writeFileSync, mkdirSync } from "node:fs"
import { resolve, dirname } from "node:path"
import { fileURLToPath } from "node:url"
import { SYSTEM_TEMPLATE_SEEDS } from "../lib/comms/templates/seed/index"
import { renderSeedReview } from "../lib/comms/templates/seed/render"
import type { TemplateSeed } from "../lib/comms/templates/seed/types"

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..")
const REVIEW_OUT = resolve(ROOT, "brief/build/_ADDENDUM/ADDENDUM_70G_SEED_REVIEW.generated.md")
const SQL_OUT = resolve(ROOT, "lib/comms/templates/seed/generated/document_templates.seed.generated.sql")

const byClass = (c: string) => SYSTEM_TEMPLATE_SEEDS.filter((s) => s.commsClass === c)

// ── Review doc ───────────────────────────────────────────────────────────────────
function buildReview(): string {
  const counts = `service ${byClass("service").length} · correspondence ${byClass("correspondence").length} · statutory ${byClass("statutory").length}`
  const sections = ["statutory", "correspondence", "service"]
    .map((cls) => {
      const seeds = byClass(cls)
      if (seeds.length === 0) return ""
      const body = seeds.map(renderSeedReview).join("\n---\n\n")
      return `## ${cls.toUpperCase()} (${seeds.length})\n\n${body}`
    })
    .filter(Boolean)
    .join("\n")
  return [
    "# ADDENDUM_70G — Centralized template review (GENERATED — do not edit)",
    "",
    "> **Generated** by `scripts/gen-template-seed.mts` from `lib/comms/templates/seed/` — the typed SSOT.",
    "> Do not edit this file; edit the seed module and regenerate. This is the doc CD reviews; the same",
    "> source emits `document_templates.seed.generated.sql` (not yet seeded — pending CD's review pass).",
    "",
    `**Templates folded:** ${SYSTEM_TEMPLATE_SEEDS.length} (${counts})`,
    "**Convention:** `{{tokens}}` preserved (template structure, not a sample fill); `cpaConditional`",
    "shows both branches; `[Agent signature]` / ECTA footer are the slot effects.",
    "",
    "---",
    "",
    sections,
  ].join("\n")
}

// ── Seed SQL ─────────────────────────────────────────────────────────────────────
const q = (s: string) => s.replace(/'/g, "''")
const jsonb = (v: unknown) => `'${q(JSON.stringify(v))}'::jsonb`
const arr = (xs?: string[]) => (xs && xs.length ? `ARRAY[${xs.map((x) => `'${q(x)}'`).join(", ")}]` : "NULL")
const txt = (s?: string) => (s ? `'${q(s)}'` : "NULL")

function seedInsert(s: TemplateSeed): string {
  const bodyBlocks = s.body ?? (s.variants?.professional ?? null)
  return [
    "INSERT INTO document_templates (",
    "  scope, template_type, name, description, category, comms_class, template_key,",
    "  subject, merge_fields, version, legal_review_ref, is_deletable, body_blocks, body_variants",
    ")",
    "SELECT 'system', " +
      [`'${s.channel}'`, txt(s.name), txt(s.description), txt(s.category), `'${s.commsClass}'`, txt(s.key)].join(", ") + ",",
    `  ${txt(s.subject)}, ${arr(s.mergeFields)}, 1, ${txt(s.legalReviewRef)}, false,`,
    `  ${bodyBlocks ? jsonb(bodyBlocks) : "NULL"}, ${s.variants ? jsonb(s.variants) : "NULL"}`,
    "WHERE NOT EXISTS (",
    `  SELECT 1 FROM document_templates WHERE scope='system' AND template_key='${q(s.key)}' AND template_type='${s.channel}'`,
    ");",
  ].join("\n")
}

function buildSql(): string {
  return [
    "-- document_templates.seed.generated.sql — GENERATED by scripts/gen-template-seed.mts (ADDENDUM_70E E3)",
    "-- DO NOT EDIT. Regenerate from lib/comms/templates/seed/. NOT YET APPLIED — pending CD review pass.",
    "-- Idempotent (WHERE NOT EXISTS). Apply only after sign-off.",
    "",
    SYSTEM_TEMPLATE_SEEDS.map(seedInsert).join("\n\n"),
    "",
  ].join("\n")
}

mkdirSync(dirname(SQL_OUT), { recursive: true })
writeFileSync(REVIEW_OUT, buildReview(), "utf8")
writeFileSync(SQL_OUT, buildSql(), "utf8")
console.log(`✓ wrote ${SYSTEM_TEMPLATE_SEEDS.length} templates`)
console.log(`  review → ${REVIEW_OUT.replace(ROOT, ".")}`)
console.log(`  seed   → ${SQL_OUT.replace(ROOT, ".")} (NOT applied)`)
