-- ==================================================================================================
-- supabase/reconcile/01_reconcile.sql — PRODUCTION RECONCILIATION, 2026-07-13
--
-- ⚠ GENERATED by supabase/reconcile/assemble.py — do not hand-edit. The two function bodies are
--   lifted VERBATIM from supabase/migrations/004_leases_financials.sql, which stays the SSOT. A
--   reconciliation script that retypes a money function is a second source of truth waiting to drift
--   from the first.
--
-- WHAT THIS IS. Production has drifted BEHIND its own committed migrations. The schema-contract
-- manifest — generated FROM prod — is what caught it. This brings prod up to the files.
--
-- ONE script. Idempotent (CREATE OR REPLACE / DROP CONSTRAINT IF EXISTS). Safe to run twice.
-- Every statement is EITHER a real fix OR a verified no-op, and says which.
--
-- WHY IT IS SAFE:
--   · Every constraint change is a WIDENING — it can only admit values it previously rejected, so no
--     existing row can be invalidated by it.
--   · Every function change is CREATE OR REPLACE.
--   · It runs in ONE transaction. Any failure aborts the lot and prod is untouched.
--   · Prod holds ZERO deposit_charges, ZERO deposit_reconciliations and ZERO trust_transactions.
--     Nothing is restated because nothing needs to be.
--
-- ROLLBACK POSTURE. There is nothing better to roll back TO: production currently REJECTS values its
-- own code writes, and is MISSING a function its own live code calls. Reverting restores two
-- silent-failure bugs.
--
-- PROVEN, NOT ASSERTED. Proved on a local stack driven to PRODUCTION'S state first
-- (00_simulate_prod_drift.sql), so the test suite FAILS before this runs and PASSES after. On a stack
-- built from the migration files there is nothing to fix, and "it replays green" would have proved
-- only that the files agree with themselves.
-- ==================================================================================================

BEGIN;

-- §1 ── REAL FIX · THE MOST URGENT ITEM ON THE BOARD ────────────────────────────────────────────
--
--     Every POPIA consent-verification audit row has FAILED TO WRITE for ~6 weeks.
--
-- ADDENDUM_14F (010 §25, 2026-05-14) added eight consent_* values to auth_events_event_type_check.
-- BUILD_AUTH_RESOLVER (010 §30.2, 2026-05-27 — thirteen days later) did a DROP+ADD on the SAME
-- constraint to add the resolver types, and its new value list simply OMITTED all eight. A DROP+ADD
-- must RE-STATE every value it means to keep. Migrations replay top-to-bottom, so the narrow list won.
--
-- /api/consent/send-code and /api/consent/verify-code write consent_code_sent, consent_code_verified,
-- consent_verification_failed and consent_verification_locked_out on every SMS consent round. Postgres
-- has rejected every one with a 23514 since 2026-05-27. The route console.errors it AND RETURNS 200 —
-- so the tenant sees "verified" while the POPIA record the flow exists to create does not exist.
--
-- Confirmed against prod: 173 rows in auth_events, ZERO of any consent_* type. Not one has landed.
--
-- The list below is prod's CURRENT set PLUS the eight restored — additive, evicting nothing. The
-- resolver types survive; a dbtest pins BOTH halves, because the original defect was a DROP+ADD that
-- kept only what its author happened to have in mind.
ALTER TABLE auth_events DROP CONSTRAINT IF EXISTS auth_events_event_type_check;
ALTER TABLE auth_events ADD CONSTRAINT auth_events_event_type_check CHECK (event_type IN (
  -- session / credential (unchanged)
  'login_success', 'login_failure', 'logout', 'password_changed', 'email_changed',
  'totp_enrolled', 'totp_unenrolled', 'totp_verified', 'totp_failed',
  'passkey_enrolled', 'passkey_unenrolled', 'passkey_verified', 'passkey_failed',
  'step_up_challenged', 'step_up_verified', 'step_up_failed',
  'session_revoked', 'new_device_detected', 'recovery_used', 'role_switched',
  'tenant_portal_login', 'landlord_portal_login', 'supplier_portal_login', 'agent_portal_login',
  -- resolver (§30.2 — kept)
  'resolver_decision', 'email_existence_check', 'membership_claimed',
  'membership_claim_blocked_by_invariant',
  -- consent (§25 — RESTORED; these are WRITTEN by the live consent routes)
  'consent_code_sent', 'consent_code_verified', 'consent_verification_failed',
  'consent_verification_locked_out', 'consent_email_link_sent', 'consent_email_link_verified',
  'consent_special_information_given', 'consent_special_information_revoked'
));


-- §2 ── REAL FIX · A LIVE MONEY PATH CALLS A FUNCTION PRODUCTION DOES NOT HAVE ──────────────────
--
-- `allocate_payment_atomic` is ~100 lines of clause-6.6 allocation: interest charges oldest-first,
-- then open invoices oldest-first, surplus recorded, arrears totals refreshed, the money event
-- audited. It is defined in 004 and WAS NEVER DEPLOYED. Production does not have it.
--
-- The LIVE `settle_deposit_charge_pattern_a_atomic` PERFORMs it. So the moment anyone settles a
-- deposit against a tenant's arrears — /leases/[leaseId]/deposit → Disburse → Pattern A — Postgres
-- raises "function allocate_payment_atomic does not exist", mid-settlement.
--
-- ARMED, NOT LIVE: prod holds ZERO deposit_charges and ZERO deposit_reconciliations, so nothing has
-- stepped on it yet. It fires on the founding agent's FIRST deposit-against-arrears settlement, which
-- is among the most ordinary things they will do.
--
-- FILE-AHEAD → DEPLOY. This is not dead code, and the opposite fix (deleting it) would have removed a
-- function that production's own live code depends on. Direction is the load-bearing axis.

CREATE OR REPLACE FUNCTION allocate_payment_atomic(
  p_org_id       uuid,
  p_payment_id   uuid,
  p_lease_id     uuid,
  p_amount_cents bigint,
  p_actor        uuid
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_remaining        bigint := p_amount_cents;
  v_interest_applied bigint := 0;
  v_rent_applied     bigint := 0;
  v_apply            bigint;
  v_new_balance      bigint;
  v_allocated        jsonb  := '[]'::jsonb;
  v_case_ids         uuid[] := ARRAY[]::uuid[];
  r_charge           record;
  r_inv              record;
  v_case             uuid;
BEGIN
  -- STEP 1 — interest charges, oldest charge_date first (clause 6.6: interest/damages before rent).
  FOR r_charge IN
    SELECT id, interest_cents, arrears_case_id
    FROM arrears_interest_charges
    WHERE lease_id = p_lease_id AND waived = false
    ORDER BY charge_date ASC
  LOOP
    EXIT WHEN v_remaining <= 0;
    v_apply := LEAST(v_remaining, r_charge.interest_cents);
    UPDATE arrears_interest_charges
      SET waived = true,
          waived_reason = 'Consumed by payment ' || p_payment_id,
          waived_at = now()
      WHERE id = r_charge.id;
    v_remaining        := v_remaining - v_apply;
    v_interest_applied := v_interest_applied + v_apply;
    IF r_charge.arrears_case_id IS NOT NULL THEN
      v_case_ids := array_append(v_case_ids, r_charge.arrears_case_id);
    END IF;
  END LOOP;

  -- STEP 2 — open rent invoices, oldest due_date first.
  FOR r_inv IN
    SELECT id, balance_cents
    FROM rent_invoices
    WHERE lease_id = p_lease_id AND status IN ('open', 'partial', 'overdue')
    ORDER BY due_date ASC
  LOOP
    EXIT WHEN v_remaining <= 0;
    IF COALESCE(r_inv.balance_cents, 0) <= 0 THEN CONTINUE; END IF;
    v_apply       := LEAST(v_remaining, r_inv.balance_cents);
    v_new_balance := r_inv.balance_cents - v_apply;
    UPDATE rent_invoices SET
      amount_paid_cents = COALESCE(amount_paid_cents, 0) + v_apply,
      balance_cents     = v_new_balance,
      status            = CASE WHEN v_new_balance <= 0 THEN 'paid' ELSE 'partial' END,
      paid_at           = CASE WHEN v_new_balance <= 0 THEN now() ELSE NULL END
    WHERE id = r_inv.id;
    v_remaining    := v_remaining - v_apply;
    v_rent_applied := v_rent_applied + v_apply;
    v_allocated    := v_allocated || jsonb_build_array(
                        jsonb_build_object('invoice_id', r_inv.id, 'amount_cents', v_apply));
  END LOOP;

  -- STEP 3 — record the breakdown on the payment (surplus = unallocated remainder).
  UPDATE payments SET
    interest_applied_cents = v_interest_applied,
    surplus_cents          = v_remaining,
    surplus_disposition    = CASE WHEN v_remaining > 0 THEN 'pending' ELSE NULL END,
    allocated_invoices     = v_allocated
  WHERE id = p_payment_id;

  -- STEP 4 — refresh arrears interest totals for each touched case.
  FOR v_case IN SELECT DISTINCT unnest(v_case_ids) LOOP
    PERFORM refresh_arrears_interest_total(v_case);
  END LOOP;

  -- STEP 5 — audit the money event with its breakdown (mirrors the old TS payment_allocated audit).
  INSERT INTO audit_log (org_id, table_name, record_id, action, changed_by, new_values)
  VALUES (p_org_id, 'payments', p_payment_id, 'UPDATE', p_actor, jsonb_build_object(
    'action', 'payment_allocated', 'lease_id', p_lease_id,
    'interest_applied_cents', v_interest_applied,
    'rent_applied_cents', v_rent_applied,
    'surplus_cents', v_remaining));

  RETURN jsonb_build_object(
    'interest_applied_cents', v_interest_applied,
    'rent_applied_cents', v_rent_applied,
    'surplus_cents', v_remaining,
    'allocated_invoices', v_allocated);
END;
$$;

-- §3 ── REAL FIX · record_payment_atomic IS THE PRE-#134 BODY IN PRODUCTION ─────────────────────
--
-- BODY DRIFT — the class a presence check cannot see. The function exists in BOTH, and they are not
-- the same function. Production's body credits the selected invoice inline and NEVER calls
-- allocate_payment_atomic: no interest-first allocation, no surplus spread across invoices, no
-- arrears refresh, no payment_allocated audit row.
--
-- The live signature of exactly this: 191 UNWAIVED arrears_interest_charges in production. Prod's
-- body has never consumed a single one, so interest keeps accruing on debt that payments should have
-- cleared.
--
-- This is the #134 body from 004, verbatim. It DEPENDS on §2, which lands first in this same
-- transaction — deploying it without allocate_payment_atomic would break payments outright.

CREATE OR REPLACE FUNCTION record_payment_atomic(
  p_org_id         uuid,
  p_invoice_id     uuid,
  p_amount_cents   bigint,
  p_payment_date   date,
  p_method         text,
  p_reference      text,
  p_recorded_by    uuid,
  p_receipt_number text,
  p_notes          text
) RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_inv        rent_invoices%ROWTYPE;
  v_payment_id uuid;
BEGIN
  -- Org-scope guard: the invoice MUST belong to the caller's org (service_role bypasses RLS).
  SELECT * INTO v_inv FROM rent_invoices WHERE id = p_invoice_id AND org_id = p_org_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'record_payment_atomic: invoice % not found in org %', p_invoice_id, p_org_id
      USING ERRCODE = 'no_data_found';
  END IF;

  -- 1. payment (provenance only: invoice_id = the agent-selected invoice. Allocation in step 3 follows
  --    clause 6.6, so the money may land on interest / older invoices — surplus_cents + allocated_invoices
  --    are filled by allocate_payment_atomic, NOT pre-credited to the selected invoice).
  INSERT INTO payments (
    org_id, invoice_id, lease_id, tenant_id, amount_cents, payment_date, payment_method,
    reference, receipt_number, recorded_by, surplus_cents, surplus_disposition, allocated_invoices, notes
  ) VALUES (
    p_org_id, p_invoice_id, v_inv.lease_id, v_inv.tenant_id, p_amount_cents, p_payment_date, p_method,
    p_reference, p_receipt_number, p_recorded_by, 0, NULL, '[]'::jsonb, p_notes
  ) RETURNING id INTO v_payment_id;

  -- 2. trust posting (rent_received credit) — sovereignty + closed-period triggers fire here.
  INSERT INTO trust_transactions (
    org_id, transaction_type, direction, amount_cents, description,
    unit_id, lease_id, reference, invoice_id, statement_month, created_by, source, initiated_by
  ) VALUES (
    p_org_id, 'rent_received', 'credit', p_amount_cents,
    'Payment received — ' || upper(p_method) || CASE WHEN p_reference IS NOT NULL AND p_reference <> '' THEN ' ref: ' || p_reference ELSE '' END,
    v_inv.unit_id, v_inv.lease_id, p_receipt_number, p_invoice_id,
    date_trunc('month', CURRENT_DATE)::date, p_recorded_by, 'agency_bank', 'agent'
  );

  -- 3. clause-6.6 allocation — interest oldest-first, then open invoices oldest-first, surplus recorded.
  --    ONE allocation, in-transaction. Replaces the old "credit the selected invoice in full" step + the
  --    post-commit allocatePayment() that TOGETHER double-applied the amount (any partial / interest /
  --    older-invoice case). The selected invoice is advisory — the money follows clause-6.6 order.
  IF v_inv.lease_id IS NOT NULL THEN
    PERFORM allocate_payment_atomic(p_org_id, v_payment_id, v_inv.lease_id, p_amount_cents, p_recorded_by);
  END IF;

  RETURN v_payment_id;
END;
$$;

-- §4 ── REAL FIX · properties.scenario_type — SIX SCENARIOS CANNOT BE CREATED TODAY ─────────────
--
-- 012 widened this in the FILE, and the widening was never deployed. An agent who picks r6, r7, c5,
-- c6, m3 or m4 in the property wizard gets "Failed to create property". A LOUD failure — nothing has
-- been silently corrupted — but the feature simply does not work. FILE-AHEAD → deploy.
ALTER TABLE properties DROP CONSTRAINT IF EXISTS properties_scenario_type_check;
ALTER TABLE properties ADD CONSTRAINT properties_scenario_type_check CHECK (scenario_type IN (
  'r1', 'r2', 'r3', 'r4', 'r5', 'r6', 'r7',
  'c1', 'c2', 'c3', 'c4', 'c5', 'c6',
  'm1', 'm2', 'm3', 'm4',
  'other'
));


-- §5 ── REAL FIX · properties.insurance_policy_type — 'farm_specialist' ─────────────────────────
-- Same shape, smaller blast radius. Production's CURRENT list plus the value the file declares.
-- Additive. (My first draft of the drift simulator GUESSED this list and guessed wrong; it is now
-- prod's, queried verbatim. A simulator built on a guess proves nothing.)
ALTER TABLE properties DROP CONSTRAINT IF EXISTS properties_insurance_policy_type_check;
ALTER TABLE properties ADD CONSTRAINT properties_insurance_policy_type_check CHECK (
  insurance_policy_type = ANY (ARRAY[
    'standard_buildings', 'heritage_specialist', 'commercial_property', 'sectional_title',
    'farm_specialist', 'other'
  ])
);


-- §6 ── VERIFIED NO-OP · contractors.supplier_type ──────────────────────────────────────────────
-- Production has accepted these six values for months — widened out-of-band, never captured in any
-- migration. Re-stating it changes NOTHING live. It is here so a LOCAL stack rebuilt from the files
-- tells the same truth as production, which is the whole reason the vendor-import tests were failing
-- on values that work fine in prod. PROD-AHEAD → the file has caught up (005, already merged).
ALTER TABLE contractors DROP CONSTRAINT IF EXISTS contractors_supplier_type_check;
ALTER TABLE contractors ADD CONSTRAINT contractors_supplier_type_check CHECK (
  supplier_type IN ('contractor', 'recurring', 'both', 'managing_scheme', 'utility', 'other')
);


-- §7 ── VERIFIED NO-OP · consent_log.consent_type ───────────────────────────────────────────────
-- 'bank_details_import' is ALREADY live in production. Re-stated for the same reason as §6, so a
-- local stack and production agree. Changes nothing live.
ALTER TABLE consent_log DROP CONSTRAINT IF EXISTS consent_log_consent_type_check;
ALTER TABLE consent_log ADD CONSTRAINT consent_log_consent_type_check CHECK (consent_type IN (
  'credit_check', 'data_processing', 'marketing', 'trust_account_notice',
  'popia_application', 'lease_template_disclaimer', 'bank_details_import'
));

COMMIT;

-- ==================================================================================================
-- DELIBERATELY NOT IN THIS SCRIPT — each one a decision, not an omission
--
--   · check_trust_txn_period_open (the BEFORE-DELETE `RETURN NEW` swallow) — ALREADY FIXED IN PROD.
--     Verified 2026-07-13: production's body carries RETURN COALESCE(NEW, OLD). No DDL needed. It was
--     ranked #2 on the board; it is done.
--
--   · subscriptions.trial_tier = 'bespoke' — FILE-AHEAD, but INERT: the sole writer's TypeScript union
--     is ("steward" | "growth" | "portfolio" | "firm"), so no caller can pass it. Widening production
--     for a value nothing writes is speculation, not reconciliation. Left as an open register item.
--
--   · contacts.primary_role = 'company_contact' — PROD-AHEAD. The fix is to amend the FILE forward,
--     not to change production. No DDL.
--
--   · deposit_rate_status — NOT a manifest RED. The column does not exist and nothing references it:
--     the only two hits in the codebase are COMMENTS explaining why it was deliberately never
--     persisted (a stamped status column would have held a lease forever after its config was fixed).
--     schema-contract-scan is green.
--
-- ── D-GL-01 — RESOLVED: EXEMPT BY NATURE. DO NOT STAMP. No DDL. ────────────────────────────────
--
--   The lean is correct AND the collision is real — it is on trust_transactions, not
--   deposit_transactions, which is why a search of the latter found nothing:
--
--       CREATE UNIQUE INDEX idx_trust_txn_one_opening_per_period
--         ON public.trust_transactions (org_id, statement_month) WHERE (is_opening_balance = true)
--
--   Verified live in production. Stamping each GL row with its own month therefore caps the whole
--   import at ONE row per org per month — which the money-conservation test caught instantly (three
--   payments in one month → one landed, two rejected).
--
--   And the guard already handles it: check_trust_txn_insert_period_open RETURNS NEW when
--   statement_month IS NULL, and opening balances are NULL — so they already pass. An opening balance
--   is the STARTING LINE, not a back-dated transaction: it represents pre-cutover state the agency
--   managed under another system, and a period Pleks never reconciled cannot meaningfully be "closed"
--   against it. Exempt by nature. No stamp, no collision, nothing to deploy.
-- ==================================================================================================
