-- ==================================================================================================
-- supabase/reconcile/01_reconcile.sql — PRODUCTION RECONCILIATION, 2026-07-13
--
-- ⚠ GENERATED by supabase/reconcile/assemble.py — do not hand-edit. The two function bodies are
--   lifted VERBATIM from supabase/migrations/004_leases_financials.sql, which stays the SSOT. A
--   reconciliation script that retypes a money function is a second source of truth waiting to drift
--   from the first.
--
-- WHAT THIS IS. Production has drifted BEHIND its own committed migrations. The schema-contract
-- manifest — generated FROM prod — is what caught it. This brings prod up to the files.
--
-- ONE script. Idempotent (CREATE OR REPLACE / DROP CONSTRAINT IF EXISTS). Safe to run twice.
-- Every statement is EITHER a real fix OR a verified no-op, and says which.
--
-- WHY IT IS SAFE:
--   · Every constraint change is a WIDENING — it can only admit values it previously rejected, so no
--     existing row can be invalidated by it.
--   · Every function change is CREATE OR REPLACE.
--   · It runs in ONE transaction. Any failure aborts the lot and prod is untouched.
--   · Prod holds ZERO deposit_charges, ZERO deposit_reconciliations and ZERO trust_transactions.
--     Nothing is restated because nothing needs to be.
--
-- ROLLBACK POSTURE. There is nothing better to roll back TO: production currently REJECTS values its
-- own code writes, and is MISSING a function its own live code calls. Reverting restores two
-- silent-failure bugs.
--
-- PROVEN, NOT ASSERTED. Proved on a local stack driven to PRODUCTION'S state first
-- (00_simulate_prod_drift.sql), so the test suite FAILS before this runs and PASSES after. On a stack
-- built from the migration files there is nothing to fix, and "it replays green" would have proved
-- only that the files agree with themselves.
-- ==================================================================================================

BEGIN;

-- §1 ── REAL FIX · THE MOST URGENT ITEM ON THE BOARD ────────────────────────────────────────────
--
--     Every POPIA consent-verification audit row has FAILED TO WRITE for ~6 weeks.
--
-- ADDENDUM_14F (010 §25, 2026-05-14) added eight consent_* values to auth_events_event_type_check.
-- BUILD_AUTH_RESOLVER (010 §30.2, 2026-05-27 — thirteen days later) did a DROP+ADD on the SAME
-- constraint to add the resolver types, and its new value list simply OMITTED all eight. A DROP+ADD
-- must RE-STATE every value it means to keep. Migrations replay top-to-bottom, so the narrow list won.
--
-- /api/consent/send-code and /api/consent/verify-code write consent_code_sent, consent_code_verified,
-- consent_verification_failed and consent_verification_locked_out on every SMS consent round. Postgres
-- has rejected every one with a 23514 since 2026-05-27. The route console.errors it AND RETURNS 200 —
-- so the tenant sees "verified" while the POPIA record the flow exists to create does not exist.
--
-- Confirmed against prod: 173 rows in auth_events, ZERO of any consent_* type. Not one has landed.
--
-- The list below is prod's CURRENT set PLUS the eight restored — additive, evicting nothing. The
-- resolver types survive; a dbtest pins BOTH halves, because the original defect was a DROP+ADD that
-- kept only what its author happened to have in mind.
ALTER TABLE auth_events DROP CONSTRAINT IF EXISTS auth_events_event_type_check;
ALTER TABLE auth_events ADD CONSTRAINT auth_events_event_type_check CHECK (event_type IN (
  -- session / credential (unchanged)
  'login_success', 'login_failure', 'logout', 'password_changed', 'email_changed',
  'totp_enrolled', 'totp_unenrolled', 'totp_verified', 'totp_failed',
  'passkey_enrolled', 'passkey_unenrolled', 'passkey_verified', 'passkey_failed',
  'step_up_challenged', 'step_up_verified', 'step_up_failed',
  'session_revoked', 'new_device_detected', 'recovery_used', 'role_switched',
  'tenant_portal_login', 'landlord_portal_login', 'supplier_portal_login', 'agent_portal_login',
  -- resolver (§30.2 — kept)
  'resolver_decision', 'email_existence_check', 'membership_claimed',
  'membership_claim_blocked_by_invariant',
  -- consent (§25 — RESTORED; these are WRITTEN by the live consent routes)
  'consent_code_sent', 'consent_code_verified', 'consent_verification_failed',
  'consent_verification_locked_out', 'consent_email_link_sent', 'consent_email_link_verified',
  'consent_special_information_given', 'consent_special_information_revoked'
));


-- §2 ── REAL FIX · A LIVE MONEY PATH CALLS A FUNCTION PRODUCTION DOES NOT HAVE ──────────────────
--
-- `allocate_payment_atomic` is ~100 lines of clause-6.6 allocation: interest charges oldest-first,
-- then open invoices oldest-first, surplus recorded, arrears totals refreshed, the money event
-- audited. It is defined in 004 and WAS NEVER DEPLOYED. Production does not have it.
--
-- The LIVE `settle_deposit_charge_pattern_a_atomic` PERFORMs it. So the moment anyone settles a
-- deposit against a tenant's arrears — /leases/[leaseId]/deposit → Disburse → Pattern A — Postgres
-- raises "function allocate_payment_atomic does not exist", mid-settlement.
--
-- ARMED, NOT LIVE: prod holds ZERO deposit_charges and ZERO deposit_reconciliations, so nothing has
-- stepped on it yet. It fires on the founding agent's FIRST deposit-against-arrears settlement, which
-- is among the most ordinary things they will do.
--
-- FILE-AHEAD → DEPLOY. This is not dead code, and the opposite fix (deleting it) would have removed a
-- function that production's own live code depends on. Direction is the load-bearing axis.
