/**
 * lib/comms/templates/seed/channels.ts — WhatsApp + SMS + consent-OTP seeds (ADDENDUM_70E E3 / E4)
 *
 * Data:   non-email channels — WhatsApp (flavoured), SMS (some flavoured), consent OTP — folded from
 *         ADDENDUM_70D. All commsClass:"service". Plain-text only (paragraph blocks); no popiaSlot /
 *         signatureSlot / legalFooterSlot / salutation block / Tribunal.
 * Notes:  ⚠ Review carry-overs from 70D (kept verbatim for CD): the arrears WhatsApp/SMS "legal
 *         proceedings"/"letter of demand" threats (whatsapp.arrears_final_notice, sms.arrears_step2),
 *         the 48h deadline + "CPA s14" naming, and the WhatsApp→SMS truncation risk on >145-char bodies.
 *         WhatsApp keys here are seed keys; reconcile with the Meta-approved template names / 011 §
 *         whatsapp seeds at actual seed-time (E4). NOT seeded.
 */

import type { TemplateSeed } from "./types"

export const CHANNEL_SEEDS: TemplateSeed[] = [
  // ── WhatsApp (flavoured: friendly/professional/firm) — ADDENDUM_70D §A ───────────────────────
  {
    key: "whatsapp.rent_due_reminder",
    channel: "whatsapp",
    commsClass: "service",
    name: "Rent Due Reminder (WhatsApp)",
    description: "WhatsApp reminder that monthly rent is due on the 1st.",
    category: "statements",
    mergeFields: ["{{tenant.primary_contact_name}}", "{{lease.rent_amount}}", "{{unit.number}}"],
    legalReviewRef: "ADDENDUM_70D §A.1",
    variants: {
      friendly: [{ type: "paragraph", text: "Hi {{tenant.primary_contact_name}}, just a reminder that rent of {{lease.rent_amount}} is due on the 1st for {{unit.number}}. Thanks!" }],
      professional: [{ type: "paragraph", text: "Dear {{tenant.primary_contact_name}}, this is a reminder that rent of {{lease.rent_amount}} is due on the 1st for {{unit.number}}." }],
      firm: [{ type: "paragraph", text: "{{tenant.primary_contact_name}}, rent of {{lease.rent_amount}} is due on the 1st for {{unit.number}}. Please ensure timely payment." }],
    },
  },
  {
    key: "whatsapp.payment_received",
    channel: "whatsapp",
    commsClass: "service",
    name: "Payment Received (WhatsApp)",
    description: "WhatsApp confirmation that a rent payment was received and the account is up to date.",
    category: "statements",
    mergeFields: ["{{tenant.primary_contact_name}}", "{{lease.rent_amount}}", "{{unit.number}}"],
    legalReviewRef: "ADDENDUM_70D §A.2",
    variants: {
      friendly: [{ type: "paragraph", text: "Hi {{tenant.primary_contact_name}}, great news — your payment of {{lease.rent_amount}} for {{unit.number}} is in. Your account is all clear! 👍" }],
      professional: [{ type: "paragraph", text: "Dear {{tenant.primary_contact_name}}, your payment of {{lease.rent_amount}} for {{unit.number}} has been received. Your account is up to date." }],
      firm: [{ type: "paragraph", text: "{{tenant.primary_contact_name}}, payment of {{lease.rent_amount}} for {{unit.number}} received. Account up to date." }],
    },
  },
  {
    key: "whatsapp.arrears_reminder_l1",
    channel: "whatsapp",
    commsClass: "service",
    name: "Arrears Reminder Level 1 (WhatsApp)",
    description: "First-level WhatsApp arrears reminder (no statutory threat). ⚠ friendly body >145 chars — SMS-fallback truncation risk (70D Part D / R4).",
    category: "arrears_and_lod",
    mergeFields: ["{{tenant.primary_contact_name}}", "{{unit.number}}", "{{arrears.total}}"],
    legalReviewRef: "ADDENDUM_70D §A.3",
    variants: {
      friendly: [{ type: "paragraph", text: "Hi {{tenant.primary_contact_name}}, just a gentle reminder that your rental for {{unit.number}} has an outstanding balance of {{arrears.total}}. Please pay when you can, or contact us if you need help." }],
      professional: [{ type: "paragraph", text: "Dear {{tenant.primary_contact_name}}, your rental account for {{unit.number}} has an outstanding balance of {{arrears.total}}. Please make payment as soon as possible." }],
      firm: [{ type: "paragraph", text: "{{tenant.primary_contact_name}}, arrears of {{arrears.total}} are outstanding for {{unit.number}}. Immediate payment is required." }],
    },
  },
  {
    key: "whatsapp.arrears_reminder_l2",
    channel: "whatsapp",
    commsClass: "service",
    name: "Arrears Reminder Level 2 (WhatsApp)",
    description: "Second-level WhatsApp arrears reminder. ⚠ >145-char bodies (SMS-fallback truncation); 🟡 firm sets a hard 48h deadline (70D §A.4).",
    category: "arrears_and_lod",
    mergeFields: ["{{tenant.primary_contact_name}}", "{{unit.number}}", "{{arrears.total}}"],
    legalReviewRef: "ADDENDUM_70D §A.4",
    variants: {
      friendly: [{ type: "paragraph", text: "Hi {{tenant.primary_contact_name}}, this is a follow-up on your rental arrears of {{arrears.total}} for {{unit.number}}. Please pay urgently or reach out to us to work something out." }],
      professional: [{ type: "paragraph", text: "Dear {{tenant.primary_contact_name}}, your rental arrears for {{unit.number}} of {{arrears.total}} remain unpaid. Please make payment urgently or contact us to arrange a payment plan." }],
      firm: [{ type: "paragraph", text: "{{tenant.primary_contact_name}}, second notice: arrears of {{arrears.total}} for {{unit.number}} are overdue. Payment or a payment arrangement is required within 48 hours." }],
    },
  },
  {
    key: "whatsapp.arrears_final_notice",
    channel: "whatsapp",
    commsClass: "service",
    name: "Arrears Final Notice (WhatsApp)",
    description: "Final WhatsApp arrears notice. 🔴 firm threatens 'Legal proceedings commence in 5 business days' (70D §A.5 — most-important flag; recommend aligning to the professional 'formal demand letter' framing).",
    category: "arrears_and_lod",
    mergeFields: ["{{tenant.primary_contact_name}}", "{{unit.number}}", "{{arrears.total}}"],
    legalReviewRef: "ADDENDUM_70D §A.5",
    variants: {
      friendly: [{ type: "paragraph", text: "Hi {{tenant.primary_contact_name}}, this is an urgent message — arrears of {{arrears.total}} for {{unit.number}} need your immediate attention. Please contact us today before formal action is taken." }],
      professional: [{ type: "paragraph", text: "Dear {{tenant.primary_contact_name}}, this is your final notice regarding arrears of {{arrears.total}} for {{unit.number}}. A formal demand letter will follow if payment is not received within 5 business days." }],
      firm: [{ type: "paragraph", text: "{{tenant.primary_contact_name}}, FINAL NOTICE: arrears of {{arrears.total}} for {{unit.number}}. Legal proceedings commence in 5 business days if payment is not received." }],
    },
  },
  {
    key: "whatsapp.inspection_scheduled",
    channel: "whatsapp",
    commsClass: "service",
    name: "Inspection Scheduled (WhatsApp)",
    description: "WhatsApp notice that a property inspection has been scheduled.",
    category: "inspections",
    mergeFields: ["{{tenant.primary_contact_name}}", "{{unit.number}}"],
    legalReviewRef: "ADDENDUM_70D §A.6",
    variants: {
      friendly: [{ type: "paragraph", text: "Hi {{tenant.primary_contact_name}}, heads up — we have a property inspection coming up for {{unit.number}}. Please make sure access is available. Let us know if you need to reschedule!" }],
      professional: [{ type: "paragraph", text: "Dear {{tenant.primary_contact_name}}, a property inspection is scheduled for {{unit.number}}. Please ensure the property is accessible at the agreed time. Contact us if you need to reschedule." }],
      firm: [{ type: "paragraph", text: "{{tenant.primary_contact_name}}, inspection notice: {{unit.number}}. You are required to provide access at the scheduled time per your lease agreement." }],
    },
  },
  {
    key: "whatsapp.inspection_reminder",
    channel: "whatsapp",
    commsClass: "service",
    name: "Inspection Reminder (WhatsApp)",
    description: "WhatsApp reminder that an inspection is scheduled for tomorrow.",
    category: "inspections",
    mergeFields: ["{{tenant.primary_contact_name}}", "{{unit.number}}"],
    legalReviewRef: "ADDENDUM_70D §A.7",
    variants: {
      friendly: [{ type: "paragraph", text: "Hi {{tenant.primary_contact_name}}, just a reminder — your property inspection at {{unit.number}} is tomorrow! Please make sure access is available. See you then 👋" }],
      professional: [{ type: "paragraph", text: "Dear {{tenant.primary_contact_name}}, reminder: property inspection at {{unit.number}} is scheduled for tomorrow. Please ensure access is available." }],
      firm: [{ type: "paragraph", text: "{{tenant.primary_contact_name}}, reminder: inspection at {{unit.number}} is tomorrow. Access must be provided." }],
    },
  },
  {
    key: "whatsapp.maintenance_ack",
    channel: "whatsapp",
    commsClass: "service",
    name: "Maintenance Request Acknowledged (WhatsApp)",
    description: "WhatsApp acknowledgement that a maintenance request was received.",
    category: "maintenance",
    mergeFields: ["{{tenant.primary_contact_name}}", "{{unit.number}}"],
    legalReviewRef: "ADDENDUM_70D §A.8",
    variants: {
      friendly: [{ type: "paragraph", text: "Hi {{tenant.primary_contact_name}}, got your maintenance request for {{unit.number}} — we're on it and will be in touch soon! 🔧" }],
      professional: [{ type: "paragraph", text: "Dear {{tenant.primary_contact_name}}, we have received your maintenance request for {{unit.number}} and will be in touch shortly regarding the next steps." }],
      firm: [{ type: "paragraph", text: "{{tenant.primary_contact_name}}, maintenance request for {{unit.number}} received. You will be contacted shortly." }],
    },
  },
  {
    key: "whatsapp.lease_renewal_reminder",
    channel: "whatsapp",
    commsClass: "service",
    name: "Lease Renewal Reminder (WhatsApp)",
    description: "Informal WhatsApp renewal nudge — distinct from the formal CPA s14 notice; does not satisfy the s14 timing obligation.",
    category: "notices",
    mergeFields: ["{{tenant.primary_contact_name}}", "{{unit.number}}", "{{lease.end_date}}"],
    legalReviewRef: "ADDENDUM_70D §A.9",
    variants: {
      friendly: [{ type: "paragraph", text: "Hi {{tenant.primary_contact_name}}, your lease at {{unit.number}} expires on {{lease.end_date}}. We'd love to have you stay — please reach out if you want to renew!" }],
      professional: [{ type: "paragraph", text: "Dear {{tenant.primary_contact_name}}, your lease for {{unit.number}} expires on {{lease.end_date}}. Please contact us if you would like to discuss renewal terms." }],
      firm: [{ type: "paragraph", text: "{{tenant.primary_contact_name}}, lease expiry notice: {{unit.number}} lease expires {{lease.end_date}}. Contact us immediately if you intend to renew." }],
    },
  },
  {
    key: "whatsapp.cpa_s14_companion",
    channel: "whatsapp",
    commsClass: "service",
    name: "CPA s14 Notice Companion (WhatsApp)",
    description: "WhatsApp companion pointing to the formal emailed CPA s14 notice — must only ever fire alongside the actual s14 email, never standalone (70D §A.10).",
    category: "compliance",
    mergeFields: ["{{tenant.primary_contact_name}}", "{{unit.number}}", "{{lease.end_date}}"],
    legalReviewRef: "ADDENDUM_70D §A.10",
    variants: {
      friendly: [{ type: "paragraph", text: "Hi {{tenant.primary_contact_name}}, we've sent you a formal CPA s14 notice about your lease at {{unit.number}} expiring on {{lease.end_date}}. Please check your email and let us know if you have questions!" }],
      professional: [{ type: "paragraph", text: "Dear {{tenant.primary_contact_name}}, your lease at {{unit.number}} expires on {{lease.end_date}}. A formal CPA s14 notice has been emailed to you. Please review it at your earliest convenience." }],
      firm: [{ type: "paragraph", text: "{{tenant.primary_contact_name}}, CPA s14 notice for {{unit.number}} (expiry: {{lease.end_date}}) has been sent by email. Please review immediately and respond within the required period." }],
    },
  },
  {
    key: "whatsapp.welcome",
    channel: "whatsapp",
    commsClass: "service",
    name: "Welcome Message (WhatsApp)",
    description: "WhatsApp welcome message on lease activation.",
    category: "welcome_and_onboarding",
    mergeFields: ["{{tenant.primary_contact_name}}", "{{unit.number}}", "{{property.name}}", "{{lease.start_date}}", "{{lease.rent_amount}}", "{{agent.name}}"],
    legalReviewRef: "ADDENDUM_70D §A.11",
    variants: {
      friendly: [{ type: "paragraph", text: "Hi {{tenant.primary_contact_name}}, welcome to {{unit.number}}, {{property.name}}! 🏠 We're so glad to have you. Your lease starts {{lease.start_date}} — reach out anytime if you need anything!" }],
      professional: [{ type: "paragraph", text: "Dear {{tenant.primary_contact_name}}, welcome to {{unit.number}}, {{property.name}}. Your lease commences on {{lease.start_date}}. Please don't hesitate to contact us with any queries." }],
      firm: [{ type: "paragraph", text: "{{tenant.primary_contact_name}}, lease activated: {{unit.number}}, {{property.name}}. Commencement: {{lease.start_date}}. Rental: {{lease.rent_amount}}/month. Contact {{agent.name}} for administration." }],
    },
  },

  // ── SMS — ADDENDUM_70D §C ────────────────────────────────────────────────────────────────────
  {
    key: "sms.arrears_step1",
    channel: "sms",
    commsClass: "service",
    name: "Arrears SMS — Step 1",
    description: "First arrears reminder SMS (flavoured) sent by the arrears-sequence cron.",
    category: "arrears_and_lod",
    mergeFields: ["{{name}}", "{{amountDisplay}}", "{{sender}}"],
    legalReviewRef: "ADDENDUM_70D §C.1",
    variants: {
      friendly: [{ type: "paragraph", text: "Hi {{name}}, just a reminder - your rent ({{amountDisplay}}) is overdue. Please pay or contact us soon. - {{sender}}" }],
      professional: [{ type: "paragraph", text: "Hi {{name}}, your rent account has an overdue balance of {{amountDisplay}}. Please arrange payment urgently. - {{sender}}" }],
      firm: [{ type: "paragraph", text: "{{name}}: Rent of {{amountDisplay}} is overdue. Pay immediately or contact us to avoid escalation. - {{sender}}" }],
    },
  },
  {
    key: "sms.arrears_step2",
    channel: "sms",
    commsClass: "service",
    name: "Arrears SMS — Step 2",
    description: "Second arrears reminder SMS (flavoured). 🔴 professional ('avoid a letter of demand') + firm ('Formal proceedings will follow') threaten statutory steps (70D §C.1) — confirm consistency with the signed LOD/final-notice flow.",
    category: "arrears_and_lod",
    mergeFields: ["{{name}}", "{{amountDisplay}}", "{{sender}}"],
    legalReviewRef: "ADDENDUM_70D §C.1",
    variants: {
      friendly: [{ type: "paragraph", text: "Hi {{name}}, your rent ({{amountDisplay}}) is still outstanding. Please pay urgently before formal action is taken. - {{sender}}" }],
      professional: [{ type: "paragraph", text: "REMINDER {{name}}: Rent arrears of {{amountDisplay}} unpaid. Act immediately to avoid a letter of demand. - {{sender}}" }],
      firm: [{ type: "paragraph", text: "{{name}}: {{amountDisplay}} in rent arrears remains unpaid. Formal proceedings will follow without immediate payment. - {{sender}}" }],
    },
  },
  {
    key: "sms.inspection_reminder",
    channel: "sms",
    commsClass: "service",
    name: "Inspection Reminder SMS",
    description: "SMS reminder that an inspection is scheduled for tomorrow.",
    category: "inspections",
    mergeFields: ["{{senderName}}", "{{inspectionTypeLabel}}", "{{propertyLabel}}", "{{scheduledDate}}"],
    legalReviewRef: "ADDENDUM_70D §C.2",
    body: [{ type: "paragraph", text: "{{senderName}}: Reminder - your {{inspectionTypeLabel}} at {{propertyLabel}} is scheduled for tomorrow, {{scheduledDate}}. Please ensure the property is accessible." }],
  },
  {
    key: "sms.pre_moveout",
    channel: "sms",
    commsClass: "service",
    name: "Pre-Move-Out SMS",
    description: "SMS prompting the tenant to schedule a pre-move-out inspection.",
    category: "deposits",
    mergeFields: ["{{tenantFirstName}}", "{{propertyLabel}}", "{{leaseEndDate}}", "{{senderName}}"],
    legalReviewRef: "ADDENDUM_70D §C.3",
    body: [{ type: "paragraph", text: "Hi {{tenantFirstName}}, your lease at {{propertyLabel}} ends {{leaseEndDate}}. Contact us to schedule a pre-moveout inspection. - {{senderName}}" }],
  },
  {
    key: "sms.mandatory_retry",
    channel: "sms",
    commsClass: "service",
    name: "Mandatory Notice Retry SMS",
    description: "Fallback SMS when a mandatory/statutory notice failed primary delivery — points to the notice, does not restate it.",
    category: "notices",
    mergeFields: ["{{noticeUrl}}"],
    legalReviewRef: "ADDENDUM_70D §C.4",
    body: [{ type: "paragraph", text: "Pleks: We tried to deliver an important notice to you. View it here: {{noticeUrl}}" }],
  },
  {
    key: "sms.maintenance_emergency",
    channel: "sms",
    commsClass: "service",
    name: "Critical Maintenance Incident SMS",
    description: "URGENT operational-emergency SMS for a critical maintenance issue.",
    category: "maintenance",
    mergeFields: ["{{propertyLabel}}", "{{title}}", "{{contactPhone}}"],
    legalReviewRef: "ADDENDUM_70D §C.5",
    body: [{ type: "paragraph", text: "URGENT: Critical maintenance issue at {{propertyLabel}}: {{title}}. Contact {{contactPhone}} immediately." }],
  },
  {
    key: "sms.bulk_rent_reminder",
    channel: "sms",
    commsClass: "service",
    name: "Bulk Rent Reminder SMS",
    description: "Friendly bulk rent-outstanding reminder SMS. ⚪ signs off '- Pleks' not the agency org name (70D §C.6 branding flag).",
    category: "statements",
    mergeFields: ["{{firstName}}"],
    legalReviewRef: "ADDENDUM_70D §C.6",
    body: [{ type: "paragraph", text: "Hi {{firstName}}, this is a friendly reminder that your rent payment is outstanding. Please make payment or contact your agent. - Pleks" }],
  },

  // ── Consent OTP (bypasses tier gate — ADDENDUM_14F) — ADDENDUM_70D §C.7 ───────────────────────
  {
    key: "consent.verification_standard",
    channel: "sms",
    commsClass: "service",
    name: "Screening Consent Code SMS",
    description: "POPIA screening-consent verification OTP (ADDENDUM_14F) — bypasses the Steward+ tier gate.",
    category: "consent",
    mergeFields: ["{{code}}"],
    legalReviewRef: "ADDENDUM_70D §C.7",
    body: [{ type: "paragraph", text: "Pleks: Your screening consent code is {{code}}. Valid 5 min. Do not share. If you did not request this, ignore." }],
  },
  {
    key: "consent.verification_special_info",
    channel: "sms",
    commsClass: "service",
    name: "Special-Information Consent Code SMS",
    description: "POPIA special-information-consent verification OTP (ADDENDUM_14F) — bypasses the Steward+ tier gate.",
    category: "consent",
    mergeFields: ["{{code}}"],
    legalReviewRef: "ADDENDUM_70D §C.7",
    body: [{ type: "paragraph", text: "Pleks: Your special-information consent code is {{code}}. Valid 5 min. Do not share. If you did not request this, ignore." }],
  },
]
