/**
 * lib/comms/templates/seed/correspondence.ts — correspondence templates folded into typed seeds (ADDENDUM_70E E3)
 *
 * Data:   agency-editable signed comms (lease lifecycle, deposits, inspections, portal, insurance,
 *         maintenance, critical-incident) as TemplateBlock[], standardized per 70F.
 * Notes:  Rules applied: salutation via {{recipient.salutation}} (R4); POPIA via {type:"popiaSlot"}
 *         (kept on correspondence, 70F §3‡); signatureSlot on signed comms; NO Tribunal (§16 #4);
 *         absolute-dated deadlines (R2); NO legalFooterSlot (statutory-only). Folded from ADDENDUM_70C.
 *         Reviewable pre-store source — NOT seeded.
 */

import type { TemplateSeed } from "./types"

const RECIPIENT = ["{{recipient.salutation}}", "{{recipient.legal_name}}", "{{recipient.address}}"]
const ORG = ["{{branding.orgName}}", "{{branding.orgPhone}}", "{{branding.orgEmail}}"]

export const CORRESPONDENCE_SEEDS: TemplateSeed[] = [
  // ── Lease lifecycle ─────────────────────────────────────────────────────────────────────────
  {
    key: "lease.created",
    channel: "email",
    commsClass: "correspondence",
    name: "Lease Created (Ready to Sign)",
    description: "Notifies the tenant that their lease is prepared and ready for signature.",
    category: "leases",
    mergeFields: ["{{recipient.salutation}}", "{{propertyLabel}}", "{{leaseStartDate}}", "{{rentDisplay}}", "{{signingUrl}}", "{{senderName}}", "{{branding.orgName}}", "{{branding.orgEmail}}"],
    legalReviewRef: "ADDENDUM_70C §2.1",
    body: [
      { type: "salutation", text: "{{recipient.salutation}}" },
      { type: "heading", text: "Your lease is ready to sign" },
      { type: "paragraph", text: "Your lease agreement for **{{propertyLabel}}** has been prepared and is ready for your signature. Please review and sign at your earliest convenience." },
      { type: "dataBox", rows: [
        { label: "Property", value: "{{propertyLabel}}" },
        { label: "Commencement", value: "{{leaseStartDate}}" },
        { label: "Monthly rent", value: "{{rentDisplay}}" },
      ] },
      { type: "cta", label: "Review & Sign Lease", href: "{{signingUrl}}" },
      { type: "paragraph", text: "If you have any questions, please contact {{branding.orgEmail}} or {{senderName}} to arrange signing of your lease agreement." },
      { type: "signoff", text: "Kind regards,\n{{senderName}}" },
      { type: "popiaSlot" },
    ],
  },
  {
    key: "lease.sign_reminder",
    channel: "email",
    commsClass: "correspondence",
    name: "Lease Sign Reminder",
    description: "Reminds the tenant that their lease is still awaiting signature.",
    category: "leases",
    mergeFields: ["{{recipient.salutation}}", "{{propertyLabel}}", "{{daysUnsigned}}", "{{signingUrl}}", "{{senderName}}", "{{branding.orgName}}", "{{branding.orgEmail}}"],
    legalReviewRef: "ADDENDUM_70C §2.2",
    body: [
      { type: "salutation", text: "{{recipient.salutation}}" },
      { type: "heading", text: "Friendly reminder — lease awaiting signature" },
      { type: "paragraph", text: "Your lease agreement for **{{propertyLabel}}** was sent {{daysUnsigned}} day(s) ago and is still waiting for your signature. Please sign at your earliest convenience so we can get everything in order before your move-in date." },
      { type: "cta", label: "Sign Lease Now", href: "{{signingUrl}}" },
      { type: "paragraph", text: "If you have any questions or need assistance signing your lease, please contact {{branding.orgEmail}} or {{senderName}}." },
      { type: "signoff", text: "Kind regards,\n{{senderName}}" },
      { type: "popiaSlot" },
    ],
  },
  {
    key: "lease.signed",
    channel: "email",
    commsClass: "correspondence",
    name: "Lease Signed",
    description: "Confirms to the tenant that the lease has been signed by all parties.",
    category: "leases",
    mergeFields: ["{{recipient.salutation}}", "{{propertyLabel}}", "{{senderName}}", "{{branding.orgName}}", "{{branding.orgEmail}}"],
    legalReviewRef: "ADDENDUM_70C §2.3",
    body: [
      { type: "salutation", text: "{{recipient.salutation}}" },
      { type: "heading", text: "Lease signed — all good" },
      { type: "paragraph", text: "Great news — your lease agreement for **{{propertyLabel}}** has been signed by all parties. We will be in touch shortly with your activation confirmation and move-in details." },
      { type: "paragraph", text: "Please keep a copy of your signed lease for your records. If you have any questions in the meantime, contact {{branding.orgEmail}} or {{senderName}}." },
      { type: "signoff", text: "Kind regards,\n{{senderName}}" },
      { type: "signatureSlot" },
      { type: "popiaSlot" },
    ],
  },
  {
    key: "lease.activated",
    channel: "email",
    commsClass: "correspondence",
    name: "Lease Activated",
    description: "Welcomes the tenant and confirms the lease is now active.",
    category: "leases",
    mergeFields: ["{{recipient.salutation}}", "{{propertyLabel}}", "{{leaseStartDate}}", "{{leaseEndDate}}", "{{rentDisplay}}", "{{portalUrl}}", "{{senderName}}", "{{branding.orgName}}"],
    legalReviewRef: "ADDENDUM_70C §2.4",
    body: [
      { type: "salutation", text: "{{recipient.salutation}}" },
      { type: "heading", text: "Your lease is now active" },
      { type: "paragraph", text: "Welcome to **{{propertyLabel}}**! Your lease agreement has been signed and is now active. We are pleased to have you as a tenant and look forward to a great tenancy." },
      { type: "dataBox", rows: [
        { label: "Property", value: "{{propertyLabel}}" },
        { label: "Commencement", value: "{{leaseStartDate}}" },
        { label: "End date", value: "{{leaseEndDate}}" },
        { label: "Monthly rent", value: "{{rentDisplay}}" },
      ] },
      { type: "paragraph", text: "You can access your tenant portal to view your lease, invoices, and maintenance requests at any time." },
      { type: "cta", label: "Access Tenant Portal", href: "{{portalUrl}}" },
      { type: "signoff", text: "Kind regards,\n{{senderName}}" },
      { type: "signatureSlot" },
      { type: "popiaSlot" },
    ],
  },
  {
    key: "lease.amended",
    channel: "email",
    commsClass: "correspondence",
    name: "Lease Amended (Charge Change)",
    description: "Notifies the tenant of a charge added to or removed from their lease.",
    category: "leases",
    mergeFields: ["{{recipient.salutation}}", "{{propertyLabel}}", "{{chargeDescription}}", "{{chargeAmountDisplay}}", "{{effectiveDate}}", "{{senderName}}", "{{branding.orgName}}", "{{branding.orgEmail}}"],
    legalReviewRef: "ADDENDUM_70C §2.5",
    body: [
      { type: "salutation", text: "{{recipient.salutation}}" },
      { type: "heading", text: "Lease update — charge change" },
      { type: "paragraph", text: "A change has been made to your lease for **{{propertyLabel}}**. Please review the details below." },
      { type: "dataBox", rows: [
        { label: "Charge", value: "{{chargeDescription}}" },
        { label: "Amount", value: "{{chargeAmountDisplay}} per month" },
        { label: "Effective from", value: "{{effectiveDate}}" },
      ] },
      { type: "paragraph", text: "This change will be reflected on your monthly invoice from the effective date above. If you have any questions, please contact {{branding.orgEmail}} or {{senderName}}." },
      { type: "signoff", text: "Kind regards,\n{{senderName}}" },
      { type: "popiaSlot" },
    ],
  },
  {
    key: "lease.escalation_notice",
    channel: "email",
    commsClass: "correspondence",
    name: "Lease Escalation Notice",
    description: "Advance notice of an upcoming contractual rent escalation.",
    category: "leases",
    mergeFields: ["{{recipient.salutation}}", "{{propertyLabel}}", "{{currentRentDisplay}}", "{{newRentDisplay}}", "{{escalationPercent}}", "{{effectiveDate}}", "{{senderName}}", "{{branding.orgName}}", "{{branding.orgEmail}}"],
    legalReviewRef: "ADDENDUM_70C §2.6",
    body: [
      { type: "salutation", text: "{{recipient.salutation}}" },
      { type: "heading", text: "Upcoming rent escalation" },
      { type: "paragraph", text: "This letter serves as advance notice that the monthly rental for **{{propertyLabel}}** will be adjusted in accordance with your lease agreement." },
      { type: "dataBox", rows: [
        { label: "Current monthly rent", value: "{{currentRentDisplay}}" },
        { label: "New monthly rent", value: "{{newRentDisplay}}" },
        { label: "Increase", value: "{{escalationPercent}}%" },
        { label: "Effective from", value: "{{effectiveDate}}" },
      ] },
      { type: "paragraph", text: "Your invoice from {{effectiveDate}} onwards will reflect the new rental amount. If you have any questions regarding this adjustment, please do not hesitate to contact {{branding.orgEmail}} or {{senderName}}." },
      { type: "signoff", text: "Kind regards,\n{{senderName}}" },
      { type: "popiaSlot" },
    ],
  },
  {
    key: "lease.notice_acknowledged",
    channel: "email",
    commsClass: "correspondence",
    name: "Notice to Vacate — Acknowledged",
    description: "Formal acknowledgement of a tenant-initiated notice to vacate.",
    category: "leases",
    mergeFields: ["{{recipient.salutation}}", "{{propertyLabel}}", "{{noticeDate}}", "{{vacateDate}}", "{{senderName}}", "{{branding.orgName}}", "{{branding.orgEmail}}"],
    legalReviewRef: "ADDENDUM_70C §2.8",
    body: [
      { type: "salutation", text: "{{recipient.salutation}}" },
      { type: "heading", text: "Notice to vacate received" },
      { type: "paragraph", text: "We confirm receipt of your notice to vacate **{{propertyLabel}}**. This letter serves as formal acknowledgement of your notice." },
      { type: "dataBox", rows: [
        { label: "Property", value: "{{propertyLabel}}" },
        { label: "Notice date", value: "{{noticeDate}}" },
        { label: "Vacate date", value: "{{vacateDate}}" },
      ] },
      { type: "paragraph", text: "Please ensure the property is vacated and all keys returned by {{vacateDate}}. We will be in contact to arrange the final move-out inspection and deposit reconciliation." },
      { type: "paragraph", text: "If you have any questions, please contact {{branding.orgEmail}} or {{senderName}}." },
      { type: "signoff", text: "Kind regards,\n{{senderName}}" },
      { type: "popiaSlot" },
    ],
  },

  // ── Deposits (non-statutory) ─────────────────────────────────────────────────────────────────
  {
    key: "deposit.received",
    channel: "email",
    commsClass: "correspondence",
    name: "Deposit Received",
    description: "Confirmation that the security deposit has been received into trust.",
    category: "deposits",
    mergeFields: [...RECIPIENT, "{{propertyLabel}}", "{{depositAmountDisplay}}", "{{leaseStartDate}}", "{{senderName}}", ...ORG],
    legalReviewRef: "ADDENDUM_70C §3.1",
    body: [
      { type: "salutation", text: "{{recipient.salutation}}" },
      { type: "heading", text: "Deposit received — thank you" },
      { type: "paragraph", text: "We confirm that your security deposit of **{{depositAmountDisplay}}** has been received and is held in our trust account in accordance with the Rental Housing Act." },
      { type: "dataBox", rows: [
        { label: "Property", value: "{{propertyLabel}}" },
        { label: "Deposit amount", value: "{{depositAmountDisplay}}" },
        { label: "Lease commencement", value: "{{leaseStartDate}}" },
        { label: "Held by", value: "{{senderName}} (trust account)" },
      ] },
      { type: "paragraph", text: "Your deposit earns interest at the prescribed rate for the duration of your tenancy. An annual interest statement will be issued to you each year, and a full interest accounting will be provided when your deposit is returned at the end of the lease." },
      { type: "paragraph", text: "Please retain this confirmation for your records. If you have any questions, contact us at {{branding.orgEmail}}." },
      { type: "paragraph", text: "This deposit is protected under the Rental Housing Act 50 of 1999. Any deductions at move-out will be itemised and communicated to you in writing before disbursement." },
      { type: "signoff", text: "Kind regards,\n{{senderName}}" },
      { type: "signatureSlot" },
      { type: "popiaSlot" },
    ],
  },
  {
    key: "deposit.pre_moveout_inspection",
    channel: "email",
    commsClass: "correspondence",
    name: "Pre-Move-Out Inspection Reminder",
    description: "Invitation to schedule a pre-move-out inspection ahead of lease end.",
    category: "deposits",
    mergeFields: [...RECIPIENT, "{{propertyLabel}}", "{{leaseEndDate}}", "{{senderName}}", ...ORG],
    legalReviewRef: "ADDENDUM_70C §3.2",
    body: [
      { type: "salutation", text: "{{recipient.salutation}}" },
      { type: "heading", text: "Your lease is ending soon" },
      { type: "paragraph", text: "Your lease for **{{propertyLabel}}** ends on **{{leaseEndDate}}**." },
      { type: "paragraph", text: "We would like to schedule a pre-move-out inspection at a time that suits you. This inspection gives you the opportunity to identify and address any items before the final move-out inspection, which helps ensure the best possible outcome for your deposit return." },
      { type: "heading", text: "What to expect" },
      { type: "list", items: [
        "A walk-through with our agent before your move-out date",
        "Any fixable items identified so you can address them",
        "No deductions applied for items you repair before move-out",
        "Your deposit return processed within the statutory period",
      ] },
      { type: "paragraph", text: "Please reply to this email or contact {{branding.orgEmail}} to confirm a convenient time. We recommend scheduling the pre-move-out inspection well ahead of your final move-out date." },
      { type: "paragraph", text: "The final move-out inspection will take place on or after **{{leaseEndDate}}**. Your deposit return schedule will be issued to you within the timeframe required by the Rental Housing Act after the final inspection is complete." },
      { type: "signoff", text: "Kind regards,\n{{senderName}}" },
      { type: "signatureSlot" },
      { type: "popiaSlot" },
    ],
  },

  // ── Inspections (non-statutory) ──────────────────────────────────────────────────────────────
  {
    key: "inspection.scheduled",
    channel: "email",
    commsClass: "correspondence",
    name: "Inspection Scheduled",
    description: "Notification that an inspection has been scheduled at the property.",
    category: "inspections",
    mergeFields: [...RECIPIENT, "{{propertyLabel}}", "{{inspectionTypeLabel}}", "{{scheduledDate}}", "{{senderName}}", ...ORG],
    legalReviewRef: "ADDENDUM_70C §4.1",
    body: [
      { type: "salutation", text: "{{recipient.salutation}}" },
      { type: "heading", text: "{{inspectionTypeLabel}} scheduled" },
      { type: "paragraph", text: "We wish to advise you that a {{inspectionTypeLabel}} has been scheduled at your property. Please find the details below." },
      { type: "dataBox", rows: [
        { label: "Property", value: "{{propertyLabel}}" },
        { label: "Type", value: "{{inspectionTypeLabel}}" },
        { label: "Scheduled for", value: "{{scheduledDate}}" },
      ] },
      { type: "paragraph", text: "Please ensure the property is accessible on the scheduled date. If this date is inconvenient, please contact us as soon as possible so we can make alternative arrangements." },
      { type: "paragraph", text: "Should you have any questions, please reply to this email or contact your property manager directly." },
      { type: "signoff", text: "Kind regards,\n{{senderName}}" },
      { type: "signatureSlot" },
      { type: "popiaSlot" },
    ],
  },
  {
    key: "inspection.reminder",
    channel: "email",
    commsClass: "correspondence",
    name: "Inspection Reminder",
    description: "Day-before reminder of a scheduled inspection.",
    category: "inspections",
    mergeFields: [...RECIPIENT, "{{propertyLabel}}", "{{inspectionTypeLabel}}", "{{scheduledDate}}", "{{senderName}}", ...ORG],
    legalReviewRef: "ADDENDUM_70C §4.2",
    body: [
      { type: "salutation", text: "{{recipient.salutation}}" },
      { type: "heading", text: "Inspection reminder — tomorrow" },
      { type: "paragraph", text: "This is a friendly reminder that your {{inspectionTypeLabel}} at **{{propertyLabel}}** is scheduled for tomorrow, **{{scheduledDate}}**." },
      { type: "dataBox", rows: [
        { label: "Property", value: "{{propertyLabel}}" },
        { label: "Type", value: "{{inspectionTypeLabel}}" },
        { label: "Date", value: "{{scheduledDate}}" },
      ] },
      { type: "paragraph", text: "Please ensure the property is accessible at the time of the inspection. If you have any concerns or need to reschedule, please contact us immediately." },
      { type: "signoff", text: "Kind regards,\n{{senderName}}" },
      { type: "signatureSlot" },
      { type: "popiaSlot" },
    ],
  },
  {
    key: "inspection.rescheduled",
    channel: "email",
    commsClass: "correspondence",
    name: "Inspection Rescheduled",
    description: "Notification that a scheduled inspection has been moved to a new date.",
    category: "inspections",
    mergeFields: [...RECIPIENT, "{{propertyLabel}}", "{{inspectionTypeLabel}}", "{{originalDate}}", "{{newDate}}", "{{rescheduleReason}}", "{{senderName}}", ...ORG],
    legalReviewRef: "ADDENDUM_70C §4.3",
    body: [
      { type: "salutation", text: "{{recipient.salutation}}" },
      { type: "heading", text: "{{inspectionTypeLabel}} rescheduled" },
      { type: "paragraph", text: "We wish to advise you that your {{inspectionTypeLabel}} at **{{propertyLabel}}** has been rescheduled. Please note the updated date below." },
      { type: "dataBox", rows: [
        { label: "Property", value: "{{propertyLabel}}" },
        { label: "Type", value: "{{inspectionTypeLabel}}" },
        { label: "Previous date", value: "{{originalDate}}" },
        { label: "New date", value: "{{newDate}}" },
        { label: "Reason", value: "{{rescheduleReason}}" },
      ] },
      { type: "paragraph", text: "Please ensure the property is accessible on the new scheduled date. If this date is inconvenient, please contact us as soon as possible." },
      { type: "signoff", text: "Kind regards,\n{{senderName}}" },
      { type: "signatureSlot" },
      { type: "popiaSlot" },
    ],
  },
  {
    key: "inspection.report_ready",
    channel: "email",
    commsClass: "correspondence",
    name: "Inspection Report Available",
    description: "Notification that a completed inspection report is available in the portal.",
    category: "inspections",
    mergeFields: [...RECIPIENT, "{{propertyLabel}}", "{{inspectionTypeLabel}}", "{{conductedDate}}", "{{overallCondition}}", "{{portalUrl}}", "{{senderName}}", ...ORG],
    legalReviewRef: "ADDENDUM_70C §4.5",
    body: [
      { type: "salutation", text: "{{recipient.salutation}}" },
      { type: "heading", text: "{{inspectionTypeLabel}} report available" },
      { type: "paragraph", text: "The {{inspectionTypeLabel}} conducted at **{{propertyLabel}}** on {{conductedDate}} has been completed. Your inspection report is now available." },
      { type: "dataBox", rows: [
        { label: "Property", value: "{{propertyLabel}}" },
        { label: "Type", value: "{{inspectionTypeLabel}}" },
        { label: "Conducted on", value: "{{conductedDate}}" },
        { label: "Overall condition", value: "{{overallCondition}}" },
      ] },
      { type: "paragraph", text: "Please log in to your tenant portal to view the full inspection report. If you have any questions or concerns about the findings, please contact your property manager." },
      { type: "cta", label: "View inspection report", href: "{{portalUrl}}" },
      { type: "signoff", text: "Kind regards,\n{{senderName}}" },
      { type: "signatureSlot" },
      { type: "popiaSlot" },
    ],
  },

  // ── Portal ───────────────────────────────────────────────────────────────────────────────────
  {
    key: "portal.tenant_invite",
    channel: "email",
    commsClass: "correspondence",
    name: "Tenant Portal Invitation",
    description: "Invitation to set up the tenant portal account after lease activation.",
    category: "portal",
    mergeFields: [...RECIPIENT, "{{portalUrl}}", "{{senderName}}", ...ORG],
    legalReviewRef: "ADDENDUM_70C §7.1",
    body: [
      { type: "salutation", text: "{{recipient.salutation}}" },
      { type: "heading", text: "Your tenant portal is ready" },
      { type: "paragraph", text: "Your lease is now active. We have set up a secure online portal where you can view your lease documents, track payment history, and log maintenance requests — all in one place." },
      { type: "paragraph", text: "Click the button below to set up your account. The link will expire after a few days." },
      { type: "cta", label: "Set up my account", href: "{{portalUrl}}" },
      { type: "paragraph", text: "If you did not expect this invitation, you can safely ignore this email. If you have any questions, contact {{branding.orgEmail}}." },
      { type: "signoff", text: "Kind regards,\n{{senderName}}" },
      { type: "signatureSlot" },
      { type: "popiaSlot" },
    ],
  },

  // ── Insurance (broker-facing) ────────────────────────────────────────────────────────────────
  {
    key: "insurance.checklist_brief",
    channel: "email",
    commsClass: "correspondence",
    name: "Insurance Coverage Verification Brief",
    description: "Broker-facing request to confirm the items on the insurance verification checklist.",
    category: "insurance",
    mergeFields: [...RECIPIENT, "{{propertyName}}", "{{agentName}}", "{{agentPhone}}", "{{agentEmail}}", ...ORG],
    legalReviewRef: "ADDENDUM_70C §7.2",
    body: [
      { type: "salutation", text: "{{recipient.salutation}}" },
      { type: "paragraph", text: "Please find attached an insurance coverage verification request for **{{propertyName}}**." },
      { type: "paragraph", text: "The attached file lists the items we need confirmed. Please review and reply to this email confirming each item. A copy of the current policy schedule would be appreciated." },
      { type: "paragraph", text: "Thank you for your assistance." },
      { type: "signoff", text: "{{agentName}}\n{{branding.orgName}}\n{{agentPhone}}\n{{agentEmail}}" },
      { type: "signatureSlot" },
      { type: "popiaSlot" },
    ],
  },
  {
    key: "insurance.renewal_reminder",
    channel: "email",
    commsClass: "correspondence",
    name: "Insurance Renewal Reminder",
    description: "Single broker-facing reminder that a policy renewed with checklist items outstanding.",
    category: "insurance",
    mergeFields: [...RECIPIENT, "{{propertyDisplay}}", "{{renewalDateFormatted}}", "{{unknownCount}}", "{{checklistUrl}}", ...ORG],
    legalReviewRef: "ADDENDUM_70C §7.3",
    body: [
      { type: "salutation", text: "{{recipient.salutation}}" },
      { type: "heading", text: "Policy renewed — checklist items outstanding" },
      { type: "paragraph", text: "The insurance policy for **{{propertyDisplay}}** renewed on **{{renewalDateFormatted}}**." },
      { type: "paragraph", text: "{{unknownCount}} verification item(s) is/are still outstanding. Most policies are unchanged renewals of last year's terms — but if anything has shifted (replacement value, security warranties, broker), the checklist is the place to update." },
      { type: "cta", label: "Open the checklist", href: "{{checklistUrl}}" },
      { type: "paragraph", text: "This is a single reminder. The banner on the property page stays until the items are verified or you dismiss it. We won't email you again about this renewal." },
      { type: "popiaSlot" },
    ],
  },

  // ── Maintenance (tenant + contractor/owner) ──────────────────────────────────────────────────
  {
    key: "maintenance.logged_tenant",
    channel: "email",
    commsClass: "correspondence",
    name: "Maintenance Request Received",
    description: "Confirms a tenant's maintenance request has been logged and is under review.",
    category: "maintenance",
    subject: "Maintenance request received — ref {{workOrderNumber}}",
    mergeFields: ["{{recipient.salutation}}", "{{propertyLabel}}", "{{requestTitle}}", "{{workOrderNumber}}", "{{senderName}}"],
    legalReviewRef: "ADDENDUM_70C §5.1",
    body: [
      { type: "salutation", text: "{{recipient.salutation}}" },
      { type: "heading", text: "Maintenance request received" },
      { type: "paragraph", text: "We have received a maintenance request for **{{propertyLabel}}** and it is now under review. Our team will be in touch to arrange the next steps." },
      { type: "dataBox", rows: [
        { label: "Request", value: "{{requestTitle}}" },
        { label: "Reference", value: "{{workOrderNumber}}" },
      ] },
      { type: "paragraph", text: "Please keep this reference number for your records. Quote it in any correspondence about this request." },
      { type: "signoff", text: "Kind regards,\n{{senderName}}" },
      { type: "popiaSlot" },
    ],
  },
  {
    key: "maintenance.assigned",
    channel: "email",
    commsClass: "correspondence",
    name: "Contractor Assigned",
    description: "Notifies the tenant a contractor has been assigned and will arrange access.",
    category: "maintenance",
    subject: "A contractor has been assigned to your maintenance request at {{propertyLabel}}",
    mergeFields: ["{{recipient.salutation}}", "{{propertyLabel}}", "{{requestTitle}}", "{{contractorName}}", "{{senderName}}"],
    legalReviewRef: "ADDENDUM_70C §5.2",
    body: [
      { type: "salutation", text: "{{recipient.salutation}}" },
      { type: "heading", text: "Contractor assigned" },
      { type: "paragraph", text: "We have assigned a contractor to your maintenance request at **{{propertyLabel}}**. They will contact you to arrange access and confirm an appointment time." },
      { type: "dataBox", rows: [
        { label: "Request", value: "{{requestTitle}}" },
        { label: "Contractor", value: "{{contractorName}}" },
      ] },
      { type: "paragraph", text: "If you have not heard from the contractor within 48 hours, please contact {{senderName}}." },
      { type: "signoff", text: "Kind regards,\n{{senderName}}" },
      { type: "popiaSlot" },
    ],
  },
  {
    key: "maintenance.scheduled",
    channel: "email",
    commsClass: "correspondence",
    name: "Maintenance Appointment Confirmed",
    description: "Confirms the scheduled maintenance appointment and access requirements.",
    category: "maintenance",
    subject: "Maintenance appointment confirmed for {{scheduledDate}} at {{propertyLabel}}",
    mergeFields: ["{{recipient.salutation}}", "{{propertyLabel}}", "{{requestTitle}}", "{{scheduledDate}}", "{{scheduledTimeFrom}}", "{{scheduledTimeTo}}", "{{contractorName}}", "{{senderName}}"],
    legalReviewRef: "ADDENDUM_70C §5.3",
    body: [
      { type: "salutation", text: "{{recipient.salutation}}" },
      { type: "heading", text: "Maintenance appointment confirmed" },
      { type: "paragraph", text: "Your maintenance appointment at **{{propertyLabel}}** has been scheduled. Please ensure access to the property at the confirmed time." },
      { type: "dataBox", rows: [
        { label: "Request", value: "{{requestTitle}}" },
        { label: "Date", value: "{{scheduledDate}}" },
        { label: "Time", value: "{{scheduledTimeFrom}} – {{scheduledTimeTo}}" },
        { label: "Contractor", value: "{{contractorName}}" },
      ] },
      { type: "paragraph", text: "If you need to reschedule or cannot provide access, please contact {{senderName}} as soon as possible to avoid a callout fee." },
      { type: "signoff", text: "Kind regards,\n{{senderName}}" },
      { type: "popiaSlot" },
    ],
  },
  {
    key: "maintenance.completed",
    channel: "email",
    commsClass: "correspondence",
    name: "Maintenance Work Completed",
    description: "Notifies the tenant maintenance work has been completed and signed off.",
    category: "maintenance",
    subject: "Maintenance work completed at {{propertyLabel}}",
    mergeFields: ["{{recipient.salutation}}", "{{propertyLabel}}", "{{requestTitle}}", "{{senderName}}"],
    legalReviewRef: "ADDENDUM_70C §5.4",
    body: [
      { type: "salutation", text: "{{recipient.salutation}}" },
      { type: "heading", text: "Maintenance work completed" },
      { type: "paragraph", text: "The maintenance work at **{{propertyLabel}}** has been completed and signed off." },
      { type: "dataBox", rows: [
        { label: "Request", value: "{{requestTitle}}" },
      ] },
      { type: "paragraph", text: "If you have any concerns about the work carried out or notice any follow-up issues, please contact {{senderName}}." },
      { type: "signoff", text: "Kind regards,\n{{senderName}}" },
      { type: "popiaSlot" },
    ],
  },
  {
    key: "maintenance.work_order",
    channel: "email",
    commsClass: "correspondence",
    name: "Work Order Dispatch",
    description: "Contractor-facing work order assignment with job details and acceptance link.",
    category: "maintenance",
    subject: "Work order {{workOrderNumber}} — {{jobTitle}} — {{propertyLabel}}",
    mergeFields: ["{{recipient.salutation}}", "{{contractorName}}", "{{workOrderNumber}}", "{{jobTitle}}", "{{propertyLabel}}", "{{unitLabel}}", "{{urgencyLabel}}", "{{woUrl}}", "{{senderName}}"],
    legalReviewRef: "ADDENDUM_70C §5.7",
    body: [
      { type: "salutation", text: "{{recipient.salutation}}" },
      { type: "heading", text: "Work Order: {{workOrderNumber}}" },
      { type: "paragraph", text: "You have been assigned the following maintenance job. Please review the details and confirm acceptance via the link below." },
      { type: "dataBox", rows: [
        { label: "Work order", value: "{{workOrderNumber}}" },
        { label: "Job", value: "{{jobTitle}}" },
        { label: "Property", value: "{{propertyLabel}}" },
        { label: "Unit", value: "{{unitLabel}}" },
        { label: "Priority", value: "{{urgencyLabel}}" },
      ] },
      { type: "cta", label: "View Work Order", href: "{{woUrl}}" },
      { type: "paragraph", text: "The link above gives you access to the full job details, access instructions, and lets you submit your quote or update the job status as work progresses." },
      { type: "signoff", text: "Kind regards,\n{{senderName}}" },
      { type: "popiaSlot" },
    ],
  },
  {
    key: "maintenance.cancelled",
    channel: "email",
    commsClass: "correspondence",
    name: "Work Order Cancelled",
    description: "Contractor-facing notice that a work order has been cancelled.",
    category: "maintenance",
    subject: "Work order {{workOrderNumber}} has been cancelled",
    mergeFields: ["{{recipient.salutation}}", "{{contractorName}}", "{{workOrderNumber}}", "{{requestTitle}}", "{{propertyLabel}}", "{{senderName}}"],
    legalReviewRef: "ADDENDUM_70C §5.8",
    body: [
      { type: "salutation", text: "{{recipient.salutation}}" },
      { type: "paragraph", text: "Please note that work order **{{workOrderNumber}}** has been cancelled." },
      { type: "dataBox", rows: [
        { label: "Work order", value: "{{workOrderNumber}}" },
        { label: "Job", value: "{{requestTitle}}" },
        { label: "Property", value: "{{propertyLabel}}" },
      ] },
      { type: "paragraph", text: "Your work order portal link for this job is no longer active. No further action is required on your end." },
      { type: "paragraph", text: "If you have already carried out any work or incurred expenses, please contact us directly." },
      { type: "signoff", text: "Thank you,\n{{senderName}}" },
      { type: "popiaSlot" },
    ],
  },
  {
    key: "maintenance.cancelled_tenant",
    channel: "email",
    commsClass: "correspondence",
    name: "Maintenance Request Closed",
    description: "Notifies the tenant their maintenance request has been closed.",
    category: "maintenance",
    subject: "Your maintenance request has been closed",
    mergeFields: ["{{recipient.salutation}}", "{{propertyLabel}}", "{{requestTitle}}", "{{senderName}}"],
    legalReviewRef: "ADDENDUM_70C §5.9",
    body: [
      { type: "salutation", text: "{{recipient.salutation}}" },
      { type: "paragraph", text: "We are writing to let you know that the following maintenance request has been closed." },
      { type: "dataBox", rows: [
        { label: "Property", value: "{{propertyLabel}}" },
        { label: "Request", value: "{{requestTitle}}" },
      ] },
      { type: "paragraph", text: "If you believe this was closed in error or the issue remains unresolved, please contact us and we will assist you further." },
      { type: "signoff", text: "Kind regards,\n{{senderName}}" },
      { type: "popiaSlot" },
    ],
  },
  {
    key: "maintenance.contractor_changed",
    channel: "email",
    commsClass: "correspondence",
    name: "Work Order Reassigned",
    description: "Contractor-facing notice that a work order has been reassigned to another contractor.",
    category: "maintenance",
    subject: "Work order {{workOrderNumber}} has been reassigned",
    mergeFields: ["{{recipient.salutation}}", "{{contractorName}}", "{{workOrderNumber}}", "{{requestTitle}}", "{{propertyLabel}}", "{{senderName}}"],
    legalReviewRef: "ADDENDUM_70C §5.10",
    body: [
      { type: "salutation", text: "{{recipient.salutation}}" },
      { type: "paragraph", text: "Please note that work order **{{workOrderNumber}}** has been reassigned to another contractor." },
      { type: "dataBox", rows: [
        { label: "Work order", value: "{{workOrderNumber}}" },
        { label: "Job", value: "{{requestTitle}}" },
        { label: "Property", value: "{{propertyLabel}}" },
      ] },
      { type: "paragraph", text: "Your work order portal link for this job is no longer active and no further action is required from you." },
      { type: "paragraph", text: "If you have already incurred any costs or carried out preparatory work, please contact us so we can discuss next steps." },
      { type: "signoff", text: "Thank you,\n{{senderName}}" },
      { type: "popiaSlot" },
    ],
  },
  {
    key: "maintenance.memo_landlord_notified",
    channel: "email",
    commsClass: "correspondence",
    name: "Maintenance Memo — Landlord Notified",
    description: "Shares an agent's maintenance memo with the landlord (not visible to the tenant).",
    category: "maintenance",
    subject: "Maintenance update from {{agentName}} — {{workOrderNumber}}",
    mergeFields: ["{{recipient.salutation}}", "{{landlordName}}", "{{agentName}}", "{{workOrderNumber}}", "{{propertyLabel}}", "{{requestTitle}}", "{{memoText}}", "{{senderName}}"],
    legalReviewRef: "ADDENDUM_70C §5.11",
    body: [
      { type: "salutation", text: "{{recipient.salutation}}" },
      { type: "paragraph", text: "{{agentName}} has added a note to the following maintenance request and chosen to share it with you." },
      { type: "dataBox", rows: [
        { label: "Work order", value: "{{workOrderNumber}}" },
        { label: "Property", value: "{{propertyLabel}}" },
        { label: "Request", value: "{{requestTitle}}" },
      ] },
      { type: "heading", text: "Memo from {{agentName}}" },
      { type: "paragraph", text: "{{memoText}}" },
      { type: "paragraph", text: "This note is visible to agents and was shared with you by {{agentName}}. Your tenant cannot see this memo." },
      { type: "signoff", text: "Kind regards,\n{{senderName}}" },
      { type: "popiaSlot" },
    ],
  },

  // ── Critical incidents (paper-trail notices) ─────────────────────────────────────────────────
  {
    key: "incident.critical_broker",
    channel: "email",
    commsClass: "correspondence",
    name: "Critical Incident Notification — Broker",
    description: "Notifies the insurance broker of a critical incident at an insured property.",
    category: "maintenance",
    subject: "Critical incident reported: {{incidentTitle}} — {{propertyName}}",
    mergeFields: ["{{recipient.salutation}}", "{{agencyName}}", "{{propertyName}}", "{{propertyAddress}}", "{{unitLabel}}", "{{incidentTitle}}", "{{incidentDate}}", "{{incidentDescription}}", "{{reportedByName}}", "{{appUrl}}", "{{maintenanceRequestId}}"],
    legalReviewRef: "ADDENDUM_70C §5.12",
    body: [
      { type: "salutation", text: "{{recipient.salutation}}" },
      { type: "heading", text: "Critical incident notification" },
      { type: "paragraph", text: "{{agencyName}} is reporting a critical incident at one of your insured properties that may require your attention." },
      { type: "dataBox", rows: [
        { label: "Property", value: "{{propertyName}} / {{propertyAddress}}" },
        { label: "Unit / area affected", value: "{{unitLabel}}" },
        { label: "Incident", value: "{{incidentTitle}}" },
        { label: "Date reported", value: "{{incidentDate}}" },
        { label: "Description", value: "{{incidentDescription}}" },
      ] },
      { type: "paragraph", text: "This notification was sent on behalf of {{agencyName}} by {{reportedByName}}. The agency has logged the incident and is managing the repair process. Please contact them directly if you require additional information or wish to open a claim." },
      { type: "paragraph", text: "Reference: {{appUrl}}/maintenance/{{maintenanceRequestId}}" },
      { type: "popiaSlot" },
    ],
  },
  {
    key: "incident.critical_owner",
    channel: "email",
    commsClass: "correspondence",
    name: "Critical Incident Notification — Owner",
    description: "Informs the property owner of a critical incident and provides a written record.",
    category: "maintenance",
    subject: "Incident update for {{propertyName}}: {{incidentTitle}}",
    mergeFields: ["{{recipient.salutation}}", "{{ownerName}}", "{{propertyName}}", "{{propertyAddress}}", "{{unitLabel}}", "{{incidentTitle}}", "{{incidentDate}}", "{{incidentDescription}}", "{{brokerName}}", "{{agencyName}}", "{{agentName}}", "{{appUrl}}", "{{maintenanceRequestId}}"],
    legalReviewRef: "ADDENDUM_70C §5.13",
    body: [
      { type: "salutation", text: "{{recipient.salutation}}" },
      { type: "heading", text: "Incident report — {{propertyName}}" },
      { type: "paragraph", text: "We are writing to inform you of a critical incident at your property that was reported on {{incidentDate}}. We are managing the situation and wanted to ensure you have a written record." },
      { type: "dataBox", rows: [
        { label: "Property", value: "{{propertyName}} / {{propertyAddress}}" },
        { label: "Unit / area affected", value: "{{unitLabel}}" },
        { label: "Incident", value: "{{incidentTitle}}" },
        { label: "Date reported", value: "{{incidentDate}}" },
        { label: "Description", value: "{{incidentDescription}}" },
      ] },
      { type: "paragraph", text: "We have notified your insurance broker ({{brokerName}}) of this incident on your behalf. Please follow up with them directly if you wish to open a claim." },
      { type: "paragraph", text: "Your property is being managed by {{agencyName}}. If you have any questions, please contact {{agentName}} directly." },
      { type: "paragraph", text: "Reference: {{appUrl}}/maintenance/{{maintenanceRequestId}}" },
      { type: "popiaSlot" },
    ],
  },
  {
    key: "incident.critical_scheme",
    channel: "email",
    commsClass: "correspondence",
    name: "Critical Incident Notification — Scheme",
    description: "Notifies the managing scheme of a critical incident affecting shared infrastructure.",
    category: "maintenance",
    subject: "Critical incident at {{propertyName}} — {{incidentTitle}}",
    mergeFields: ["{{recipient.salutation}}", "{{schemeName}}", "{{agencyName}}", "{{propertyName}}", "{{propertyAddress}}", "{{unitLabel}}", "{{incidentTitle}}", "{{incidentDate}}", "{{incidentDescription}}", "{{agentName}}", "{{agentPhone}}", "{{appUrl}}", "{{maintenanceRequestId}}"],
    legalReviewRef: "ADDENDUM_70C §5.14",
    body: [
      { type: "salutation", text: "{{recipient.salutation}}" },
      { type: "heading", text: "Critical incident — {{schemeName}}" },
      { type: "paragraph", text: "{{agencyName}} is notifying {{schemeName}} of a critical incident at a property within the scheme. This notification is provided for your records and to allow the managing agent to take any necessary action regarding shared infrastructure or common areas." },
      { type: "dataBox", rows: [
        { label: "Property", value: "{{propertyName}} / {{propertyAddress}}" },
        { label: "Unit / area affected", value: "{{unitLabel}}" },
        { label: "Incident", value: "{{incidentTitle}}" },
        { label: "Date reported", value: "{{incidentDate}}" },
        { label: "Description", value: "{{incidentDescription}}" },
      ] },
      { type: "paragraph", text: "The agency is managing the repair. If any common-property infrastructure is affected — including shared electrical, plumbing, or structural elements — please contact {{agentName}} on {{agentPhone}} at {{agencyName}} to coordinate access and repair scope." },
      { type: "paragraph", text: "Reference: {{appUrl}}/maintenance/{{maintenanceRequestId}}" },
      { type: "popiaSlot" },
    ],
  },

  // ── Maintenance delay (FLAVOURED — friendly/professional/firm openers) ───────────────────────
  {
    key: "maintenance.delay",
    channel: "email",
    commsClass: "correspondence",
    name: "Maintenance Update — Delay",
    description: "Notifies the tenant of a delay to their maintenance request (tone-flavoured opener).",
    category: "maintenance",
    subject: "Update on your maintenance request at {{propertyLabel}}",
    mergeFields: ["{{recipient.salutation}}", "{{propertyLabel}}", "{{delayReason}}", "{{requestTitle}}", "{{revisedDate}}", "{{senderName}}"],
    legalReviewRef: "ADDENDUM_70C §5.5",
    variants: {
      friendly: [
        { type: "salutation", text: "{{recipient.salutation}}" },
        { type: "heading", text: "Maintenance update — delay" },
        { type: "paragraph", text: "We wanted to give you a quick update on your maintenance request at **{{propertyLabel}}**." },
        { type: "paragraph", text: "Unfortunately there has been a delay: {{delayReason}}." },
        { type: "dataBox", rows: [
          { label: "Request", value: "{{requestTitle}}" },
          { label: "Revised date", value: "{{revisedDate}}" },
        ] },
        { type: "paragraph", text: "We apologise for the inconvenience. If you have any questions, please contact {{senderName}}." },
        { type: "signoff", text: "Kind regards,\n{{senderName}}" },
        { type: "popiaSlot" },
      ],
      professional: [
        { type: "salutation", text: "{{recipient.salutation}}" },
        { type: "heading", text: "Maintenance update — delay" },
        { type: "paragraph", text: "We are writing to update you on your maintenance request at **{{propertyLabel}}**." },
        { type: "paragraph", text: "Unfortunately there has been a delay: {{delayReason}}." },
        { type: "dataBox", rows: [
          { label: "Request", value: "{{requestTitle}}" },
          { label: "Revised date", value: "{{revisedDate}}" },
        ] },
        { type: "paragraph", text: "We apologise for the inconvenience. If you have any questions, please contact {{senderName}}." },
        { type: "signoff", text: "Kind regards,\n{{senderName}}" },
        { type: "popiaSlot" },
      ],
      firm: [
        { type: "salutation", text: "{{recipient.salutation}}" },
        { type: "heading", text: "Maintenance update — delay" },
        { type: "paragraph", text: "Please be advised of the following update regarding your maintenance request at **{{propertyLabel}}**." },
        { type: "paragraph", text: "Unfortunately there has been a delay: {{delayReason}}." },
        { type: "dataBox", rows: [
          { label: "Request", value: "{{requestTitle}}" },
          { label: "Revised date", value: "{{revisedDate}}" },
        ] },
        { type: "paragraph", text: "We apologise for the inconvenience. If you have any questions, please contact {{senderName}}." },
        { type: "signoff", text: "Kind regards,\n{{senderName}}" },
        { type: "popiaSlot" },
      ],
    },
  },
]
