/**
 * lib/comms/templates/seed/info-requests.ts — info-request + POPIA-lifecycle seeds (ADDENDUM_70E E3)
 *
 * Data:   data-collection info-requests (POPIA line KEPT via popiaSlot) + POPIA-lifecycle comms
 *         (data-rights + Information Regulator contact in-body — NO popiaSlot, content is verbatim).
 * Notes:  Both groups are commsClass:"correspondence". Info-requests open on a heading (no personal
 *         salutation). Reminders are the FIRM branch (one body per template). NO Tribunal. Reviewable
 *         pre-store source — NOT seeded. Folded from ADDENDUM_70C §9 + §10.
 */

import type { TemplateSeed } from "./types"

export const INFO_REQUEST_SEEDS: TemplateSeed[] = [
  // ── Info requests — base (data-collection · popiaSlot kept) ──────────────────────────────────
  {
    key: "info_request.landlord",
    channel: "email",
    commsClass: "correspondence",
    name: "Info Request — Landlord / Owner Details",
    description: "Request to the owner to confirm owner details during property setup.",
    category: "info_requests",
    mergeFields: ["{{branding.orgName}}", "{{propertyLabel}}", "{{formUrl}}"],
    legalReviewRef: "ADDENDUM_70C §9.1",
    body: [
      { type: "heading", text: "Confirm the owner details" },
      { type: "paragraph", text: "{{branding.orgName}} is setting up {{propertyLabel}} in their property management platform, and needs to confirm a few owner details before the setup can be finalised." },
      { type: "paragraph", text: "This should take about two minutes:" },
      { type: "cta", label: "Open the form", href: "{{formUrl}}" },
      { type: "list", items: [
        "Your full name, or company name if the property is held by an entity",
        "Preferred contact email and phone",
        "Postal address, if different from the property",
      ] },
      { type: "paragraph", text: "This is a secure link, valid for 14 days. If you'd prefer to send the details by email, just reply to this message." },
      { type: "popiaSlot" },
      { type: "signoff", text: "Thanks,\n{{branding.orgName}}" },
    ],
  },
  {
    key: "info_request.insurance",
    channel: "email",
    commsClass: "correspondence",
    name: "Info Request — Insurance Details",
    description: "Request to confirm the current insurance on the property during setup.",
    category: "info_requests",
    mergeFields: ["{{branding.orgName}}", "{{propertyLabel}}", "{{formUrl}}"],
    legalReviewRef: "ADDENDUM_70C §9.2",
    body: [
      { type: "heading", text: "Confirm insurance details" },
      { type: "paragraph", text: "{{branding.orgName}} is setting up {{propertyLabel}} on their property management platform, and needs to confirm the current insurance on the property." },
      { type: "paragraph", text: "Having this on record helps with claims, broker notifications when incidents happen, and annual renewal reminders. It should take about two minutes:" },
      { type: "cta", label: "Open the form", href: "{{formUrl}}" },
      { type: "list", items: [
        "Insurer name",
        "Policy number",
        "Annual renewal date",
        "Replacement value on the current policy",
        "Broker name and contact, if you use one",
      ] },
      { type: "paragraph", text: "This is a secure link, valid for 14 days. If you'd prefer to send the details by email, just reply to this message." },
      { type: "popiaSlot" },
      { type: "signoff", text: "Thanks,\n{{branding.orgName}}" },
    ],
  },
  {
    key: "info_request.broker",
    channel: "email",
    commsClass: "correspondence",
    name: "Info Request — Broker Coverage Confirmation",
    description: "Request to the broker to confirm current coverage on file.",
    category: "info_requests",
    mergeFields: ["{{branding.orgName}}", "{{propertyLabel}}", "{{ownerName}}", "{{formUrl}}"],
    legalReviewRef: "ADDENDUM_70C §9.3",
    body: [
      { type: "heading", text: "Coverage confirmation requested" },
      { type: "paragraph", text: "{{branding.orgName}} manages {{propertyLabel}} on behalf of {{ownerName}}, and is setting up the property on a property management platform." },
      { type: "paragraph", text: "To route incident notifications to the right inbox and keep renewal dates aligned, we'd appreciate your confirmation of the current coverage on file:" },
      { type: "cta", label: "Confirm coverage details", href: "{{formUrl}}" },
      { type: "list", items: [
        "Insurer name and policy number",
        "Replacement value and annual renewal date",
        "Preferred broker contact name and email for incident notifications",
        "Direct phone line for after-hours claims, if available",
      ] },
      { type: "paragraph", text: "Authorisation to disclose these details should be on record with your client; if you'd prefer to confirm with them first, please do reach out directly." },
      { type: "paragraph", text: "This is a secure link, valid for 14 days. If you'd prefer to send the details by email, just reply to this message." },
      { type: "popiaSlot" },
      { type: "signoff", text: "Thanks,\n{{branding.orgName}}" },
    ],
  },
  {
    key: "info_request.scheme",
    channel: "email",
    commsClass: "correspondence",
    name: "Info Request — Scheme Contact Details",
    description: "Request to confirm the right scheme contacts on file.",
    category: "info_requests",
    mergeFields: ["{{branding.orgName}}", "{{propertyLabel}}", "{{schemeName}}", "{{formUrl}}"],
    legalReviewRef: "ADDENDUM_70C §9.4",
    body: [
      { type: "heading", text: "Scheme contact details" },
      { type: "paragraph", text: "{{branding.orgName}} manages a unit at {{propertyLabel}} under {{schemeName}}, and is setting the property up on a property management platform." },
      { type: "paragraph", text: "To keep levies, rules, and scheme communication lined up correctly, we'd appreciate confirmation of the right scheme contacts on file:" },
      { type: "cta", label: "Confirm scheme details", href: "{{formUrl}}" },
      { type: "list", items: [
        "Managing agent name and email",
        "Trustee chair or primary contact, if different",
        "After-hours contact for common-area emergencies",
        "Any change-of-tenancy notification process we should follow",
      ] },
      { type: "paragraph", text: "This is a secure link, valid for 14 days. If you'd prefer to send the details by email, just reply to this message." },
      { type: "popiaSlot" },
      { type: "signoff", text: "Thanks,\n{{branding.orgName}}" },
    ],
  },
  {
    key: "info_request.banking",
    channel: "email",
    commsClass: "correspondence",
    name: "Info Request — Banking Details",
    description: "Request to capture owner banking details via the secure form for owner statement payouts.",
    category: "info_requests",
    mergeFields: ["{{branding.orgName}}", "{{propertyLabel}}", "{{formUrl}}"],
    legalReviewRef: "ADDENDUM_70C §9.5",
    body: [
      { type: "heading", text: "Confirm banking details" },
      { type: "paragraph", text: "{{branding.orgName}} is setting up {{propertyLabel}} on their property management platform. To pay rental income through to you correctly, we need the banking details for your owner statements." },
      { type: "paragraph", text: "Please enter your banking details using the secure form — the account number is encrypted on submission and stored securely:" },
      { type: "cta", label: "Enter banking details securely", href: "{{formUrl}}" },
      { type: "list", items: [
        "Bank name",
        "Account holder name (as it appears on your bank statement)",
        "Account number",
        "Branch code",
        "Account type (cheque, savings, transmission)",
      ] },
      { type: "paragraph", text: "These details are used only to pay your owner statement amounts and will not be shared outside of {{branding.orgName}} and its payment processor." },
      { type: "paragraph", text: "Please do not reply to this email with your banking details. The secure form above is the only safe channel." },
      { type: "paragraph", text: "This is a secure link, valid for 14 days. To submit your details, please use the secure form above — do not reply by email." },
      { type: "popiaSlot" },
      { type: "signoff", text: "Thanks,\n{{branding.orgName}}" },
    ],
  },
  {
    key: "info_request.documents",
    channel: "email",
    commsClass: "correspondence",
    name: "Info Request — Property Documents",
    description: "Request for property documents to be uploaded during setup.",
    category: "info_requests",
    mergeFields: ["{{branding.orgName}}", "{{propertyLabel}}", "{{formUrl}}"],
    legalReviewRef: "ADDENDUM_70C §9.6",
    body: [
      { type: "heading", text: "A few property documents" },
      { type: "paragraph", text: "{{branding.orgName}} is setting up {{propertyLabel}} on their property management platform, and would appreciate a few documents on file. You only need to upload what you have — anything missing can be added later." },
      { type: "cta", label: "Upload documents", href: "{{formUrl}}" },
      { type: "list", items: [
        "Title deed or proof of ownership",
        "Latest municipal rates account",
        "Insurance certificate or schedule",
        "Electrical compliance certificate (CoC), if available",
        "Gas, beetle, plumbing, or other CoCs that apply",
        "Scheme rules or conduct rules, if the property is in a scheme",
      ] },
      { type: "paragraph", text: "The form accepts PDFs, JPGs, and PNGs, up to 20 MB per file." },
      { type: "paragraph", text: "This is a secure link, valid for 14 days. If you'd prefer to send the details by email, just reply to this message." },
      { type: "popiaSlot" },
      { type: "signoff", text: "Thanks,\n{{branding.orgName}}" },
    ],
  },
  {
    key: "info_request.compliance",
    channel: "email",
    commsClass: "correspondence",
    name: "Info Request — Compliance Certificate Details",
    description: "Request to capture compliance certificates on record so renewal reminders can be set.",
    category: "info_requests",
    mergeFields: ["{{branding.orgName}}", "{{propertyLabel}}", "{{formUrl}}"],
    legalReviewRef: "ADDENDUM_70C §9.7",
    body: [
      { type: "heading", text: "Compliance certificate details" },
      { type: "paragraph", text: "{{branding.orgName}} is setting up {{propertyLabel}} on their property management platform, and needs to capture the compliance certificates on record so renewal reminders can be set correctly." },
      { type: "cta", label: "Confirm compliance details", href: "{{formUrl}}" },
      { type: "list", items: [
        "Electrical compliance certificate (CoC) — issue date and expiry",
        "Gas CoC, if the property has a gas installation",
        "Beetle or borer certificate, if one was issued at sale",
        "Pool compliance, where a pool is on the property",
        "Lift inspection certificate, where applicable",
        "Any other municipal or safety certificate the property carries",
      ] },
      { type: "paragraph", text: "For each item you have, the form lets you upload the certificate and capture the issuer and expiry date. Anything you don't have can be marked as \"not applicable\" or left for later." },
      { type: "paragraph", text: "This is a secure link, valid for 14 days. If you'd prefer to send the details by email, just reply to this message." },
      { type: "popiaSlot" },
      { type: "signoff", text: "Thanks,\n{{branding.orgName}}" },
    ],
  },
  {
    key: "info_request.other",
    channel: "email",
    commsClass: "correspondence",
    name: "Info Request — Other / Free-form",
    description: "Free-form information request with agent-supplied prompt during setup.",
    category: "info_requests",
    mergeFields: ["{{branding.orgName}}", "{{propertyLabel}}", "{{prompt}}", "{{formUrl}}"],
    legalReviewRef: "ADDENDUM_70C §9.8",
    validateFields: ["{{prompt}}"],
    body: [
      { type: "heading", text: "A quick request for some information" },
      { type: "paragraph", text: "{{branding.orgName}} is setting up {{propertyLabel}} on their property management platform, and has a few specific questions about the property they'd appreciate your help with." },
      { type: "paragraph", text: "\"{{prompt}}\"" },
      { type: "paragraph", text: "The secure form below has space to answer or upload anything relevant:" },
      { type: "cta", label: "Open the form", href: "{{formUrl}}" },
      { type: "paragraph", text: "This is a secure link, valid for 14 days. If you'd prefer to send the details by email, just reply to this message." },
      { type: "popiaSlot" },
      { type: "signoff", text: "Thanks,\n{{branding.orgName}}" },
    ],
  },

  // ── Info request reminders (FIRM branch — one body per template) ─────────────────────────────
  {
    key: "info_request.landlord_reminder",
    channel: "email",
    commsClass: "correspondence",
    name: "Info Request Reminder — Landlord / Owner Details",
    description: "Firm follow-up reminder for outstanding owner details.",
    category: "info_requests",
    mergeFields: ["{{branding.orgName}}", "{{propertyLabel}}", "{{formUrl}}"],
    legalReviewRef: "ADDENDUM_70C §9.9",
    body: [
      { type: "heading", text: "We still need the owner details" },
      { type: "paragraph", text: "{{branding.orgName}} still needs the owner details for {{propertyLabel}} before the property setup can be finalised." },
      { type: "paragraph", text: "Please take a few minutes to complete the form:" },
      { type: "cta", label: "Open the form", href: "{{formUrl}}" },
      { type: "paragraph", text: "If you've already replied or there's been a mix-up, just let us know by replying to this email." },
      { type: "paragraph", text: "This is a secure link, valid for 14 days. If you'd prefer to send the details by email, just reply to this message." },
      { type: "popiaSlot" },
      { type: "signoff", text: "Thanks,\n{{branding.orgName}}" },
    ],
  },
  {
    key: "info_request.insurance_reminder",
    channel: "email",
    commsClass: "correspondence",
    name: "Info Request Reminder — Insurance Details",
    description: "Firm follow-up reminder for outstanding insurance details.",
    category: "info_requests",
    mergeFields: ["{{branding.orgName}}", "{{propertyLabel}}", "{{formUrl}}"],
    legalReviewRef: "ADDENDUM_70C §9.9",
    body: [
      { type: "heading", text: "Insurance details still outstanding" },
      { type: "paragraph", text: "{{branding.orgName}} is still waiting on the insurance details for {{propertyLabel}}. Without them on record, claims, broker notifications, and renewal reminders can't be set up correctly." },
      { type: "paragraph", text: "Please take a few minutes to complete the form:" },
      { type: "cta", label: "Open the form", href: "{{formUrl}}" },
      { type: "paragraph", text: "If you've already replied or there's been a mix-up, just let us know by replying to this email." },
      { type: "paragraph", text: "This is a secure link, valid for 14 days. If you'd prefer to send the details by email, just reply to this message." },
      { type: "popiaSlot" },
      { type: "signoff", text: "Thanks,\n{{branding.orgName}}" },
    ],
  },
  {
    key: "info_request.broker_reminder",
    channel: "email",
    commsClass: "correspondence",
    name: "Info Request Reminder — Broker Coverage Confirmation",
    description: "Firm follow-up reminder for outstanding broker coverage confirmation.",
    category: "info_requests",
    mergeFields: ["{{branding.orgName}}", "{{propertyLabel}}", "{{ownerName}}", "{{formUrl}}"],
    legalReviewRef: "ADDENDUM_70C §9.9",
    body: [
      { type: "heading", text: "Coverage confirmation still outstanding" },
      { type: "paragraph", text: "{{branding.orgName}} is still waiting on confirmation of the current coverage for {{propertyLabel}}, managed on behalf of {{ownerName}}. Without it, incident notifications and renewal dates can't be routed correctly." },
      { type: "paragraph", text: "Please take a few minutes to complete the form:" },
      { type: "cta", label: "Open the form", href: "{{formUrl}}" },
      { type: "paragraph", text: "Authorisation to disclose these details should be on record with your client; if you'd prefer to confirm with them first, please do reach out directly." },
      { type: "paragraph", text: "This is a secure link, valid for 14 days. If you'd prefer to send the details by email, just reply to this message." },
      { type: "popiaSlot" },
      { type: "signoff", text: "Thanks,\n{{branding.orgName}}" },
    ],
  },
  {
    key: "info_request.scheme_reminder",
    channel: "email",
    commsClass: "correspondence",
    name: "Info Request Reminder — Scheme Contact Details",
    description: "Firm follow-up reminder for outstanding scheme contact details.",
    category: "info_requests",
    mergeFields: ["{{branding.orgName}}", "{{propertyLabel}}", "{{schemeName}}", "{{formUrl}}"],
    legalReviewRef: "ADDENDUM_70C §9.9",
    body: [
      { type: "heading", text: "Scheme contacts still outstanding" },
      { type: "paragraph", text: "{{branding.orgName}} is still waiting on the scheme contacts for {{propertyLabel}} under {{schemeName}}. Without them, levies, rules, and scheme communication can't be lined up correctly." },
      { type: "paragraph", text: "Please take a few minutes to complete the form:" },
      { type: "cta", label: "Open the form", href: "{{formUrl}}" },
      { type: "paragraph", text: "If you've already replied or there's been a mix-up, just let us know by replying to this email." },
      { type: "paragraph", text: "This is a secure link, valid for 14 days. If you'd prefer to send the details by email, just reply to this message." },
      { type: "popiaSlot" },
      { type: "signoff", text: "Thanks,\n{{branding.orgName}}" },
    ],
  },
  {
    key: "info_request.banking_reminder",
    channel: "email",
    commsClass: "correspondence",
    name: "Info Request Reminder — Banking Details",
    description: "Firm follow-up reminder for outstanding owner banking details.",
    category: "info_requests",
    mergeFields: ["{{branding.orgName}}", "{{propertyLabel}}", "{{formUrl}}"],
    legalReviewRef: "ADDENDUM_70C §9.9",
    body: [
      { type: "heading", text: "Banking details still needed" },
      { type: "paragraph", text: "{{branding.orgName}} is holding up owner statements for {{propertyLabel}} until the banking details are captured. Rental income received on your behalf can't be released to you without them." },
      { type: "paragraph", text: "Please take a few minutes to complete the form:" },
      { type: "cta", label: "Enter banking details securely", href: "{{formUrl}}" },
      { type: "paragraph", text: "Please do not reply to this email with your banking details. The secure form above is the only safe channel." },
      { type: "paragraph", text: "This is a secure link, valid for 14 days. To submit your details, please use the secure form above — do not reply by email." },
      { type: "popiaSlot" },
      { type: "signoff", text: "Thanks,\n{{branding.orgName}}" },
    ],
  },
  {
    key: "info_request.documents_reminder",
    channel: "email",
    commsClass: "correspondence",
    name: "Info Request Reminder — Property Documents",
    description: "Firm follow-up reminder for outstanding property documents.",
    category: "info_requests",
    mergeFields: ["{{branding.orgName}}", "{{propertyLabel}}", "{{formUrl}}"],
    legalReviewRef: "ADDENDUM_70C §9.9",
    body: [
      { type: "heading", text: "Property documents still outstanding" },
      { type: "paragraph", text: "{{branding.orgName}} is still waiting on the property documents for {{propertyLabel}}. The setup can't be finalised until what's on hand is on file." },
      { type: "paragraph", text: "Please take a few minutes to complete the form:" },
      { type: "cta", label: "Upload documents", href: "{{formUrl}}" },
      { type: "paragraph", text: "You only need to upload what you have — anything missing can be added later. If you've already replied or there's been a mix-up, just let us know by replying to this email." },
      { type: "paragraph", text: "This is a secure link, valid for 14 days. If you'd prefer to send the details by email, just reply to this message." },
      { type: "popiaSlot" },
      { type: "signoff", text: "Thanks,\n{{branding.orgName}}" },
    ],
  },
  {
    key: "info_request.compliance_reminder",
    channel: "email",
    commsClass: "correspondence",
    name: "Info Request Reminder — Compliance Certificate Details",
    description: "Firm follow-up reminder for outstanding compliance certificate details.",
    category: "info_requests",
    mergeFields: ["{{branding.orgName}}", "{{propertyLabel}}", "{{formUrl}}"],
    legalReviewRef: "ADDENDUM_70C §9.9",
    body: [
      { type: "heading", text: "Compliance details still outstanding" },
      { type: "paragraph", text: "{{branding.orgName}} is still waiting on the compliance certificate details for {{propertyLabel}}. Without expiry dates on file, the platform can't warn you when renewals fall due." },
      { type: "paragraph", text: "Please take a few minutes to complete the form:" },
      { type: "cta", label: "Confirm compliance details", href: "{{formUrl}}" },
      { type: "paragraph", text: "If you've already replied or there's been a mix-up, just let us know by replying to this email." },
      { type: "paragraph", text: "This is a secure link, valid for 14 days. If you'd prefer to send the details by email, just reply to this message." },
      { type: "popiaSlot" },
      { type: "signoff", text: "Thanks,\n{{branding.orgName}}" },
    ],
  },
  {
    key: "info_request.other_reminder",
    channel: "email",
    commsClass: "correspondence",
    name: "Info Request Reminder — Other / Free-form",
    description: "Firm follow-up reminder for an outstanding free-form information request.",
    category: "info_requests",
    mergeFields: ["{{branding.orgName}}", "{{propertyLabel}}", "{{prompt}}", "{{formUrl}}"],
    legalReviewRef: "ADDENDUM_70C §9.9",
    validateFields: ["{{prompt}}"],
    body: [
      { type: "heading", text: "Still waiting on your reply" },
      { type: "paragraph", text: "{{branding.orgName}} is still waiting on the information requested for {{propertyLabel}}. The setup can't be completed until it's on file." },
      { type: "paragraph", text: "\"{{prompt}}\"" },
      { type: "paragraph", text: "Please take a few minutes to complete the form:" },
      { type: "cta", label: "Open the form", href: "{{formUrl}}" },
      { type: "paragraph", text: "If you've already replied or there's been a mix-up, just let us know by replying to this email." },
      { type: "paragraph", text: "This is a secure link, valid for 14 days. If you'd prefer to send the details by email, just reply to this message." },
      { type: "popiaSlot" },
      { type: "signoff", text: "Thanks,\n{{branding.orgName}}" },
    ],
  },

  // ── POPIA lifecycle (data-rights + Information Regulator contact in-body; NO popiaSlot) ───────
  {
    key: "popia.request_received",
    channel: "email",
    commsClass: "correspondence",
    name: "POPIA Request Received",
    description: "Acknowledgement of a POPIA data-subject request with SLA deadline.",
    category: "popia",
    locked: true,
    mergeFields: ["{{recipient.salutation}}", "{{requestType}}", "{{agencyName}}", "{{requestId}}", "{{slaDeadline}}", "{{requestUrl}}"],
    legalReviewRef: "ADDENDUM_70C §10.1",
    body: [
      { type: "salutation", text: "{{recipient.salutation}}" },
      { type: "heading", text: "Your POPIA request has been received" },
      { type: "paragraph", text: "Your {{requestType}} request to {{agencyName}} was received successfully. We are required by POPIA to respond within 30 calendar days." },
      { type: "dataBox", rows: [
        { label: "Request ID", value: "{{requestId}}" },
        { label: "Response deadline", value: "{{slaDeadline}}" },
      ] },
      { type: "cta", label: "View your request", href: "{{requestUrl}}" },
      { type: "paragraph", text: "If you do not receive a response by {{slaDeadline}}, you have the right to complain to the Information Regulator of South Africa at complaints.IR@justice.gov.za or +27 10 023 5207." },
    ],
  },
  {
    key: "popia.request_under_review",
    channel: "email",
    commsClass: "correspondence",
    name: "POPIA Request Under Review",
    description: "Identity verified; POPIA request now under review.",
    category: "popia",
    locked: true,
    mergeFields: ["{{recipient.salutation}}", "{{requestType}}", "{{agencyName}}", "{{slaDeadline}}", "{{requestUrl}}"],
    legalReviewRef: "ADDENDUM_70C §10.2",
    body: [
      { type: "salutation", text: "{{recipient.salutation}}" },
      { type: "heading", text: "Your request is under review" },
      { type: "paragraph", text: "Your identity has been verified. Your {{requestType}} request to {{agencyName}} is now under review. We will notify you when a decision has been made." },
      { type: "dataBox", rows: [
        { label: "Response deadline", value: "{{slaDeadline}}" },
      ] },
      { type: "cta", label: "View request status", href: "{{requestUrl}}" },
      { type: "paragraph", text: "Questions? Reply to this email or contact {{agencyName}} directly." },
    ],
  },
  {
    key: "popia.request_approved",
    channel: "email",
    commsClass: "correspondence",
    name: "POPIA Request Completed",
    description: "POPIA data-subject request completed.",
    category: "popia",
    locked: true,
    mergeFields: ["{{recipient.salutation}}", "{{requestType}}", "{{agencyName}}", "{{resolutionNotes}}", "{{requestUrl}}"],
    legalReviewRef: "ADDENDUM_70C §10.3",
    validateFields: ["{{resolutionNotes}}"],
    body: [
      { type: "salutation", text: "{{recipient.salutation}}" },
      { type: "heading", text: "Your request has been completed" },
      { type: "paragraph", text: "{{agencyName}} has completed your {{requestType}} request." },
      { type: "paragraph", text: "{{resolutionNotes}}" },
      { type: "cta", label: "View full details", href: "{{requestUrl}}" },
      { type: "paragraph", text: "If you are not satisfied with this response, you may complain to the Information Regulator at complaints.IR@justice.gov.za or +27 10 023 5207." },
    ],
  },
  {
    key: "popia.request_rejected",
    channel: "email",
    commsClass: "correspondence",
    name: "POPIA Request Rejected",
    description: "POPIA request could not be fulfilled, with legal basis + escalation rights.",
    category: "popia",
    locked: true,
    mergeFields: ["{{recipient.salutation}}", "{{requestType}}", "{{agencyName}}", "{{resolutionNotes}}", "{{legalBasis}}", "{{requestUrl}}"],
    legalReviewRef: "ADDENDUM_70C §10.4",
    validateFields: ["{{legalBasis}}", "{{resolutionNotes}}"],
    body: [
      { type: "salutation", text: "{{recipient.salutation}}" },
      { type: "heading", text: "Your request could not be fulfilled" },
      { type: "paragraph", text: "{{agencyName}} has reviewed your {{requestType}} request and is unable to fulfil it at this time." },
      { type: "heading", text: "Reason" },
      { type: "paragraph", text: "{{resolutionNotes}}" },
      { type: "heading", text: "Legal basis" },
      { type: "paragraph", text: "{{legalBasis}}" },
      { type: "cta", label: "View your request", href: "{{requestUrl}}" },
      { type: "heading", text: "Your right to escalate" },
      { type: "paragraph", text: "If you believe this decision is incorrect, you have the unconditional right to complain to the Information Regulator of South Africa. The regulator operates independently of Pleks and {{agencyName}}." },
      { type: "dataBox", rows: [
        { label: "Email", value: "complaints.IR@justice.gov.za" },
        { label: "Phone", value: "+27 10 023 5207" },
        { label: "Address", value: "JD House, 27 Stiemens Street, Braamfontein, Johannesburg, 2001" },
        { label: "Web", value: "www.justice.gov.za/inforeg" },
      ] },
    ],
  },
  {
    key: "popia.export_ready",
    channel: "email",
    commsClass: "correspondence",
    name: "POPIA Data Export Ready",
    description: "Data-subject export bundle ready, with tamper-evidence hash.",
    category: "popia",
    locked: true,
    mergeFields: ["{{recipient.salutation}}", "{{requestType}}", "{{agencyName}}", "{{expiresAt}}", "{{manifestHash}}", "{{exportUrl}}", "{{requestUrl}}"],
    legalReviewRef: "ADDENDUM_70C §10.5",
    body: [
      { type: "salutation", text: "{{recipient.salutation}}" },
      { type: "heading", text: "Your data export is ready" },
      { type: "paragraph", text: "{{agencyName}} has prepared your {{requestType}} data export. The bundle includes a PDF summary, a machine-readable JSON file, and where applicable, supporting documents." },
      { type: "cta", label: "Download your data export", href: "{{exportUrl}}" },
      { type: "paragraph", text: "This link expires on {{expiresAt}}. After that, contact {{agencyName}} to request a new link." },
      { type: "heading", text: "Tamper evidence" },
      { type: "dataBox", rows: [
        { label: "Manifest hash", value: "{{manifestHash}}" },
      ] },
      { type: "paragraph", text: "This SHA-256 manifest hash uniquely identifies your export bundle. If you ever need to verify that the export has not been altered since it was issued, provide this hash to the Information Regulator." },
      { type: "cta", label: "View request record", href: "{{requestUrl}}" },
    ],
  },
  {
    key: "popia.nuke_confirmation",
    channel: "email",
    commsClass: "correspondence",
    name: "POPIA Full Erasure Completed",
    description: "Confirmation of completed full-erasure request with retention summary.",
    category: "popia",
    locked: true,
    mergeFields: ["{{recipient.salutation}}", "{{agencyName}}", "{{resolvedAt}}", "{{summary.deleted}}", "{{summary.anonymised}}", "{{summary.retained}}", "{{requestUrl}}"],
    legalReviewRef: "ADDENDUM_70C §10.6",
    body: [
      { type: "salutation", text: "{{recipient.salutation}}" },
      { type: "heading", text: "Full erasure completed" },
      { type: "paragraph", text: "{{agencyName}} has completed your full erasure request on {{resolvedAt}}. Here is a summary of what was done." },
      { type: "heading", text: "What happened" },
      { type: "dataBox", rows: [
        { label: "Records deleted", value: "{{summary.deleted}}" },
        { label: "Records anonymised (identifying fields replaced)", value: "{{summary.anonymised}}" },
        { label: "Records retained (legal requirement)", value: "{{summary.retained}}" },
      ] },
      { type: "heading", text: "Retained as disclosed" },
      { type: "paragraph", text: "The following categories were retained as you acknowledged before submitting:" },
      { type: "callout", tone: "info", text: "The retained categories — each shown as category — reason — render here per request." },
      { type: "cta", label: "View request record", href: "{{requestUrl}}" },
      { type: "paragraph", text: "This confirmation is your record. The consent log entry for this erasure is retained permanently per POPIA accountability requirements and was not deleted." },
      { type: "paragraph", text: "If you have questions, contact {{agencyName}} directly. To escalate to the Information Regulator: complaints.IR@justice.gov.za · +27 10 023 5207." },
    ],
  },
  {
    key: "popia.policy_update",
    channel: "email",
    commsClass: "correspondence",
    name: "Privacy Notice Updated",
    description: "Notice of an updated Pleks Privacy Notice version.",
    category: "popia",
    locked: true,
    mergeFields: ["{{recipient.salutation}}", "{{newVersion}}", "{{effectiveFrom}}", "{{changeSummary}}", "{{oldVersion}}", "{{policyUrl}}"],
    legalReviewRef: "ADDENDUM_70C §10.7",
    body: [
      { type: "salutation", text: "{{recipient.salutation}}" },
      { type: "heading", text: "Pleks Privacy Notice updated" },
      { type: "paragraph", text: "We have updated the Pleks Privacy Notice. The new version ({{newVersion}}) is effective from {{effectiveFrom}}." },
      { type: "heading", text: "What changed" },
      { type: "paragraph", text: "{{changeSummary}}" },
      { type: "cta", label: "Read the updated policy", href: "{{policyUrl}}" },
      { type: "paragraph", text: "The previous version ({{oldVersion}}) remains available at pleks.co.za/privacy/versions/{{oldVersion}} for your reference." },
      { type: "paragraph", text: "If you have questions about these changes, contact privacy@pleks.co.za or the Information Regulator at complaints.IR@justice.gov.za." },
    ],
  },
]
