/**
 * lib/comms/templates/seed/subscriptions.ts — subscription/billing lifecycle seeds (ADDENDUM_70E E3)
 *
 * Data:   agent-facing account-state comms (past-due, paused, resumed, dormancy) + the cancellation
 *         data-retention lifecycle (T1–T6) as TemplateBlock[], folded from ADDENDUM_70C §8.
 * Notes:  Account-state = commsClass:"service". Cancellation lifecycle (T1–T6) = correspondence + locked
 *         (statutory-grade retention content — verbatim Tax Admin Act / PPA Reg 33 / FICA / POPIA /
 *         Companies Act citations). NO popiaSlot/signatureSlot/legalFooterSlot/Tribunal. NOT seeded.
 */

import type { TemplateSeed } from "./types"

export const SUBSCRIPTION_SEEDS: TemplateSeed[] = [
  {
    // 57H D-57H-04: re-homed from the retired subscription.payment_failed key onto the live dunning key.
    key: "subscription.past_due_first",
    channel: "email",
    commsClass: "service",
    name: "Past Due — First Notice (Day 0)",
    description: "First past-due notice — payment didn't process; PayFast will auto-retry, no action required.",
    category: "subscriptions",
    subject: "Payment for {{branding.orgName}} didn't go through",
    mergeFields: ["{{recipient.salutation}}", "{{branding.orgName}}", "{{updatePaymentUrl}}"],
    legalReviewRef: "ADDENDUM_70C §8.1",
    body: [
      { type: "heading", text: "We couldn't process your payment" },
      { type: "salutation", text: "{{recipient.salutation}}" },
      { type: "paragraph", text: "The latest payment for **{{branding.orgName}}** didn't go through on PayFast. No action is required right now — PayFast will automatically retry over the next few days." },
      { type: "paragraph", text: "In the meantime, everything in your Pleks workspace is running as normal. Your properties, leases, tenants and all scheduled communications are completely unaffected." },
      { type: "paragraph", text: "If you'd like to update your card details or check your payment method, you can do that at any time in Settings → Subscription." },
      { type: "cta", label: "Update payment details", href: "{{updatePaymentUrl}}" },
      { type: "paragraph", text: "If payment succeeds in the next few days, you won't hear from us again." },
    ],
  },
  {
    // 57H D-57H-04: re-homed from the retired subscription.payment_reminder key onto the live dunning key.
    key: "subscription.past_due_day7",
    channel: "email",
    commsClass: "service",
    name: "Past Due — Day 7 Reminder",
    description: "Second past-due reminder — payment still pending one week on; auto-pause warning at 14 days.",
    category: "subscriptions",
    subject: "Second reminder: payment for {{branding.orgName}} still pending",
    mergeFields: ["{{recipient.salutation}}", "{{branding.orgName}}", "{{daysOverdue}}", "{{updatePaymentUrl}}"],
    legalReviewRef: "ADDENDUM_70C §8.2",
    body: [
      { type: "heading", text: "Payment still pending — one week on" },
      { type: "salutation", text: "{{recipient.salutation}}" },
      { type: "paragraph", text: "It's been {{daysOverdue}} days since the payment for **{{branding.orgName}}** first failed, and PayFast has retried but the payment still hasn't cleared." },
      { type: "paragraph", text: "Your workspace is still fully active — all reads, reports and scheduled tenant communications are running normally, and nothing has been disrupted for your landlords or tenants." },
      { type: "callout", tone: "warn", text: "**Important:** if payment doesn't clear in the next 7 days, your account will be paused automatically. Updating your payment details or contacting your bank now will prevent this." },
      { type: "cta", label: "Settle payment now", href: "{{updatePaymentUrl}}" },
      { type: "paragraph", text: "Need help? Reply to this email and we'll sort it out with you." },
    ],
  },
  {
    key: "subscription.paused_auto",
    channel: "email",
    commsClass: "service",
    name: "Subscription Paused (Automatic)",
    description: "Account auto-paused after two weeks of failed payment retries; reads/exports/notifications remain available.",
    category: "subscriptions",
    subject: "Your Pleks subscription has been paused",
    mergeFields: ["{{recipient.salutation}}", "{{branding.orgName}}", "{{pausedDate}}", "{{resumeUrl}}"],
    legalReviewRef: "ADDENDUM_70C §8.3",
    body: [
      { type: "heading", text: "Your subscription has been paused" },
      { type: "salutation", text: "{{recipient.salutation}}" },
      { type: "paragraph", text: "After two weeks of unsuccessful payment retries, the **{{branding.orgName}}** subscription was automatically paused on {{pausedDate}}." },
      { type: "heading", text: "Still available" },
      { type: "list", items: [
        "All existing property, lease and tenant data",
        "Financial reports and exports",
        "Scheduled tenant and landlord notifications",
      ] },
      { type: "heading", text: "Paused until payment is settled" },
      { type: "list", items: [
        "Creating new leases",
        "Onboarding new properties",
        "Processing new rental applications",
      ] },
      { type: "paragraph", text: "Settling the overdue payment will restore full access instantly — no further steps needed." },
      { type: "cta", label: "Resume subscription", href: "{{resumeUrl}}" },
    ],
  },
  {
    key: "subscription.paused_manual",
    channel: "email",
    commsClass: "service",
    name: "Subscription Paused (Manual)",
    description: "Confirmation that the agent manually paused their subscription; data safe, resume anytime.",
    category: "subscriptions",
    subject: "Your subscription is now paused",
    mergeFields: ["{{recipient.salutation}}", "{{branding.orgName}}", "{{pausedDate}}", "{{resumeUrl}}"],
    legalReviewRef: "ADDENDUM_70C §8.4",
    body: [
      { type: "heading", text: "You've paused your subscription" },
      { type: "salutation", text: "{{recipient.salutation}}" },
      { type: "paragraph", text: "You've paused the **{{branding.orgName}}** subscription on {{pausedDate}}. Everything you've built in Pleks is safe and waiting for you." },
      { type: "heading", text: "Still available while paused" },
      { type: "list", items: [
        "All existing property, lease and tenant data",
        "Financial reports and exports",
        "Scheduled tenant and landlord notifications",
      ] },
      { type: "heading", text: "Available again when you resume" },
      { type: "list", items: [
        "Creating new leases",
        "Onboarding new properties",
        "Processing new rental applications",
      ] },
      { type: "paragraph", text: "You can resume your subscription at any time from Settings — it only takes a moment and everything will pick up exactly where you left off." },
      { type: "cta", label: "Resume subscription", href: "{{resumeUrl}}" },
    ],
  },
  {
    key: "subscription.resumed",
    channel: "email",
    commsClass: "service",
    name: "Subscription Resumed",
    description: "Payment cleared and subscription fully reactivated; full access restored, no data lost.",
    category: "subscriptions",
    subject: "You're back — subscription reactivated",
    mergeFields: ["{{recipient.salutation}}", "{{branding.orgName}}", "{{dashboardUrl}}"],
    legalReviewRef: "ADDENDUM_70C §8.5",
    body: [
      { type: "heading", text: "All systems go — you're fully active again" },
      { type: "salutation", text: "{{recipient.salutation}}" },
      { type: "paragraph", text: "Payment went through and your **{{branding.orgName}}** subscription is fully active again. Full access has been restored — new leases, properties, applications, everything." },
      { type: "paragraph", text: "All your data is exactly as you left it. Nothing has changed, nothing was lost." },
      { type: "cta", label: "Go to dashboard", href: "{{dashboardUrl}}" },
    ],
  },
  {
    key: "subscription.dormancy_warning",
    channel: "email",
    commsClass: "service",
    name: "Dormancy Warning",
    description: "Inactive Owner-tier account check-in; 30 days to scheduled auto-close, logging in resets the clock.",
    category: "subscriptions",
    subject: "Your Pleks account hasn't been used — a quick check-in",
    mergeFields: ["{{recipient.salutation}}", "{{branding.orgName}}", "{{daysInactive}}", "{{scheduledCloseDate}}", "{{loginUrl}}"],
    legalReviewRef: "ADDENDUM_70C §8.6",
    body: [
      { type: "heading", text: "Checking in on your account" },
      { type: "salutation", text: "{{recipient.salutation}}" },
      { type: "paragraph", text: "Your **{{branding.orgName}}** Pleks account hasn't been active for {{daysInactive}} days. That's completely fine — everything is still here. Your properties, leases and contacts are all safe and waiting for you." },
      { type: "paragraph", text: "Free Owner-tier accounts that remain completely inactive are automatically closed after a period of inactivity, but you have 30 days before that happens. The scheduled close date is {{scheduledCloseDate}}." },
      { type: "paragraph", text: "Simply logging in resets the clock — no forms, no payments, nothing else required." },
      { type: "cta", label: "Log in to keep your account", href: "{{loginUrl}}" },
    ],
  },
  {
    key: "subscription.dormancy_final",
    channel: "email",
    commsClass: "service",
    name: "Dormancy Final Notice",
    description: "Last notice before dormant Owner-tier account auto-closes tomorrow; logging in cancels closure.",
    category: "subscriptions",
    subject: "Last notice: your Pleks account closes tomorrow",
    mergeFields: ["{{recipient.salutation}}", "{{branding.orgName}}", "{{scheduledCloseDate}}", "{{loginUrl}}"],
    legalReviewRef: "ADDENDUM_70C §8.7",
    body: [
      { type: "heading", text: "Account closes tomorrow" },
      { type: "salutation", text: "{{recipient.salutation}}" },
      { type: "callout", tone: "warn", text: "Tomorrow — {{scheduledCloseDate}} — your **{{branding.orgName}}** Pleks account will be automatically closed and all data deleted due to extended inactivity." },
      { type: "paragraph", text: "Logging in today will stop this completely. No form to fill in, no payment required — you're on the free Owner tier. Just log in and the scheduled closure is cancelled immediately." },
      { type: "cta", label: "Log in now to keep your account", href: "{{loginUrl}}" },
    ],
  },
  {
    key: "subscription.cancellation_confirm",
    channel: "email",
    commsClass: "correspondence",
    locked: true,
    name: "Cancellation Confirmation (T1)",
    description: "Confirms subscription cancellation and opens the 12-month read-only retention lifecycle; verbatim retention citations.",
    category: "subscriptions",
    subject: "Your Pleks subscription has been cancelled",
    mergeFields: ["{{recipient.salutation}}", "{{branding.orgName}}", "{{cancelledDate}}", "{{cancellationMethod}}", "{{purgeEligibleAt}}", "{{daysUntilPurge}}", "{{exportUrl}}", "{{reactivateUrl}}"],
    legalReviewRef: "ADDENDUM_70C §8.8",
    body: [
      { type: "heading", text: "Subscription cancelled — your data is available until {{purgeEligibleAt}}" },
      { type: "salutation", text: "{{recipient.salutation}}" },
      { type: "paragraph", text: "Your **{{branding.orgName}}** subscription was cancelled on {{cancelledDate}}. We confirmed this cancellation via {{cancellationMethod}}." },
      { type: "paragraph", text: "By confirming cancellation, you instructed Pleks to begin the account closure and data-retention lifecycle described in Section 04 of our Terms of Service in force at the time of your cancellation. The 12-month read-only access period begins now." },
      { type: "heading", text: "What happens to your data" },
      { type: "paragraph", text: "**Operational data** — properties, leases, communications, tenant profiles, and historical records of day-to-day platform use — remains fully readable and exportable until {{purgeEligibleAt}}. That's 12 months from {{cancelledDate}} ({{daysUntilPurge}} days). After that date, Operational data is deleted from production systems and excluded from backup retention thereafter." },
      { type: "paragraph", text: "**Compliance Records** — a small set of records we are legally required to retain — will not be deleted on {{purgeEligibleAt}}. These include:" },
      { type: "list", items: [
        "Tax and billing records (5 years, Tax Administration Act s29)",
        "Trust account records (5 years from end of financial year, Property Practitioners Act Regulation 33)",
        "FICA verification records (5 years, Financial Intelligence Centre Act s23)",
        "Audit and consent logs (7–10 years, POPIA s17 documentation)",
        "Accounting records (7 years, Companies Act s24)",
        "Records subject to any active legal hold or dispute",
      ] },
      { type: "paragraph", text: "These Compliance Records remain in a restricted-access archive for the periods specified above. The full retention schedule is published in our Privacy Policy." },
      { type: "paragraph", text: "Where retention is required by law, regulatory request, or active dispute, the deletion of Operational data may also be deferred — we will notify you separately if this applies." },
      { type: "heading", text: "What you should do" },
      { type: "paragraph", text: "As the Responsible Party for your tenants' personal information under POPIA, your obligations to those tenants continue after this cancellation. Trust account records carry a 5-year statutory retention requirement under the Property Practitioners Act. Please export and securely store all records you may need for these obligations before {{purgeEligibleAt}}." },
      { type: "cta", label: "Export all data", href: "{{exportUrl}}" },
      { type: "cta", label: "Reactivate", href: "{{reactivateUrl}}" },
      { type: "paragraph", text: "Exports are provided as a downloadable archive at the time of request. You are responsible for verifying that exported records are complete before the deletion date. Pleks does not warrant the long-term integrity of exported files held outside the platform." },
      { type: "heading", text: "Reactivation" },
      { type: "paragraph", text: "You can reactivate your account at any time before {{purgeEligibleAt}} and your Operational data will be restored in place — leases, tenants, documents and history. The Terms of Service and pricing in force at the time of reactivation will apply." },
      { type: "paragraph", text: "All deletion lifecycle dates are calculated in South Africa Standard Time (SAST, UTC+2). Scheduled purge jobs may execute within a 24-hour window of the deletion date." },
      { type: "paragraph", text: "You may request deletion or destruction of personal information under POPIA s24–s25, subject to applicable legal retention obligations. You may also request a copy of your data under s23, or lodge a complaint with the Information Regulator (South Africa) under POPIA s74 — see our Privacy Policy." },
    ],
  },
  {
    key: "subscription.cancellation_warn_90",
    channel: "email",
    commsClass: "correspondence",
    locked: true,
    name: "Cancellation 90-Day Warning (T2)",
    description: "90-day reminder before cancelled account's Operational data is deleted from production; verbatim retention citations.",
    category: "subscriptions",
    subject: "90 days until your Pleks data is scheduled for deletion",
    mergeFields: ["{{recipient.salutation}}", "{{branding.orgName}}", "{{cancelledDate}}", "{{purgeEligibleAt}}", "{{exportUrl}}", "{{reactivateUrl}}"],
    legalReviewRef: "ADDENDUM_70C §8.8",
    body: [
      { type: "heading", text: "90 days until production deletion" },
      { type: "salutation", text: "{{recipient.salutation}}" },
      { type: "paragraph", text: "This is a reminder that the **{{branding.orgName}}** account was cancelled on {{cancelledDate}}." },
      { type: "paragraph", text: "Your Operational data — properties, leases, communications, tenant profiles, and historical records — is scheduled for deletion from production systems on {{purgeEligibleAt}}, 90 days from today. After that date, Operational data will be excluded from backup retention." },
      { type: "heading", text: "What you should do" },
      { type: "paragraph", text: "If you want to keep any Operational records, export them now. You are responsible for verifying that exported records are complete before the deletion date." },
      { type: "cta", label: "Export all data now", href: "{{exportUrl}}" },
      { type: "cta", label: "Reactivate account", href: "{{reactivateUrl}}" },
      { type: "paragraph", text: "If you'd like to continue using Pleks, you can reactivate before {{purgeEligibleAt}} — the Terms of Service and pricing in force at the time of reactivation will apply." },
      { type: "paragraph", text: "As the Responsible Party for your tenants' personal information under POPIA, your obligations to those tenants continue after the deletion. If you require historical lease, payment, or trust records to meet those obligations, export them before {{purgeEligibleAt}}." },
      { type: "paragraph", text: "A small set of Compliance Records — tax, trust, FICA, audit, and accounting records — are retained in a restricted-access archive for between 5 and 10 years depending on the record type, as set out in our Privacy Policy." },
      { type: "paragraph", text: "Deletion dates are calculated in South Africa Standard Time (SAST). Cancellation lifecycle: see Section 04 of our Terms of Service." },
      { type: "paragraph", text: "You may request deletion or destruction of personal information under POPIA s24–s25, subject to applicable legal retention obligations. You may also request a copy of your data under s23, or lodge a complaint with the Information Regulator (South Africa) under POPIA s74 — see our Privacy Policy." },
    ],
  },
  {
    key: "subscription.cancellation_warn_30",
    channel: "email",
    commsClass: "correspondence",
    locked: true,
    name: "Cancellation 30-Day Warning (T3)",
    description: "Final-month reminder — 30 days until cancelled account's Operational data is deleted; verbatim retention citations.",
    category: "subscriptions",
    subject: "30 days until your Pleks data is scheduled for deletion",
    mergeFields: ["{{recipient.salutation}}", "{{branding.orgName}}", "{{cancelledDate}}", "{{purgeEligibleAt}}", "{{exportUrl}}", "{{reactivateUrl}}"],
    legalReviewRef: "ADDENDUM_70C §8.8",
    body: [
      { type: "heading", text: "Final month — 30 days to deletion" },
      { type: "salutation", text: "{{recipient.salutation}}" },
      { type: "paragraph", text: "The **{{branding.orgName}}** account was cancelled on {{cancelledDate}}, and your Operational data is now scheduled for deletion in 30 days — on {{purgeEligibleAt}}." },
      { type: "paragraph", text: "After that date, your Operational records — properties, leases, communications, tenant profiles, and historical activity — will be deleted from production systems and excluded from backup retention." },
      { type: "heading", text: "Last month for export or reactivation" },
      { type: "cta", label: "Export all data now", href: "{{exportUrl}}" },
      { type: "cta", label: "Reactivate account", href: "{{reactivateUrl}}" },
      { type: "paragraph", text: "You are responsible for verifying that exported records are complete before the deletion date." },
      { type: "paragraph", text: "If you'd like to continue using Pleks, reactivate before {{purgeEligibleAt}} — the Terms of Service and pricing in force at the time of reactivation will apply." },
      { type: "paragraph", text: "If you have continuing POPIA, RHA, or PPA obligations to your tenants — including the 5-year trust-record retention — export the records you need before deletion." },
      { type: "paragraph", text: "A small set of Compliance Records — tax, trust, FICA, audit, and accounting records — are retained in a restricted-access archive for between 5 and 10 years depending on the record type, as set out in our Privacy Policy." },
      { type: "paragraph", text: "All deletion lifecycle dates are calculated in South Africa Standard Time (SAST). Cancellation lifecycle: see Section 04 of our Terms of Service." },
      { type: "paragraph", text: "You may request deletion or destruction of personal information under POPIA s24–s25, subject to applicable legal retention obligations. You may also request a copy of your data under s23, or lodge a complaint with the Information Regulator (South Africa) under POPIA s74 — see our Privacy Policy." },
    ],
  },
  {
    key: "subscription.cancellation_warn_7",
    channel: "email",
    commsClass: "correspondence",
    locked: true,
    name: "Cancellation 7-Day Warning (T4)",
    description: "Final-week reminder — 7 days until cancelled account's Operational data is deleted; verbatim retention citations.",
    category: "subscriptions",
    subject: "7 days until your Pleks data is deleted",
    mergeFields: ["{{recipient.salutation}}", "{{branding.orgName}}", "{{purgeEligibleAt}}", "{{exportUrl}}", "{{reactivateUrl}}"],
    legalReviewRef: "ADDENDUM_70C §8.8",
    body: [
      { type: "callout", tone: "warn", text: "⚠ One week to data deletion" },
      { type: "salutation", text: "{{recipient.salutation}}" },
      { type: "paragraph", text: "This is a final-week reminder. The **{{branding.orgName}}** account is scheduled for Operational data deletion on {{purgeEligibleAt}} — 7 days from today." },
      { type: "paragraph", text: "All properties, leases, communications, tenant profiles, and historical records will be deleted from production systems and excluded from backup retention." },
      { type: "heading", text: "Last chance to export or reactivate" },
      { type: "cta", label: "Export all data now", href: "{{exportUrl}}" },
      { type: "cta", label: "Reactivate account", href: "{{reactivateUrl}}" },
      { type: "paragraph", text: "You are responsible for verifying that exported records are complete before the deletion date. If anything is missing or unreadable, contact support@pleks.co.za this week — after {{purgeEligibleAt}}, Operational records will no longer be recoverable through Pleks production systems once the backup-retention window expires." },
      { type: "paragraph", text: "If you'd like to continue using Pleks, reactivate before {{purgeEligibleAt}} — the Terms of Service and pricing in force at the time of reactivation will apply." },
      { type: "paragraph", text: "A small set of Compliance Records — tax, trust, FICA, audit, and accounting records — are retained in a restricted-access archive for between 5 and 10 years depending on the record type, as set out in our Privacy Policy." },
      { type: "paragraph", text: "Deletion lifecycle calculated in South Africa Standard Time (SAST)." },
      { type: "paragraph", text: "You may request deletion or destruction of personal information under POPIA s24–s25, subject to applicable legal retention obligations. You may also request a copy of your data under s23, or lodge a complaint with the Information Regulator (South Africa) under POPIA s74 — see our Privacy Policy." },
    ],
  },
  {
    key: "subscription.cancellation_warn_24h",
    channel: "email",
    commsClass: "correspondence",
    locked: true,
    name: "Cancellation Final 24-Hour Warning (T5)",
    description: "Final 24-hour notice before cancelled account's Operational data is deleted tomorrow; verbatim retention citations.",
    category: "subscriptions",
    subject: "Final notice: your Pleks data is deleted tomorrow",
    mergeFields: ["{{recipient.salutation}}", "{{branding.orgName}}", "{{purgeEligibleAt}}", "{{exportUrl}}", "{{reactivateUrl}}"],
    legalReviewRef: "ADDENDUM_70C §8.8",
    body: [
      { type: "callout", tone: "warn", text: "⚠ Operational data deletion is tomorrow" },
      { type: "salutation", text: "{{recipient.salutation}}" },
      { type: "paragraph", text: "Tomorrow — {{purgeEligibleAt}} — is the scheduled production-deletion date for **{{branding.orgName}}**. After this date, Operational data will no longer be recoverable through Pleks production systems once the backup-retention window expires." },
      { type: "paragraph", text: "All properties, leases, communications, tenant profiles, and historical records will be deleted from production systems and excluded from backup retention." },
      { type: "cta", label: "Export all data now", href: "{{exportUrl}}" },
      { type: "cta", label: "Reactivate account", href: "{{reactivateUrl}}" },
      { type: "paragraph", text: "You are responsible for verifying that exported records are complete before deletion. The deletion job runs in South Africa Standard Time and may execute within a 24-hour window of {{purgeEligibleAt}}." },
      { type: "paragraph", text: "If you'd like to keep your account, reactivate before 23:59 SAST tonight — the Terms of Service and pricing in force at the time of reactivation will apply." },
      { type: "paragraph", text: "A small set of Compliance Records — tax, trust, FICA, audit, and accounting records — are retained in a restricted-access archive for between 5 and 10 years depending on the record type, as set out in our Privacy Policy." },
      { type: "paragraph", text: "All deletion lifecycle dates are calculated in South Africa Standard Time (SAST, UTC+2). Cancellation lifecycle: Section 04 of our Terms of Service in force at the time of your cancellation." },
      { type: "paragraph", text: "You may request deletion or destruction of personal information under POPIA s24–s25, subject to applicable legal retention obligations. You may also request a copy of your data under s23, or lodge a complaint with the Information Regulator (South Africa) under POPIA s74 — see our Privacy Policy." },
    ],
  },
  {
    key: "subscription.account_closed",
    channel: "email",
    commsClass: "correspondence",
    locked: true,
    name: "Account Closed (T6)",
    description: "Post-deletion confirmation — Operational data deleted, Compliance Records retained; verbatim retention citations + final billing.",
    category: "subscriptions",
    subject: "Your Pleks account has been closed",
    mergeFields: ["{{recipient.salutation}}", "{{branding.orgName}}", "{{recipientEmail}}", "{{cancelledDate}}", "{{purgedDate}}", "{{finalInvoiceDate}}"],
    legalReviewRef: "ADDENDUM_70C §8.8",
    body: [
      { type: "heading", text: "Account closed" },
      { type: "salutation", text: "{{recipient.salutation}}" },
      { type: "paragraph", text: "The **{{branding.orgName}}** account ({{recipientEmail}}), cancelled on {{cancelledDate}}, was closed on {{purgedDate}}." },
      { type: "heading", text: "What was deleted" },
      { type: "paragraph", text: "Operational data — properties, leases, communications, tenant profiles, and historical records of day-to-day platform use — has been deleted from production systems and excluded from backup retention thereafter." },
      { type: "heading", text: "What is retained" },
      { type: "paragraph", text: "The following Compliance Records remain in a restricted-access archive for the periods specified, as set out in our Privacy Policy:" },
      { type: "list", items: [
        "Tax and billing records (5 years, Tax Administration Act s29)",
        "Trust account records (5 years from end of financial year, Property Practitioners Act Regulation 33)",
        "FICA verification records (5 years, Financial Intelligence Centre Act s23)",
        "Audit and consent logs (7–10 years, POPIA s17 documentation)",
        "Accounting records (7 years, Companies Act s24)",
        "Records subject to any active legal hold or dispute",
      ] },
      { type: "paragraph", text: "These records are accessed only for the legal obligation that requires their retention, and are deleted at the end of the applicable retention window." },
      { type: "heading", text: "Final billing" },
      { type: "paragraph", text: "The final invoice for **{{branding.orgName}}** was issued on {{finalInvoiceDate}}. No further charges will be made to your payment method." },
      { type: "heading", text: "If you believe this is in error" },
      { type: "paragraph", text: "If you believe this account closure was made in error, or if you need to access your retained Compliance Records, contact us at support@pleks.co.za. Pleks retains a documented record of all cancellation and deletion events for accountability purposes under POPIA s17." },
      { type: "paragraph", text: "Deletion lifecycle dates are calculated in South Africa Standard Time (SAST, UTC+2)." },
      { type: "paragraph", text: "This account no longer exists as an active production account. Compliance Records are retained per the schedule above and our Privacy Policy. You may at any time lodge a complaint about data handling with the Information Regulator (South Africa) under POPIA s74." },
    ],
  },
]
