/**
 * lib/help/help-data.ts — Help Centre corpus (BUILD_68)
 *
 * Auth:   none — imported by the /help page (server) and the floating widget (client).
 * Data:   content-as-data, role-tagged. NOT a DB table (D-HELP-01): small, legally-verified,
 *         version-controlled, offline-cacheable, zero infra. One corpus, two surfaces (widget
 *         preview + /help page) so there's no second FAQ array that can drift.
 * Notes:  ⚠ DRAFT — `HELP_CONTENT_DRAFT` is true until Stéan's §7 content-compliance pass signs
 *         off every answer against the no-payment-rails / not-the-trustee invariants. Statutory
 *         values (RHA deposit windows, CPA notice windows) are stated AS THE LAW, not config, and
 *         must track any amendment. Config values (fees, affordability %, app URL) are interpolated
 *         from the SSOT (lib/constants.ts) — never hardcoded. Source draft: brief/build/_OTHER/faq.md.
 */
import { APP_URL, APPLICATION_FEE_CENTS, JOINT_APPLICATION_FEE_CENTS, INCOME_AFFORDABILITY_THRESHOLD, formatZAR } from "@/lib/constants"

// ── SSOT-derived values (no hardcoded literals — feedback_no_hardcoded_values) ────────────────
const APP_FEE = formatZAR(APPLICATION_FEE_CENTS)
const JOINT_FEE = formatZAR(JOINT_APPLICATION_FEE_CENTS)
const AFFORD = `${Math.round(INCOME_AFFORDABILITY_THRESHOLD * 100)}%`
const APP_HOST = APP_URL.replace(/^https?:\/\//, "")
/** Help contact (in-app fallback when an answer doesn't resolve a question). */
export const HELP_SUPPORT_EMAIL = "support@pleks.co.za"

// ── Schema ────────────────────────────────────────────────────────────────────────────────────
export type HelpRole = "agent" | "tenant" | "landlord" | "supplier"

export interface HelpCategory { id: string; label: string }

export interface HelpEntry {
  id: string             // stable q-{category}-{slug}; documents concept, never a URL
  roles: HelpRole[]      // which audiences see this entry
  category: string       // HelpCategory id
  q: string
  a: string              // MUST satisfy the §7 compliance invariants
  keywords?: string[]    // synonyms users type; also the future AI-grounding signal (D-HELP-07)
  legalCheck?: boolean   // statutory/compliance-weighted — prioritised in the §7 pass
}

/** Flip to false only after Stéan's §7 content-compliance pass (D-HELP-20). */
export const HELP_CONTENT_DRAFT = true

export const ALL_ROLES: HelpRole[] = ["agent", "tenant", "landlord", "supplier"]

export const HELP_ROLES: { id: HelpRole; label: string }[] = [
  { id: "agent",    label: "Agency" },
  { id: "tenant",   label: "Tenant" },
  { id: "landlord", label: "Landlord" },
  { id: "supplier", label: "Supplier" },
]

// Ordered; a category with no entries for the active role does not render (D-HELP-15).
export const HELP_CATEGORIES: HelpCategory[] = [
  { id: "account",      label: "Account & security" },
  { id: "start",        label: "Getting started" },
  { id: "trust",        label: "Trust & payments" },
  { id: "arrears",      label: "Arrears" },
  { id: "applications", label: "Applications & screening" },
  { id: "leases",       label: "Leases, renewals & notices" },
  { id: "maintenance",  label: "Maintenance, inspections & deposits" },
  { id: "utilities",    label: "Utilities, municipal & schemes" },
  { id: "reports",      label: "Reports, statements & team" },
  { id: "billing",      label: "Billing & subscription" },
  { id: "portal",       label: "Your portal" },
  { id: "payments",     label: "Paying & getting paid" },
  { id: "living",       label: "Living in your home" },
  { id: "jobs",         label: "Jobs & invoices" },
]

export const HELP_ENTRIES: HelpEntry[] = [
  // ── General (all roles) — Account & security ──────────────────────────────────────────────
  { id: "q-account-signin", roles: ALL_ROLES, category: "account",
    q: "How do I sign in to Pleks?",
    a: `Go to ${APP_HOST} and sign in with your email and password. You can also use a passkey, or ask for a one-time login link by email ("Email me a login link"). Agents are protected by an extra security step (see two-factor authentication below).`,
    keywords: ["log in", "login", "sign on", "access"] },
  { id: "q-account-forgot", roles: ALL_ROLES, category: "account",
    q: "I forgot my password.",
    a: `On the sign-in screen choose "Forgot password". Enter your email and we'll send you a secure link to set a new one. The link only works on the official Pleks site and expires after a short while, so request a fresh one if it lapses.`,
    keywords: ["reset password", "can't log in", "locked out"] },
  { id: "q-account-mfa", roles: ALL_ROLES, category: "account",
    q: "What is two-factor authentication (2FA / MFA) and why do I need it?",
    a: `Two-factor authentication adds a second check on top of your password so that a stolen password alone can't get into your account. Agency (staff) accounts require it because they can see tenant, landlord and trust information. You set it up once with an authenticator app, and optionally a passkey.`,
    keywords: ["2fa", "otp", "authenticator", "totp"] },
  { id: "q-account-totp-setup", roles: ALL_ROLES, category: "account",
    q: "How do I set up an authenticator app?",
    a: `When prompted, open an authenticator app (Google Authenticator, Authy, 1Password, Bitwarden, or iCloud Keychain), scan the QR code we show you, and enter the 6-digit code it generates. We'll also show you a backup secret — save it in your password manager so you can recover access if you lose your phone.` },
  { id: "q-account-passkey", roles: ALL_ROLES, category: "account",
    q: "What is a passkey and should I use one?",
    a: `A passkey signs you in with your fingerprint, face, or device PIN instead of a password — it can't be phished or guessed. If your device supports it, choose "Set up a passkey" during onboarding or in Security settings. Once enrolled, "Sign in with passkey" logs you straight in, and for agents it satisfies two-factor on its own (no separate code needed).`,
    keywords: ["face id", "fingerprint", "touch id", "windows hello"] },
  { id: "q-account-lost-phone", roles: ALL_ROLES, category: "account",
    q: "I lost my phone / my authenticator app — how do I get back in?",
    a: `If you set up a passkey, choose "Use a passkey instead" on the verification screen to sign in without your authenticator. If you saved your backup secret, add it to a new authenticator app. If you have neither, contact your agency (tenants, landlords and suppliers) or Pleks support (agents) to reset your second factor.`,
    keywords: ["lost authenticator", "new phone", "can't get the code", "recovery"] },
  { id: "q-account-change", roles: ALL_ROLES, category: "account",
    q: "How do I change my email, password, or security settings?",
    a: `Open your account's Security section (Settings → Security for agents; Account → Security in the tenant, landlord and supplier portals). From there you can change your password, manage your authenticator and passkeys, and review active sessions.` },
  { id: "q-account-shared", roles: ALL_ROLES, category: "account",
    q: "Why was I asked to sign in again on a shared computer?",
    a: `For your protection, signing out — or a session timing out — clears your access on that device, so the next person can't pick up where you left off. On a shared or public computer, always sign out when you're done rather than just closing the tab.` },
  { id: "q-account-install", roles: ALL_ROLES, category: "account",
    q: "Can I install Pleks as an app on my phone?",
    a: `Yes. Pleks is a progressive web app — open ${APP_HOST} in your phone's browser and choose "Add to Home Screen" (or accept the install prompt). It then behaves like an installed app and works on slower connections.`,
    keywords: ["app store", "install app", "home screen", "pwa"] },
  { id: "q-account-offline", roles: ALL_ROLES, category: "account",
    q: "Does Pleks work offline or on a poor connection?",
    a: `Largely, yes. As an installed app, Pleks caches what you've recently viewed so you can keep reading and working on a weak signal, and it syncs your changes once you're back online. Some actions (like running a screening check) need a live connection and will wait until you reconnect.` },
  { id: "q-account-browsers", roles: ALL_ROLES, category: "account",
    q: "Which browsers and devices does Pleks support?",
    a: `Any current browser on phone, tablet or desktop — Chrome, Safari, Edge or Firefox. Passkeys and the "add to home screen" install work best on an up-to-date device. You don't need to install anything from an app store.` },
  { id: "q-account-contact", roles: ALL_ROLES, category: "account",
    q: "How will Pleks contact me — email, SMS or WhatsApp?",
    a: `Important notices reach you by email, and depending on your agency's setup, also by WhatsApp or SMS. Tenants, landlords and suppliers receive agency-driven communications; you'll always have an in-app record under Communications (or your portal's messages area) as well.` },
  { id: "q-account-popia", roles: ALL_ROLES, category: "account",
    q: "Is my information secure and POPIA-compliant?",
    a: `Yes. Access is role-scoped so you only see what's relevant to you, sensitive personal fields are encrypted, and every change is recorded in an audit trail. You can request access to, or deletion of, your personal information from the Privacy section of your portal. See the POPIA register for the full detail.`,
    keywords: ["privacy", "data protection", "popia", "security"], legalCheck: true },
  { id: "q-account-who-sees", roles: ALL_ROLES, category: "account",
    q: "Who can see my personal information?",
    a: `Only the people who need it for your tenancy or account: your managing agency, and Pleks as the software provider, within role-scoped limits. Pleks never sells your information and never shares identifying details with third parties without a lawful basis. You can review what's held in the Privacy section of your portal.`,
    legalCheck: true },
  { id: "q-account-feedback", roles: ALL_ROLES, category: "account",
    q: "Something is broken or I have a suggestion — how do I tell you?",
    a: `Use the help button (bottom-right of the screen) and choose "Report a problem" or "Send feedback". A problem report automatically attaches the technical details we need to investigate, so you only have to describe what happened in one line.` },
  { id: "q-account-help-types", roles: ALL_ROLES, category: "account",
    q: `What's the difference between "Report a problem", "Send feedback" and "Need support"?`,
    a: `"Report a problem" is for something broken — it captures the technical detail for us automatically. "Send feedback" is for ideas, requests or a note about how Pleks is working for you. "Need support" is where you'll find answers to common questions first, with a way to reach the team if you're still stuck.` },

  // ── Agent — Getting started ───────────────────────────────────────────────────────────────
  { id: "q-start-setup", roles: ["agent"], category: "start",
    q: "How do I set up my agency for the first time?",
    a: `After signing up you'll complete a short onboarding: confirm your agency details and location, accept the terms, and secure your account with two-factor authentication. You then land on your dashboard, ready to add properties, landlords and tenants.` },
  { id: "q-start-first", roles: ["agent"], category: "start",
    q: "What should I do first after onboarding?",
    a: `A practical order is: add a landlord, add their property and units, then add a tenant and create the lease — that chain gives you working invoicing, arrears tracking and statements straight away. You can also invite a colleague and set up your trust reconciliation in parallel.` },
  { id: "q-start-property", roles: ["agent"], category: "start",
    q: "How do I add a property?",
    a: `Go to Properties → Add property. Capture the address and details, then add the building, units, and any inspection or insurance information. A property can hold multiple units, each of which can carry its own lease.` },
  { id: "q-start-landlord", roles: ["agent"], category: "start",
    q: "How do I add a landlord (owner)?",
    a: `Open Landlords → Add landlord and capture their contact and banking-mandate details. You can then link them to the properties they own, so their statements and trust summary reflect the right portfolio.` },
  { id: "q-start-lease", roles: ["agent"], category: "start",
    q: "How do I add a tenant and create a lease?",
    a: `Add the tenant under Tenants (or convert them from an approved application), then go to Leases → New lease to link the tenant to a unit, set the rent, deposit, dates and charges. Leases drive your invoicing, arrears tracking, deposit handling and statements.` },
  { id: "q-start-applicant", roles: ["agent"], category: "start",
    q: "What's the difference between an applicant and a tenant?",
    a: `They're the same person at different stages — an applicant is simply a tenant who doesn't have an active lease yet. When you approve an application and activate a lease, the applicant becomes the lease's tenant; there's no separate "applicant" record to re-capture.` },
  { id: "q-start-invite", roles: ["agent"], category: "start",
    q: "Can I invite a landlord or tenant to their own portal?",
    a: `Yes. When you add them you can send an invite by email or WhatsApp; they set up their own sign-in and confirm their own details, so you never key in their personal or banking information yourself. Until they accept, you still see their record and can manage the lease.` },
  { id: "q-start-demo", roles: ["agent"], category: "start",
    q: "Is there a way to explore Pleks without touching real data?",
    a: `Yes — the demo environment lets you click through the product with sample data that resets when you leave. It's for learning the flow and showing a colleague; nothing you do there affects your real agency or any live records.`,
    keywords: ["sandbox", "test", "try"] },

  // ── Agent — Trust & payments ──────────────────────────────────────────────────────────────
  { id: "q-trust-holds-money", roles: ["agent"], category: "trust",
    q: "Does Pleks hold or move my trust money?",
    a: `No. Pleks is never the trustee and is never in the payment flow — it cannot hold, receive or move money. Your trust account stays at your bank, in your name, under your control. Pleks reads the bank-statement data you bring in to reconcile what was paid.`,
    keywords: ["trust account", "wallet", "holds money", "custody"], legalCheck: true },
  { id: "q-trust-matching", roles: ["agent"], category: "trust",
    q: "How does payment matching work if Pleks isn't in the flow?",
    a: `Tenants pay into your account by the method on their lease. Pleks matches those incoming payments against the invoices on your bank statement, so you can see who has paid, who is short, and who is in arrears — without Pleks ever touching the money.`,
    keywords: ["reconcile", "matching", "allocation"] },
  { id: "q-trust-import", roles: ["agent"], category: "trust",
    q: "How do I bring my bank statement into Pleks for reconciliation?",
    a: `You import the statement your bank exports — Pleks reads the common formats (OFX, CSV and QIF) — and it matches the transactions against your invoices and ledgers. You review the matches, allocate anything unmatched, and approve the reconciled position. Pleks reads the file; it never connects to move money.`,
    keywords: ["bank feed", "import statement", "ofx", "csv"] },
  { id: "q-trust-unallocated", roles: ["agent"], category: "trust",
    q: "A payment came in but isn't allocated — why, and what do I do?",
    a: `An incoming payment that doesn't carry a clear reference or matching amount waits in an unallocated view rather than being guessed onto the wrong lease. Open Reconciliation → Unallocated, pick the correct lease and allocate it; the audit trail records who allocated it and when.`,
    keywords: ["unmatched", "unallocated", "wrong reference"] },
  { id: "q-trust-debicheck", roles: ["agent"], category: "trust",
    q: "Can Pleks collect rent by debit order / DebiCheck?",
    a: `No. Pleks does not create debit orders or DebiCheck mandates and is not a payment processor. Any debit-order mandate stays between your agency and your bank; Pleks only reads the resulting payment matches on your statement.`,
    keywords: ["debit order", "debicheck", "collect rent", "mandate"], legalCheck: true },
  { id: "q-trust-payouts", roles: ["agent"], category: "trust",
    q: "How do landlord payouts work?",
    a: `Once rent has cleared and your deductions (commission, fees, agreed maintenance) are accounted for, Pleks shows the net due to each landlord and records the payout against their ledger when you make it. The payment itself goes out through your bank — Pleks keeps the record and the statement, it doesn't release the funds.`,
    keywords: ["payout", "disbursement", "pay landlord"], legalCheck: true },
  { id: "q-trust-deposits", roles: ["agent"], category: "trust",
    q: "How are deposits and deposit interest handled?",
    a: `Deposits are held in your trust account (not by Pleks). Pleks tracks each deposit, accrues interest according to your configured rate, and keeps a per-lease ledger of receipts, interest, deductions and refunds so the deposit can be reconciled and returned correctly at the end of the lease.`,
    keywords: ["deposit interest", "deposit ledger"] },
  { id: "q-trust-health", roles: ["agent"], category: "trust",
    q: "What is the trust health / trust summary?",
    a: `It's an at-a-glance view of your trust position — what's held, what's owed, and whether everything reconciles — so you (and your landlords) can see that money is accounted for. Because Pleks isn't the custodian, this reflects your bank reality rather than a balance Pleks controls.` },
  { id: "q-trust-recon", roles: ["agent"], category: "trust",
    q: "What is a trust reconciliation period and why do I close it?",
    a: `Reconciling and closing each period gives you a fixed, signed-off record of your trust position for that month — the kind of evidence your auditor and the regulator expect. Once a period is closed it's locked so the history can't be quietly changed; later corrections happen in the open period with a clear trail.`,
    legalCheck: true },
  { id: "q-trust-audit", roles: ["agent"], category: "trust",
    q: "Does Pleks replace my PPRA / EAAB trust-account audit obligations?",
    a: `No. Pleks helps you reconcile and produce clean records, but you remain the accountable party for your trust account and its audit under the PPRA (formerly EAAB) and FIC requirements. Pleks is a record-keeping and reconciliation tool, not your auditor and not the trustee.`,
    keywords: ["ppra", "eaab", "fic", "audit", "trustee"], legalCheck: true },

  // ── Agent — Arrears ───────────────────────────────────────────────────────────────────────
  { id: "q-arrears-how", roles: ["agent"], category: "arrears",
    q: "How does Pleks help with arrears?",
    a: `When a tenant falls behind, Pleks opens an arrears case and can run a reminder/escalation sequence on a schedule, so follow-ups happen consistently instead of being forgotten. You stay in control of tone and escalation; Pleks handles the timing and the record-keeping.` },
  { id: "q-arrears-tone", roles: ["agent"], category: "arrears",
    q: "Can I control the tone and timing of arrears reminders?",
    a: `Yes. You set the escalation schedule and choose a communication tone for your agency, and Pleks sends on that basis across the channels you've enabled (in-app, WhatsApp, email). Every notice is logged with its content and delivery, so you have a defensible record of what was sent and when.` },
  { id: "q-arrears-lod", roles: ["agent"], category: "arrears",
    q: "Does Pleks send a Letter of Demand or final notice?",
    a: `Pleks can generate later-stage arrears communications, including demand and final-notice wording drawing on the relevant Rental Housing Act and Consumer Protection Act provisions, and log them for your records. You review and approve before anything is sent, and legal escalation beyond that remains your decision and your attorney's.`,
    keywords: ["letter of demand", "lod", "final notice", "eviction"], legalCheck: true },

  // ── Agent — Applications & screening ──────────────────────────────────────────────────────
  { id: "q-applications-fitscore", roles: ["agent"], category: "applications",
    q: "How does tenant screening / FitScore work?",
    a: `When an applicant applies, Pleks compiles a screening report (FitScore) drawing on the information and checks for that application — including an income-affordability view (rent against income, guided by a ~${AFFORD} threshold rather than a hard cut-off). The agent-facing result is a parallel rendering of the same evidence held in the archived report of record, so it's tribunal-defensible.`,
    keywords: ["fitscore", "screening", "credit check", "vet tenant"] },
  { id: "q-applications-decline", roles: ["agent"], category: "applications",
    q: "Does a low FitScore automatically decline an applicant?",
    a: `No. FitScore is a decision aid, never an automatic accept or decline, and every applicant is shown to you regardless of score — the underlying factors are laid out so you make and own the decision. Showing all applicants and the reasoning is also your protection against unfair-discrimination claims.`,
    legalCheck: true },
  { id: "q-applications-consent", roles: ["agent"], category: "applications",
    q: "What checks are included, and do I need the applicant's consent?",
    a: `Screening can draw on credit-bureau and identity checks alongside the affordability view, and it is only run with the applicant's explicit, recorded consent — consent is captured before any check is requested. The raw report is retained only as long as needed and is stored as the report of record.`,
    keywords: ["consent", "credit bureau", "id check"], legalCheck: true },
  { id: "q-applications-affordability", roles: ["agent"], category: "applications",
    q: "How is affordability assessed?",
    a: `Affordability compares the rent against the applicant's verified income, using an income threshold of ${AFFORD} as a guide. It's one signal among several in the report — you see the figures rather than just a verdict.` },
  { id: "q-applications-fee", roles: ["agent"], category: "applications",
    q: "What does an application cost?",
    a: `Application fees are fixed: ${APP_FEE} for a single applicant and ${JOINT_FEE} for a joint application. These are screening fees tied to the application, separate from any rent or deposit.`,
    keywords: ["application fee", "screening fee", "cost"] },
  { id: "q-applications-to-lease", roles: ["agent"], category: "applications",
    q: "How do I turn an approved application into a lease?",
    a: `Open the approved application and choose Generate lease. Pleks pre-fills the parties, unit and terms from the application so you're not re-capturing anything; you review, adjust and send for signature.` },

  // ── Agent — Leases, renewals & notices ────────────────────────────────────────────────────
  { id: "q-leases-generate", roles: ["agent"], category: "leases",
    q: "Can I generate leases and other documents, and get them signed?",
    a: `Yes. Pleks has document templates and built-in e-signature, so you can generate a lease or notice from a template and send it for signature. Signing is hosted on South African infrastructure.`,
    keywords: ["e-signature", "sign lease", "template", "docuseal"] },
  { id: "q-leases-custom", roles: ["agent"], category: "leases",
    q: "Can Pleks produce a custom or non-standard lease?",
    a: `The built-in templates cover standard residential leases. For a bespoke lease or unusual clauses, Pleks offers this as a managed once-off service rather than a complex self-service clause builder — reach the team and they'll set up the template for you to reuse.` },
  { id: "q-leases-renewals", roles: ["agent"], category: "leases",
    q: "How do renewals and escalations work?",
    a: `Pleks flags leases approaching expiry and can apply the agreed escalation to a renewal offer. You approve before anything is sent to the tenant. Where the Consumer Protection Act applies, a fixed-term lease must be preceded by a continuation notice 20 business days before expiry — Pleks helps you stay ahead of that window.`,
    keywords: ["renewal", "escalation", "cpa notice", "continuation"], legalCheck: true },
  { id: "q-leases-end", roles: ["agent"], category: "leases",
    q: "What happens when a lease reaches its end date?",
    a: `You'll be prompted ahead of expiry to renew, let it continue month-to-month, or begin the move-out and deposit close-out. Whichever path you take, the lease history, the outgoing inspection and the deposit ledger stay linked so the close-out is clean and defensible.` },

  // ── Agent — Maintenance, inspections & deposits ───────────────────────────────────────────
  { id: "q-maintenance-handle", roles: ["agent"], category: "maintenance",
    q: "How do I handle a maintenance request?",
    a: `Maintenance requests (logged by you or raised by a tenant) appear under Maintenance. You can assign a supplier, request a quote, track progress and delays, and keep the landlord and tenant informed — all against the property and unit.` },
  { id: "q-maintenance-inspections", roles: ["agent"], category: "maintenance",
    q: "How do inspections work, and when should I do them?",
    a: `Pleks supports incoming (move-in) and outgoing (move-out) inspections, which the Rental Housing Act expects to be done jointly with the tenant. Capturing the property's condition at both ends — with dated, located photos — is what lets you justify (or rule out) deposit deductions fairly at the end of the lease.`,
    keywords: ["inspection", "move-in", "move-out", "ingoing", "outgoing"], legalCheck: true },
  { id: "q-maintenance-photos", roles: ["agent"], category: "maintenance",
    q: "Why must inspection photos be taken in the app?",
    a: `Inspection photos are compressed on your device before upload, and the GPS location and timestamp are extracted from the original photo first. That preserves a tamper-evident evidence chain (important for deposit disputes and the Tribunal) and keeps storage manageable.` },
  { id: "q-maintenance-deduction", roles: ["agent"], category: "maintenance",
    q: "How do I run a deposit deduction at the end of a lease?",
    a: `Open the lease and start the close-out. You itemise each deduction against the outgoing inspection with supporting evidence; Pleks calculates the refund balance, including interest, and produces the statement for the tenant. The disbursement is logged against the deposit ledger.`,
    keywords: ["deposit deduction", "close-out", "deposit refund"], legalCheck: true },
  { id: "q-maintenance-wear", roles: ["agent"], category: "maintenance",
    q: "What's the difference between wear-and-tear and damage?",
    a: `Normal wear and tear — the ordinary ageing you'd expect from reasonable use — cannot be deducted from a deposit; only damage beyond that can. Each item has to be classified and justified separately, which is why the move-in and move-out inspections matter: they're the evidence that an item changed beyond fair wear.`,
    keywords: ["wear and tear", "damage", "deduction"], legalCheck: true },
  { id: "q-maintenance-return-window", roles: ["agent"], category: "maintenance",
    q: "How long do I have to return a deposit?",
    a: `Under the Rental Housing Act, where there are no deductions the deposit (with interest) must be refunded within 14 days of the lease ending; where deductions are made, within 21 days, together with an itemised list and the receipts supporting each deduction. Pleks tracks the close-out against these windows.`,
    keywords: ["14 days", "21 days", "deposit timeline", "refund window"], legalCheck: true },
  { id: "q-maintenance-tribunal", roles: ["agent"], category: "maintenance",
    q: "What is the Tribunal evidence pack?",
    a: `If a deposit or tenancy matter goes to the Rental Housing Tribunal, Pleks can assemble the relevant records — lease, inspections with dated photos, the deposit ledger, the itemised deduction schedule and the communication history — into a single, ordered pack, so your case rests on a complete and consistent record rather than scattered files.`,
    keywords: ["tribunal", "evidence", "dispute"], legalCheck: true },
  { id: "q-maintenance-notices", roles: ["agent"], category: "maintenance",
    q: "Can I generate notices (breach, cancellation, demand)?",
    a: `Yes — Pleks has templates for common notices that draw on the relevant Rental Housing Act and Consumer Protection Act provisions, generated from the lease and sent for signature or delivery, with each one logged. Review them before sending; they support your process, they don't replace legal advice on a contested matter.`,
    legalCheck: true },

  // ── Agent — Utilities, municipal & schemes ────────────────────────────────────────────────
  { id: "q-utilities-municipal", roles: ["agent"], category: "utilities",
    q: "Can Pleks handle utilities and municipal bills?",
    a: `Pleks lets you record utilities and municipal charges against a property and recover them through the tenant's account where the lease provides for it. Municipal bills are captured by uploading the document, with the figures read off it, rather than scraped automatically.`,
    keywords: ["utilities", "water", "electricity", "municipal", "rates"] },
  { id: "q-utilities-schemes", roles: ["agent"], category: "utilities",
    q: "Does Pleks support HOA / sectional-title scheme management?",
    a: `Pleks includes a managing-schemes area for the body-corporate and HOA side of a managed property, alongside the rental management. The depth depends on your setup — start in Managing schemes to see what's enabled for your portfolio.`,
    keywords: ["hoa", "body corporate", "sectional title", "levy"] },

  // ── Agent — Reports, statements & team ────────────────────────────────────────────────────
  { id: "q-reports-statements", roles: ["agent"], category: "reports",
    q: "Where are owner statements and reports?",
    a: `Statements live under Statements, and broader reporting under Reports. Owner statements summarise income, fees and payouts for each landlord's portfolio; you can export them for your records or to send on.` },
  { id: "q-reports-export", roles: ["agent"], category: "reports",
    q: "Can I export my data to my accounting system?",
    a: `Yes — Pleks covers your property financials and exports them for use in your accounting package (such as Xero or Sage). Pleks is not a full accounting system; it keeps the property and trust side clean and hands the figures off to your books.`,
    keywords: ["xero", "sage", "accounting", "export"] },
  { id: "q-reports-team", roles: ["agent"], category: "reports",
    q: "How do I add staff and control what they can do?",
    a: `Invite team members from Settings and assign each a role (owner, property manager, agent, accountant, or maintenance manager). Roles determine what each person can access. Sensitive actions (trust writes, refunds, bank-detail or role changes, bulk exports) require a fresh re-confirmation — a "step-up" — even for signed-in staff.`,
    keywords: ["staff", "team", "roles", "permissions", "invite colleague"] },
  { id: "q-reports-stepup", roles: ["agent"], category: "reports",
    q: `What is the "Confirm it's you" step before a sensitive action?`,
    a: `For high-risk actions Pleks asks you to re-authenticate right then — with your passkey or an authenticator code — even though you're already signed in. It's a deliberate guard on the money and on account-security changes, so a single unattended session can't be used to move value.`,
    keywords: ["step-up", "confirm it's you", "re-authenticate"] },
  { id: "q-reports-staff-lockout", roles: ["agent"], category: "reports",
    q: "A staff member lost their phone and can't sign in — how do I help them?",
    a: `If they enrolled a passkey they can sign in with it on a trusted device without their authenticator. If not, an account owner can reset that staff member's second factor (a step-up-protected action), after which they re-enrol an authenticator. For anything you can't resolve, contact Pleks support.` },

  // ── Agent — Billing & subscription ────────────────────────────────────────────────────────
  { id: "q-billing-pricing", roles: ["agent"], category: "billing",
    q: "How is Pleks priced?",
    a: `Plans are tiered by the number of active leases you manage, not by the number of staff seats — every plan includes your whole team. The current tiers, prices and lease limits are shown on your Subscription page; you move up a tier as your managed-lease count grows.`,
    keywords: ["pricing", "tiers", "plans", "cost", "subscription"] },
  { id: "q-billing-seats", roles: ["agent"], category: "billing",
    q: "Am I charged per staff member or per user?",
    a: `No — there are no per-seat charges. You can add as many staff as your agency needs on any tier; the only thing that moves you between tiers is the number of active leases under management.` },
  { id: "q-billing-cancel", roles: ["agent"], category: "billing",
    q: "What happens to my data if I pause or cancel my subscription?",
    a: `You can always read and export your existing data — records, statements, audit bundles and legally-required notifications keep working even when a subscription is paused or cancelled. What's gated is creating new value (new leases, new properties beyond your tier, new screening checks, new AI outputs). Your history is never held hostage.`,
    keywords: ["cancel", "pause", "export data", "downgrade"] },
  { id: "q-billing-change", roles: ["agent"], category: "billing",
    q: "How do I upgrade or downgrade?",
    a: `Manage your plan under Settings → Subscription. Upgrades take effect immediately; you can downgrade as long as your active-lease count fits the lower tier's limit.` },

  // ── Landlord — Your portal ────────────────────────────────────────────────────────────────
  { id: "q-portal-access-ll", roles: ["landlord"], category: "portal",
    q: "How do I get access to my landlord portal?",
    a: `Your managing agent invites you — you'll get a link by email or WhatsApp to set up your own sign-in and confirm your details. From then on you sign in at ${APP_HOST} to your own oversight view; your agent runs the day-to-day.` },
  { id: "q-portal-see-ll", roles: ["landlord"], category: "portal",
    q: "What can I see in my landlord portal?",
    a: `Your dashboard shows your properties, your statements, a trust summary for money held on your behalf, and the maintenance happening across your portfolio. It's a read-and-oversight view — your managing agent runs the day-to-day, and you can see that it's being done correctly.` },
  { id: "q-portal-statements-ll", roles: ["landlord"], category: "portal",
    q: "Where do I find my statements?",
    a: `Under Statements. Each statement summarises the income, fees and payouts for your properties for the period, so you can reconcile what you received against what was collected.` },
  { id: "q-portal-payout-ll", roles: ["landlord"], category: "portal",
    q: "When and how do I get paid?",
    a: `Your managing agent pays you from their trust account according to your mandate. Pleks is not in the money flow — it gives you and your agent the statements and trust summary so every cent is accounted for, but the payout itself happens through your agent's bank.`,
    keywords: ["get paid", "payout", "when do i get my money"], legalCheck: true },
  { id: "q-portal-trust-ll", roles: ["landlord"], category: "portal",
    q: "What does the trust summary show me?",
    a: `It shows the money held on your behalf and how it reconciles — deposits, rent collected, fees and payouts. Because Pleks doesn't hold the money, this reflects your agent's trust-account reality, giving you independent visibility rather than a figure Pleks controls.`,
    legalCheck: true },
  { id: "q-portal-maintenance-ll", roles: ["landlord"], category: "portal",
    q: "Can I see and approve maintenance?",
    a: `Yes — maintenance across your properties is visible in the Maintenance section, including status and costs, so you're informed about work on your assets. Approval limits and who authorises spend are arranged with your managing agent.` },
  { id: "q-portal-deposit-ll", roles: ["landlord"], category: "portal",
    q: "How is my deposit money and interest handled?",
    a: `Tenant deposits are held in your agent's trust account, with interest tracked per the configured rate, and reconciled when a lease ends. Your statements and trust summary reflect deposit movements so nothing is unaccounted for.`,
    legalCheck: true },
  { id: "q-portal-agents-ll", roles: ["landlord"], category: "portal",
    q: "Can I have more than one managing agent, or change agents?",
    a: `Your portal reflects the properties a given agency manages for you. If your arrangements change, that's handled with the agency directly; speak to your managing agent about how your portfolio is set up in Pleks.` },
  { id: "q-portal-tenants-ll", roles: ["landlord"], category: "portal",
    q: "Can I see who my tenants are and how their leases are doing?",
    a: `Your oversight view shows the leases, their status and the financial position across your properties — enough to see that your portfolio is being managed correctly — while the day-to-day tenant management stays with your agent.` },

  // ── Tenant — Applications & screening ─────────────────────────────────────────────────────
  { id: "q-applications-apply-t", roles: ["tenant"], category: "applications",
    q: "How do I apply for a property?",
    a: `Complete the application your agent sends you, including the personal and income details requested. A screening check is run as part of the application; once approved and your lease is activated, you move from applicant to tenant with access to your tenant portal.` },
  { id: "q-applications-cost-t", roles: ["tenant"], category: "applications",
    q: "What does it cost to apply, and what is the screening?",
    a: `A single application is ${APP_FEE} and a joint application is ${JOINT_FEE} — a screening fee tied to the application, separate from rent and deposit. Screening looks at affordability (your rent against your income) and the checks relevant to the application, and is only run with your consent.`,
    keywords: ["application fee", "screening", "credit check"], legalCheck: true },
  { id: "q-applications-consent-t", roles: ["tenant"], category: "applications",
    q: "Why do you need my consent to run a check, and what happens to my data?",
    a: `Credit and identity checks may only be run with your explicit permission, so you're asked to consent before anything is requested, and that consent is recorded. The report is kept only as long as needed and protected under POPIA; you can see what's held from the Privacy section of your portal.`,
    keywords: ["consent", "credit check", "my data"], legalCheck: true },
  { id: "q-applications-result-t", roles: ["tenant"], category: "applications",
    q: "Where can I see my application or screening result?",
    a: `In your portal under Screening, you can view the application linked to you and its outcome. Your agent makes the final approval decision.` },
  { id: "q-applications-movein-t", roles: ["tenant"], category: "applications",
    q: "What is a move-in inspection and why does it matter?",
    a: `A move-in (incoming) inspection records the condition of the property when you take occupation, ideally done together with your agent and with dated photos. It's your protection too: it's the baseline that decides, fairly, what is normal wear and what is damage when your deposit is settled at the end.`,
    legalCheck: true },

  // ── Tenant — Paying rent & deposits ───────────────────────────────────────────────────────
  { id: "q-payments-pay-t", roles: ["tenant"], category: "payments",
    q: "How do I pay my rent?",
    a: `Pleks does not take card or EFT payments directly. Pay using the banking details or method on your lease (usually EFT into your agency's account, or a debit order you arranged with them). Once your payment reflects on the agency's bank statement it is matched and appears in your payment history.`,
    keywords: ["pay rent", "eft", "how do i pay", "banking details"], legalCheck: true },
  { id: "q-payments-balance-t", roles: ["tenant"], category: "payments",
    q: "Where do I see what I've paid and what I owe?",
    a: `Open Payments in your portal. It shows your payment history and current balance once payments have reflected and been matched. If something looks wrong, contact your agency — they manage the account.`,
    keywords: ["balance", "statement", "what do i owe"] },
  { id: "q-payments-notshowing-t", roles: ["tenant"], category: "payments",
    q: "My payment isn't showing yet — what should I do?",
    a: `Bank transfers and debit orders take a day or two to reflect, and your payment only appears once it lands on the agency's statement and is matched — there's no need to pay again. If it still hasn't shown after a few business days, contact your agency with your proof of payment.`,
    keywords: ["payment not showing", "proof of payment", "pending"] },
  { id: "q-payments-behind-t", roles: ["tenant"], category: "payments",
    q: "I can't pay this month / I'm behind — what should I do?",
    a: `Contact your managing agent as early as possible to discuss an arrangement. Pleks may send you reminders on the agency's behalf when an account falls behind; responding early and agreeing a plan with your agent is the best step.`,
    keywords: ["can't pay", "arrears", "behind on rent"] },
  { id: "q-payments-deposit-held-t", roles: ["tenant"], category: "payments",
    q: "Where is my deposit held and do I earn interest?",
    a: `Your deposit is held in your managing agent's trust account (not by Pleks), and interest accrues according to the configured rate. At the end of the lease it's reconciled — interest added, any agreed deductions applied with evidence — and the balance returned.`,
    legalCheck: true },
  { id: "q-payments-deposit-back-t", roles: ["tenant"], category: "payments",
    q: "When and how do I get my deposit back?",
    a: `After you move out and the outgoing inspection is done, your deposit and interest are refunded — within 14 days if there are no deductions, or within 21 days if deductions are made, in which case you're given an itemised list with the receipts. Normal wear and tear can't be deducted; only damage beyond that.`,
    keywords: ["deposit back", "deposit refund", "get my deposit", "14 days", "21 days"], legalCheck: true },
  { id: "q-payments-dispute-t", roles: ["tenant"], category: "payments",
    q: "I don't agree with a deduction from my deposit — what can I do?",
    a: `First raise it with your managing agent — you're entitled to the itemised deductions and the supporting evidence, and the move-in and move-out inspections are the reference. If it stays unresolved, you can approach the Rental Housing Tribunal, which resolves rental disputes at no cost to you.`,
    keywords: ["dispute deduction", "tribunal", "unfair deduction"], legalCheck: true },

  // ── Tenant — Living in your home ──────────────────────────────────────────────────────────
  { id: "q-living-maintenance-t", roles: ["tenant"], category: "living",
    q: "How do I log a maintenance request?",
    a: `Go to Maintenance → New request, describe the issue and add photos if you can. You can then track its status and any messages under Maintenance. Your agent assigns a supplier and keeps you updated.`,
    keywords: ["report maintenance", "something broken", "repair"] },
  { id: "q-living-lease-access-t", roles: ["tenant"], category: "living",
    q: "Where do I find my lease and property access details?",
    a: `Your current lease is under Lease, and any access information your agent has shared (gate codes, instructions) is under Access. If something's missing, message your agent through the portal.`,
    keywords: ["my lease", "gate code", "access"] },
  { id: "q-living-message-t", roles: ["tenant"], category: "living",
    q: "How do I message my agency?",
    a: `Use the Communications section to see messages and notices from your agency and to follow up. Important notifications are also sent to you by email or WhatsApp/SMS depending on your agency's setup.` },
  { id: "q-living-lease-end-t", roles: ["tenant"], category: "living",
    q: "My lease is coming to an end — what are my options?",
    a: `Your agent will usually reach out before your lease expires about renewing or continuing month-to-month. If you're planning to move out, give notice as your lease requires and arrange the move-out inspection, which sets up your deposit refund. Speak to your agent early so the timing works for both sides.`,
    legalCheck: true },
  { id: "q-living-notice-t", roles: ["tenant"], category: "living",
    q: "How do I give notice that I'm moving out?",
    a: `Give notice in the way and within the period your lease sets out (commonly one calendar month), through your agency. Once notice is given, the outgoing inspection and deposit close-out follow, so arrange the inspection date with your agent.`,
    keywords: ["give notice", "moving out", "vacate"], legalCheck: true },

  // ── Supplier — Jobs & invoices ────────────────────────────────────────────────────────────
  { id: "q-jobs-see", roles: ["supplier"], category: "jobs",
    q: "How do I see jobs assigned to me?",
    a: `Open Jobs in your supplier portal to see the maintenance jobs an agency has assigned to you, with the property, the issue and the contact details. Each job has its own page where you can see the full request and updates.`,
    keywords: ["jobs", "work orders", "assigned"] },
  { id: "q-jobs-quote", roles: ["supplier"], category: "jobs",
    q: "How do I submit a quote?",
    a: `Open the job and choose Quote to submit your price and any notes for the agency's approval. The agent reviews it before work proceeds, and you'll see the status change once they respond.`,
    keywords: ["quote", "quotation", "estimate"] },
  { id: "q-jobs-progress", roles: ["supplier"], category: "jobs",
    q: "How do I update progress or report a delay?",
    a: `From the job page, update the status as you go and flag any delay with the reason. Keeping the job updated keeps the agent, landlord and tenant informed and your record clean.` },
  { id: "q-jobs-statuses", roles: ["supplier"], category: "jobs",
    q: "What do the job statuses mean?",
    a: `A job moves through stages — typically from assigned, to scheduled, to on-site, to done — and you advance it as the work progresses. Each step you record, with notes and photos, keeps everyone informed and gives the agency a clean history of the work.` },
  { id: "q-jobs-photos", roles: ["supplier"], category: "jobs",
    q: "Should I add photos and notes to a job?",
    a: `Yes — photos and short notes at each stage (before, during, after) are the record of what you did. They help the agent approve and pay faster, keep the tenant and landlord informed, and protect you if there's ever a question about the work.` },
  { id: "q-jobs-invoice", roles: ["supplier"], category: "jobs",
    q: "How do I get paid / submit an invoice?",
    a: `Submit your invoice for a completed job under Invoices. Pleks is not a payment processor — it routes your invoice and its status to the agency, who pays you through their own banking. Track each invoice's status in the Invoices section.`,
    keywords: ["invoice", "get paid", "payment"], legalCheck: true },
  { id: "q-jobs-multi", roles: ["supplier"], category: "jobs",
    q: "Can I work with more than one agency on Pleks?",
    a: `Yes — your supplier portal shows the jobs assigned to you by any agency using Pleks, each against its own property and contact. Keep your profile and banking details current so every agency reaches and pays the right account.` },
  { id: "q-jobs-profile", roles: ["supplier"], category: "jobs",
    q: "How do I update my company / contact details?",
    a: `Keep your details current under Profile so agencies can reach you and pay the right account. Accurate contact and banking information avoids delays on jobs and invoices.` },
]

/** Entries visible to a given role (D-HELP-02). */
export function entriesForRole(role: HelpRole): HelpEntry[] {
  return HELP_ENTRIES.filter((e) => e.roles.includes(role))
}

/** Categories (ordered) that have at least one entry for the role — empty ones don't render. */
export function categoriesForRole(role: HelpRole): HelpCategory[] {
  const present = new Set(entriesForRole(role).map((e) => e.category))
  return HELP_CATEGORIES.filter((c) => present.has(c.id))
}
