/**
 * lib/reports/screening/_pdf/primitives/AttestationCard.tsx
 *
 * Document attestation block — body content, not chrome. Replaces the per-page AuditStrip.
 * Placed as the last child of the final DocumentShell by the composing template.
 * Carries version metadata, inputs hash, help URL, and POPIA contact.
 * Spec: ADDENDUM_14H_FITSCORE_DELIVERY.md §E.3 density retune.
 */

import { View, Text, StyleSheet } from "@react-pdf/renderer"
import { C, D, FONTS, sp, fmtDate } from "./theme"
import type { FitScoreReportData } from "./theme"
import { BlockHeader } from "./BlockHeader"

const S = StyleSheet.create({
  wrap: { marginBottom: D.primitiveGap },
  card: {
    borderWidth:     0.75,
    borderColor:     C.rule.base,
    backgroundColor: C.surface.paperRaised,
  },
  cardBody: {
    paddingHorizontal: D.cardPaddingX,
    paddingVertical:   D.cardPaddingY,
  },

  metaBlock: {
    paddingBottom:     D.cardPaddingY,
    borderBottomWidth: 0.75,
    borderBottomColor: C.rule.base,
    marginBottom:      D.cardPaddingY,
  },
  metaRow: {
    flexDirection: 'row',
    marginBottom:  4,
  },
  metaRowLast: { marginBottom: 0 },
  metaKey: {
    fontFamily:    FONTS.mono,
    fontSize:      7,
    letterSpacing: 0.5,
    color:         C.ink.mute,
    width:         80,
  },
  metaVal: {
    fontFamily:    FONTS.mono,
    fontSize:      7,
    letterSpacing: 0.3,
    color:         C.ink.primary,
    flex:          1,
  },

  prose: {
    fontFamily:    FONTS.mono,
    fontSize:      7.5,
    color:         C.ink.mute,
    letterSpacing: 0.3,
    lineHeight:    1.65,
    marginBottom:  10,
  },

  linkBlock: { marginBottom: 8 },
  linkBlockLast: { marginBottom: 0 },
  linkLabel: {
    fontFamily:    FONTS.mono,
    fontSize:      7,
    letterSpacing: 0.5,
    color:         C.ink.mute,
    textTransform: 'uppercase',
    marginBottom:  2,
  },
  linkUrl: {
    fontFamily:    FONTS.mono,
    fontSize:      7,
    letterSpacing: 0.3,
    color:         C.ink.primary,
  },
})

interface AttestationCardProps {
  data: FitScoreReportData
}

export function AttestationCard({ data }: Readonly<AttestationCardProps>) {
  const appUrl      = process.env.NEXT_PUBLIC_APP_URL ?? 'https://app.pleks.co.za'
  const displayHost = appUrl.replace(/^https?:\/\//, '')
  const helpUrl     = `${displayHost}/help/fitscore-report/${sp(data.interpretationVersion)}`

  return (
    <View style={S.wrap} wrap={false}>
      <View style={S.card}>
        <BlockHeader
          label="3.3"
          title="Document attestation"
          rightTag={sp(data.applicationRef)}
        />
        <View style={S.cardBody}>
          <View style={S.metaBlock}>
            <View style={S.metaRow}>
              <Text style={S.metaKey}>Engine</Text>
              <Text style={S.metaVal}>{sp(data.engineVersion)}</Text>
            </View>
            <View style={S.metaRow}>
              <Text style={S.metaKey}>Narrative</Text>
              <Text style={S.metaVal}>{sp(data.narrativeVersion)}</Text>
            </View>
            <View style={S.metaRow}>
              <Text style={S.metaKey}>Interpretation</Text>
              <Text style={S.metaVal}>{sp(data.interpretationVersion)}</Text>
            </View>
            <View style={[S.metaRow, S.metaRowLast]}>
              <Text style={S.metaKey}>Inputs hash</Text>
              <Text style={S.metaVal}>{`sha256:${sp(data.inputsHash)}`}</Text>
            </View>
          </View>

          <Text style={S.prose}>
            {`This report was generated by Pleks at ${sp(fmtDate(data.generatedAt))} for application ${sp(data.applicationRef)}.`}
          </Text>

          <View style={S.linkBlock}>
            <Text style={S.linkLabel}>How to read this report</Text>
            <Text style={S.linkUrl}>{helpUrl}</Text>
          </View>

          <View style={S.linkBlockLast}>
            <Text style={S.linkLabel}>POPIA access requests</Text>
            <Text style={S.linkUrl}>privacy@pleks.co.za</Text>
          </View>
        </View>
      </View>
    </View>
  )
}
