/**
 * lib/reports/screening/_pdf/primitives/AttestationCard.tsx
 *
 * Document attestation block — body content, not chrome. Replaces the per-page AuditStrip.
 * Placed as the last child of the final DocumentShell by the composing template.
 * Carries version metadata, inputs hash, help URL, and POPIA contact.
 * Spec: ADDENDUM_14H_FITSCORE_DELIVERY.md §E.3 density retune.
 */

import { View, Text, StyleSheet } from "@react-pdf/renderer"
import { C, FONTS, sp, fmtDate } from "./theme"
import type { FitScoreReportData } from "./theme"

const S = StyleSheet.create({
  wrap: {
    borderTopWidth:    1,
    borderTopColor:    C.ink.primary,
    borderBottomWidth: 1,
    borderBottomColor: C.rule.base,
    paddingVertical:   14,
    marginTop:         4,
  },

  headerRow: {
    flexDirection:  'row',
    justifyContent: 'space-between',
    alignItems:     'baseline',
    marginBottom:   12,
  },
  headerLabel: {
    fontFamily:    FONTS.mono,
    fontSize:      7.5,
    letterSpacing: 1,
    textTransform: 'uppercase',
    color:         C.ink.primary,
  },
  headerRef: {
    fontFamily:    FONTS.mono,
    fontSize:      7,
    letterSpacing: 0.5,
    color:         C.ink.mute,
  },

  metaBlock: {
    marginBottom:   12,
    paddingBottom:  12,
    borderBottomWidth: 0.75,
    borderBottomColor: C.rule.base,
  },
  metaRow: {
    flexDirection: 'row',
    marginBottom:  4,
  },
  metaRowLast: { marginBottom: 0 },
  metaKey: {
    fontFamily:    FONTS.mono,
    fontSize:      7,
    letterSpacing: 0.5,
    color:         C.ink.mute,
    width:         80,
  },
  metaVal: {
    fontFamily:    FONTS.mono,
    fontSize:      7,
    letterSpacing: 0.3,
    color:         C.ink.primary,
    flex:          1,
  },

  prose: {
    fontFamily:  FONTS.mono,
    fontSize:    7.5,
    color:       C.ink.mute,
    letterSpacing: 0.3,
    lineHeight:  1.65,
    marginBottom: 10,
  },

  linkBlock: { marginBottom: 8 },
  linkLabel: {
    fontFamily:    FONTS.mono,
    fontSize:      7,
    letterSpacing: 0.5,
    color:         C.ink.mute,
    textTransform: 'uppercase',
    marginBottom:  2,
  },
  linkUrl: {
    fontFamily:    FONTS.mono,
    fontSize:      7,
    letterSpacing: 0.3,
    color:         C.ink.primary,
  },
})

interface AttestationCardProps {
  data: FitScoreReportData
}

export function AttestationCard({ data }: Readonly<AttestationCardProps>) {
  const appUrl      = process.env.NEXT_PUBLIC_APP_URL ?? 'https://app.pleks.co.za'
  const displayHost = appUrl.replace(/^https?:\/\//, '')
  const helpUrl     = `${displayHost}/help/fitscore-report/${sp(data.interpretationVersion)}`

  return (
    <View style={S.wrap} wrap={false}>
      <View style={S.headerRow}>
        <Text style={S.headerLabel}>Document attestation</Text>
        <Text style={S.headerRef}>{sp(data.applicationRef)}</Text>
      </View>

      <View style={S.metaBlock}>
        <View style={S.metaRow}>
          <Text style={S.metaKey}>Engine</Text>
          <Text style={S.metaVal}>{sp(data.engineVersion)}</Text>
        </View>
        <View style={S.metaRow}>
          <Text style={S.metaKey}>Narrative</Text>
          <Text style={S.metaVal}>{sp(data.narrativeVersion)}</Text>
        </View>
        <View style={S.metaRow}>
          <Text style={S.metaKey}>Interpretation</Text>
          <Text style={S.metaVal}>{sp(data.interpretationVersion)}</Text>
        </View>
        <View style={[S.metaRow, S.metaRowLast]}>
          <Text style={S.metaKey}>Inputs hash</Text>
          <Text style={S.metaVal}>{`sha256:${sp(data.inputsHash)}`}</Text>
        </View>
      </View>

      <Text style={S.prose}>
        {`This report was generated by Pleks at ${sp(fmtDate(data.generatedAt))} for application ${sp(data.applicationRef)}.`}
      </Text>

      <View style={S.linkBlock}>
        <Text style={S.linkLabel}>How to read this report</Text>
        <Text style={S.linkUrl}>{helpUrl}</Text>
      </View>

      <View style={S.linkBlock}>
        <Text style={S.linkLabel}>POPIA access requests</Text>
        <Text style={S.linkUrl}>privacy@pleks.co.za</Text>
      </View>
    </View>
  )
}
